// One-time content backfill: Mindset 1 vocabulary, grouped 2 units per
// VocabularyLesson ("Mindset 1 Unit X-Y") — same shared/curriculum-lesson
// approach as scripts/seedVocabLessonsMindset0.js (see that file for the
// full rationale: VocabularyLesson vs VocabBook, required parser fields).
//
// Run: node scripts/seedVocabLessonsMindset1.js
'use strict';

const ADMIN_EMAIL = 'tranhadeeptry@gmail.com'; // existing admin — createdBy

// ── Unit 1: Relationships ────────────────────────────────────────────────
const unit1 = [
  ['relationship', 'mối quan hệ', 'Trust and honesty are the foundation of any healthy relationship.', 'the way in which two or more people are connected, or feel and behave towards each other'],
  ['close relationship', 'mối quan hệ thân thiết', 'She has a close relationship with her grandmother.', 'a relationship in which people know and trust each other well'],
  ['family relationship', 'mối quan hệ gia đình', 'Family relationships can have a huge influence on a person\'s confidence.', 'the connection and bond between members of a family'],
  ['family ties', 'mối ràng buộc gia đình', 'Even after moving abroad, she kept strong family ties.', 'the emotional bonds and sense of connection between family members'],
  ['friendship', 'tình bạn', 'Their friendship has lasted since primary school.', 'a relationship between friends'],
  ['close friend', 'bạn thân', 'He\'s been my close friend since university.', 'a friend one knows very well and trusts deeply'],
  ['childhood friend', 'bạn thời thơ ấu', 'I bumped into a childhood friend at the airport.', 'a friend one has known since childhood'],
  ['best friend', 'bạn thân nhất', 'She tells her best friend everything.', 'the friend one is closest to'],
  ['acquaintance', 'người quen', 'He\'s more of an acquaintance than a close friend.', 'a person one knows slightly, but not closely'],
  ['colleague', 'đồng nghiệp', 'She gets on well with all her colleagues.', 'a person one works with'],
  ['get along with', 'hòa hợp với', 'He gets along with almost everyone at work.', 'to have a friendly relationship with someone'],
  ['get on well with', 'hòa hợp tốt với', 'She gets on well with her new flatmate.', 'to have a good relationship with someone'],
  ['fall out with', 'bất hòa với', 'The two brothers fell out with each other over money.', 'to have an argument or disagreement with someone, damaging the relationship'],
  ['make up with', 'làm hòa với', 'They made up with each other after a long argument.', 'to become friendly again with someone after a disagreement'],
  ['keep in touch with', 'giữ liên lạc với', 'We still keep in touch with our old classmates.', 'to continue communicating regularly with someone'],
  ['lose touch with', 'mất liên lạc với', 'I lost touch with most of my school friends after graduating.', 'to stop communicating with someone over time'],
  ['rely on someone', 'dựa vào ai đó', 'She knows she can always rely on her sister.', 'to depend on someone for help or support'],
  ['trust someone', 'tin tưởng ai đó', 'It takes time to fully trust someone.', 'to believe that someone is honest and reliable'],
  ['mutual respect', 'sự tôn trọng lẫn nhau', 'A good relationship is built on mutual respect.', 'respect that two or more people have for each other'],
  ['mutual understanding', 'sự thấu hiểu lẫn nhau', 'The couple reached a mutual understanding after talking things through.', 'a shared understanding between two or more people'],
  ['support each other', 'hỗ trợ lẫn nhau', 'Good friends support each other through difficult times.', 'to help and encourage one another'],
  ['have things in common', 'có điểm chung', 'They became friends quickly because they had a lot in common.', 'to share similar interests, experiences or opinions'],
  ['share common interests', 'chia sẻ sở thích chung', 'The club brings together people who share common interests.', 'to have the same hobbies or interests as someone else'],
  ['build a relationship', 'xây dựng mối quan hệ', 'It takes time and effort to build a strong relationship.', 'to gradually develop a connection with someone'],
  ['maintain a relationship', 'duy trì mối quan hệ', 'Busy schedules can make it hard to maintain close relationships.', 'to keep a relationship going over time'],
  ['strengthen a relationship', 'củng cố mối quan hệ', 'Spending quality time together can strengthen a relationship.', 'to make a relationship closer or more secure'],
  ['break up with someone', 'chia tay ai đó', 'She broke up with her boyfriend after two years.', 'to end a romantic relationship with someone'],
  ['split up', 'chia tay/ly thân', 'The couple split up after years of arguing.', 'to end a relationship or marriage'],
  ['get married', 'kết hôn', 'They got married last summer in a small ceremony.', 'to become husband and wife'],
  ['marriage', 'hôn nhân', 'A happy marriage requires effort from both partners.', 'the legal union of two people as partners'],
  ['spouse', 'vợ/chồng', 'Her spouse works in a different city during the week.', 'a husband or wife'],
  ['partner', 'bạn đời/đối tác', 'He introduced his partner to his parents.', 'a person one is in a romantic relationship with'],
  ['in a relationship', 'đang trong một mối quan hệ', 'She\'s been in a relationship for three years.', 'romantically involved with someone'],
  ['single', 'độc thân', 'He\'s been single since last year.', 'not in a romantic relationship'],
  ['long-distance relationship', 'mối quan hệ yêu xa', 'Long-distance relationships require a lot of trust.', 'a romantic relationship between people who live far apart'],
  ['sibling rivalry', 'sự ganh đua giữa anh chị em', 'Sibling rivalry is common in families with more than one child.', 'competition or jealousy between brothers and sisters'],
  ['generation gap', 'khoảng cách thế hệ', 'There\'s often a generation gap between parents and teenagers.', 'a difference in attitudes and values between older and younger generations'],
  ['parent-child relationship', 'mối quan hệ cha mẹ - con cái', 'Open communication improves the parent-child relationship.', 'the bond and connection between a parent and their child'],
  ['role model', 'hình mẫu/tấm gương', 'Her older sister has always been her role model.', 'a person whose behaviour is copied by others as a positive example'],
  ['peer group', 'nhóm bạn cùng trang lứa', 'Teenagers are strongly influenced by their peer group.', 'a group of people of a similar age or social status'],
  ['social circle', 'vòng bạn bè', 'University helped her expand her social circle.', 'the group of people someone regularly socialises with'],
  ['form a bond', 'hình thành mối liên kết', 'The two roommates formed a strong bond in their first year.', 'to develop a close connection with someone'],
  ['develop a friendship', 'phát triển tình bạn', 'They developed a friendship after working on the same project.', 'to gradually build a friendly relationship with someone'],
  ['drift apart', 'dần xa cách', 'Old friends sometimes drift apart after moving to different cities.', 'to gradually stop being close to someone over time'],
  ['reconcile with someone', 'làm hòa với ai đó', 'The brothers finally reconciled after years of silence.', 'to become friendly again with someone after a disagreement'],
  ['communication', 'sự giao tiếp', 'Good communication is essential in any relationship.', 'the exchange of information or feelings between people'],
  ['open communication', 'giao tiếp cởi mở', 'Open communication helps couples avoid misunderstandings.', 'honest and direct communication between people'],
  ['loyalty', 'lòng trung thành', 'Loyalty is one of the most important qualities in a friend.', 'the quality of being faithful and supportive'],
  ['trust issues', 'vấn đề về lòng tin', 'He has trust issues after being betrayed in the past.', 'difficulty trusting other people, often due to past experiences'],
  ['resolve a conflict', 'giải quyết mâu thuẫn', 'They sat down together to resolve the conflict calmly.', 'to find a solution to a disagreement'],
  ['compromise', 'sự thỏa hiệp', 'A good relationship often requires compromise from both sides.', 'an agreement reached by each side giving up some demands'],
  ['empathy', 'sự đồng cảm', 'Empathy helps us understand what other people are feeling.', 'the ability to understand and share the feelings of another person'],
  ['emotional support', 'sự hỗ trợ tinh thần', 'Friends can provide valuable emotional support during hard times.', 'comfort and encouragement given to someone going through difficulty'],
  ['confide in someone', 'tâm sự với ai đó', 'She confides in her best friend about everything.', 'to tell someone private feelings or information, trusting them not to share it'],
  ['betray someone\'s trust', 'phản bội lòng tin của ai đó', 'Lying to a friend can betray their trust.', 'to break someone\'s confidence by being dishonest or disloyal'],
  ['quality time', 'thời gian chất lượng', 'Parents should spend quality time with their children.', 'time spent giving full attention to a person or activity'],
  ['blood relative', 'người thân ruột thịt', 'She only invited blood relatives to the small wedding.', 'a relative connected by birth rather than marriage'],
  ['in-laws', 'gia đình bên vợ/chồng', 'She gets along well with her in-laws.', 'the family of one\'s husband or wife'],
  ['close-knit family', 'gia đình gắn bó', 'He grew up in a close-knit family that did everything together.', 'a family whose members are very close and supportive of one another'],
  ['see eye to eye with someone', 'đồng quan điểm với ai đó', 'The two colleagues don\'t always see eye to eye on decisions.', 'to agree with someone about something'],
  ['be on good terms with someone', 'có mối quan hệ tốt với ai đó', 'She\'s on good terms with all her former colleagues.', 'to have a friendly relationship with someone'],
];

// ── Unit 2: Places and Buildings ─────────────────────────────────────────
const unit2 = [
  ['building', 'tòa nhà', 'The building was constructed over a hundred years ago.', 'a structure with a roof and walls, such as a house or office'],
  ['structure', 'kết cấu/công trình', 'The bridge is an impressive engineering structure.', 'something built or constructed, especially a large one'],
  ['architecture', 'kiến trúc', 'The city is famous for its unique architecture.', 'the art and practice of designing buildings'],
  ['architectural style', 'phong cách kiến trúc', 'The old town has a distinctive architectural style.', 'a particular way buildings are designed, often typical of a period or region'],
  ['skyscraper', 'tòa nhà chọc trời', 'New skyscrapers keep appearing in the city skyline.', 'a very tall modern building, usually in a city'],
  ['high-rise building', 'tòa nhà cao tầng', 'Many people in the city live in high-rise buildings.', 'a tall building with many floors'],
  ['residential building', 'tòa nhà dân cư', 'The new residential building has over two hundred flats.', 'a building where people live'],
  ['commercial building', 'tòa nhà thương mại', 'The commercial building houses several offices and shops.', 'a building used for business purposes'],
  ['public building', 'công trình công cộng', 'The library is one of the city\'s oldest public buildings.', 'a building open to and used by the general public'],
  ['historic building', 'công trình lịch sử', 'The historic building has been carefully restored.', 'a building that is old and important because of its history'],
  ['landmark', 'địa danh/công trình nổi bật', 'The tower has become a famous landmark of the city.', 'a well-known building or feature that is easily recognised'],
  ['monument', 'đài tưởng niệm/di tích', 'The monument was built to honour soldiers who died in the war.', 'a structure built to remember an important person or event'],
  ['cityscape', 'cảnh quan thành phố', 'The rooftop offers a wonderful view of the cityscape.', 'the visual appearance of a city, especially its buildings'],
  ['skyline', 'đường chân trời thành phố', 'The city\'s skyline changes every few years as new towers are built.', 'the outline of buildings against the sky'],
  ['urban area', 'khu vực đô thị', 'More than half the population now lives in urban areas.', 'a town or city area, as opposed to the countryside'],
  ['rural area', 'khu vực nông thôn', 'Life in a rural area is often quieter than in a city.', 'an area in the countryside, away from towns and cities'],
  ['suburb', 'vùng ngoại ô', 'Many families choose to live in the suburbs for more space.', 'a residential area on the edge of a city'],
  ['neighbourhood', 'khu dân cư', 'It\'s a friendly neighbourhood with a strong sense of community.', 'a district or area within a town or city'],
  ['district', 'quận/khu vực', 'The financial district is full of tall office buildings.', 'an area of a town, city or country, especially for a particular purpose'],
  ['city centre', 'trung tâm thành phố', 'The city centre gets very crowded on weekends.', 'the main, usually busiest, part of a city'],
  ['downtown area', 'khu trung tâm thành phố', 'The downtown area is home to most of the shops and restaurants.', 'the central or main business area of a city'],
  ['residential area', 'khu dân cư', 'The new school was built in a quiet residential area.', 'an area where people mainly live, rather than work or shop'],
  ['infrastructure', 'cơ sở hạ tầng', 'The city needs better infrastructure to cope with population growth.', 'the basic structures and facilities needed for a place to function, e.g. roads'],
  ['public transport system', 'hệ thống giao thông công cộng', 'The city has an efficient public transport system.', 'the network of buses, trains and other shared vehicles in an area'],
  ['construction', 'việc xây dựng', 'Construction of the new bridge is expected to finish next year.', 'the process of building something'],
  ['under construction', 'đang được xây dựng', 'The new stadium is still under construction.', 'in the process of being built'],
  ['construct a building', 'xây dựng một tòa nhà', 'The company plans to construct a new office building downtown.', 'to build something'],
  ['design a building', 'thiết kế một tòa nhà', 'The architect designed the building with large glass windows.', 'to plan the appearance and structure of a building'],
  ['renovate a building', 'cải tạo một tòa nhà', 'The old theatre was renovated and reopened last year.', 'to repair and improve an old building'],
  ['restore a building', 'khôi phục một tòa nhà', 'The council restored the historic building to its original condition.', 'to return a building to its original condition'],
  ['demolish a building', 'phá dỡ một tòa nhà', 'The old factory was demolished to make way for flats.', 'to completely destroy a building, usually on purpose'],
  ['tear down a building', 'phá bỏ một tòa nhà', 'They tore down the old cinema to build a shopping centre.', 'to demolish a building'],
  ['preserve a building', 'bảo tồn một tòa nhà', 'Local residents fought to preserve the historic building.', 'to protect a building from damage or destruction'],
  ['building material', 'vật liệu xây dựng', 'Concrete is one of the most common building materials.', 'a substance used to construct buildings'],
  ['foundation', 'nền móng', 'Workers spent weeks laying the foundation of the new building.', 'the solid base on which a building is constructed'],
  ['rooftop', 'nóc nhà/sân thượng', 'The restaurant on the rooftop offers stunning views.', 'the top surface or roof of a building'],
  ['facade', 'mặt tiền', 'The building\'s stone facade has been carefully cleaned.', 'the front outer wall of a building'],
  ['spacious', 'rộng rãi', 'The apartment is bright and spacious.', 'having a lot of space'],
  ['cramped', 'chật chội', 'Their office is cramped, with barely enough room for everyone.', 'uncomfortably small in space'],
  ['overcrowded', 'quá tải/đông đúc', 'The city centre becomes overcrowded during rush hour.', 'containing too many people or things for the available space'],
  ['modern building', 'tòa nhà hiện đại', 'The museum is housed in a striking modern building.', 'a building designed and constructed using current styles and technology'],
  ['traditional building', 'công trình truyền thống', 'Traditional buildings in the old quarter are made of wood.', 'a building constructed in a style typical of the past'],
  ['sustainable building', 'công trình bền vững', 'Sustainable buildings use less energy and fewer resources.', 'a building designed to have minimal harmful effects on the environment'],
  ['green building', 'công trình xanh', 'Green buildings often use solar panels and natural light.', 'a building designed to reduce its environmental impact'],
  ['energy-efficient building', 'tòa nhà tiết kiệm năng lượng', 'The new office is an energy-efficient building with solar panels.', 'a building designed to use as little energy as possible'],
  ['public space', 'không gian công cộng', 'The city has created more public spaces for residents to relax.', 'an area that is open and accessible to everyone'],
  ['green space', 'không gian xanh', 'Green spaces in cities help improve air quality.', 'an area with grass, trees or plants, especially in a town or city'],
  ['open space', 'không gian mở', 'The park provides open space for families to enjoy.', 'an area of land that is not built on'],
  ['car park', 'bãi đỗ xe', 'The shopping centre has a large underground car park.', 'an area or building where vehicles may be parked'],
  ['shopping mall', 'trung tâm thương mại', 'The new shopping mall attracts thousands of visitors each week.', 'a large building or group of buildings containing many shops'],
  ['town planning', 'quy hoạch đô thị', 'Good town planning can reduce traffic congestion.', 'the organised design and development of towns and cities'],
  ['urban planning', 'quy hoạch đô thị', 'Urban planning aims to make cities more liveable.', 'the process of designing how a city\'s land and buildings are used'],
  ['urban development', 'phát triển đô thị', 'Urban development has transformed the once-quiet town.', 'the process of building and expanding towns and cities'],
  ['urban sprawl', 'sự mở rộng đô thị không kiểm soát', 'Urban sprawl has led to the loss of farmland near the city.', 'the uncontrolled expansion of a city into surrounding areas'],
  ['gentrification', 'quá trình nâng cấp khu dân cư', 'Gentrification has pushed up housing prices in the area.', 'the process by which a poor area of a city becomes wealthier as new people move in'],
  ['property price', 'giá bất động sản', 'Property prices have risen sharply in the city centre.', 'the cost of buying land or buildings'],
  ['property developer', 'nhà phát triển bất động sản', 'The property developer plans to build 500 new homes.', 'a person or company that buys land and builds on it to sell or rent'],
  ['blend in with the surroundings', 'hòa hợp với môi trường xung quanh', 'The new building was designed to blend in with the surroundings.', 'to look similar to and fit well with what is nearby'],
  ['stand out from', 'nổi bật so với', 'The glass tower stands out from the older buildings nearby.', 'to be noticeably different from what surrounds it'],
  ['be located in', 'tọa lạc tại', 'The museum is located in the heart of the city.', 'to be positioned or situated in a particular place'],
  ['dominate the skyline', 'thống trị đường chân trời', 'The cathedral used to dominate the city\'s skyline.', 'to be the most noticeable feature in a view of a city'],
];

// ── Unit 3: Education and Employment ─────────────────────────────────────
const unit3 = [
  ['education', 'giáo dục', 'Education plays a vital role in a country\'s development.', 'the process of teaching and learning, especially in schools'],
  ['educational institution', 'cơ sở giáo dục', 'The university is one of the oldest educational institutions in the country.', 'an organisation such as a school or university that provides education'],
  ['academic achievement', 'thành tích học tập', 'Her academic achievement earned her a place at a top university.', 'success reached in schoolwork or study'],
  ['academic performance', 'kết quả học tập', 'Regular sleep can improve a student\'s academic performance.', 'how well a student does in their studies'],
  ['academic subject', 'môn học', 'Maths is her strongest academic subject.', 'a subject studied at school or university'],
  ['higher education', 'giáo dục đại học', 'Higher education gives graduates better job prospects.', 'education at university level or above'],
  ['primary education', 'giáo dục tiểu học', 'Primary education usually starts at the age of six.', 'education for young children, usually the first stage of schooling'],
  ['secondary education', 'giáo dục trung học', 'Secondary education prepares students for university or work.', 'education for older children, after primary school'],
  ['compulsory education', 'giáo dục bắt buộc', 'Compulsory education in this country lasts until the age of sixteen.', 'education that is required by law'],
  ['further education', 'giáo dục sau phổ thông', 'She took a further education course to gain new skills.', 'education after secondary school, below university level'],
  ['undergraduate', 'sinh viên đại học', 'He is an undergraduate studying economics.', 'a student studying for their first university degree'],
  ['postgraduate', 'sau đại học', 'She is doing a postgraduate degree in psychology.', 'relating to study after completing a first university degree'],
  ['degree', 'bằng cấp', 'He earned a degree in engineering.', 'a qualification given by a university after a course of study'],
  ['qualification', 'trình độ/bằng cấp', 'A teaching qualification is required for this job.', 'an official record showing that someone has completed training or an exam'],
  ['scholarship', 'học bổng', 'She was awarded a scholarship to study abroad.', 'money given to a student to help pay for their education'],
  ['tuition fee', 'học phí', 'Tuition fees have increased significantly in recent years.', 'the money charged for teaching, especially at a university'],
  ['lecture', 'bài giảng', 'The professor gave a fascinating lecture on climate change.', 'a talk given to teach people about a subject, especially at university'],
  ['assignment', 'bài tập được giao', 'She finished her assignment before the deadline.', 'a piece of work given to a student to complete'],
  ['assessment', 'sự đánh giá', 'The course includes both written and oral assessment.', 'the process of judging a student\'s knowledge or performance'],
  ['examination', 'kỳ thi', 'Students must pass the final examination to graduate.', 'a formal test of knowledge or skill'],
  ['curriculum', 'chương trình học', 'The school introduced coding into the curriculum.', 'the subjects included in a course of study'],
  ['course', 'khóa học/môn học', 'He enrolled in a business course at the local college.', 'a series of lessons on a particular subject'],
  ['subject', 'môn học', 'History is her favourite subject.', 'an area of knowledge studied in school or university'],
  ['semester', 'học kỳ', 'The first semester ends in December.', 'one of the two main periods a school or university year is divided into'],
  ['campus', 'khuôn viên trường', 'The university campus has several modern buildings.', 'the land and buildings of a university or college'],
  ['faculty', 'khoa/giảng viên', 'She works in the Faculty of Engineering.', 'a department of a university, or the teaching staff there'],
  ['classmate', 'bạn cùng lớp', 'She studied with her classmates for the exam.', 'a person who is in the same class as you'],
  ['lecturer', 'giảng viên', 'The lecturer explained the theory using real examples.', 'a person who teaches at a university or college'],
  ['professor', 'giáo sư', 'Professor Smith has taught at the university for twenty years.', 'a senior university teacher, usually an expert in their field'],
  ['academic year', 'năm học', 'The academic year usually starts in September.', 'the period of time schools and universities are open, divided into terms'],
  ['learning environment', 'môi trường học tập', 'A positive learning environment helps students perform better.', 'the setting and conditions in which learning takes place'],
  ['educational background', 'nền tảng học vấn', 'Her educational background is in mathematics and computer science.', 'a person\'s history of schooling and qualifications'],
  ['teaching method', 'phương pháp giảng dạy', 'The school adopted a new teaching method based on group work.', 'a particular way of teaching a subject'],
  ['study skills', 'kỹ năng học tập', 'The workshop taught useful study skills like note-taking.', 'techniques that help a person learn effectively'],
  ['critical thinking', 'tư duy phản biện', 'The course helps students develop critical thinking.', 'the ability to analyse facts and form a reasoned judgement'],
  ['problem-solving skills', 'kỹ năng giải quyết vấn đề', 'Maths lessons help build problem-solving skills.', 'the ability to find solutions to difficult situations'],
  ['gain knowledge', 'tiếp thu kiến thức', 'Reading widely helps you gain knowledge about many topics.', 'to acquire information or understanding'],
  ['gain experience', 'tích lũy kinh nghiệm', 'Internships help students gain experience before graduating.', 'to acquire practical knowledge or skill through doing something'],
  ['attend a lecture', 'tham dự một buổi giảng', 'Students are expected to attend every lecture.', 'to go to and listen to a talk given to teach a subject'],
  ['sit an exam', 'dự thi', 'She sat her final exam last week.', 'to take a formal test'],
  ['pass an exam', 'vượt qua kỳ thi', 'She worked hard and passed her exam with a great score.', 'to succeed in a test'],
  ['fail an exam', 'trượt kỳ thi', 'He failed the exam because he didn\'t study enough.', 'to be unsuccessful in a test'],
  ['get a degree', 'lấy bằng', 'She got a degree in law after four years of study.', 'to complete a university course and receive a degree'],
  ['pursue a degree', 'theo đuổi một bằng cấp', 'He decided to pursue a degree in medicine.', 'to work towards completing a university qualification'],
  ['enrol in a course', 'đăng ký một khóa học', 'She enrolled in an online course to learn graphic design.', 'to officially register to join a course of study'],
  ['keep up with studies', 'theo kịp việc học', 'She works hard to keep up with her studies despite a busy schedule.', 'to stay on track with schoolwork and not fall behind'],
  ['fall behind with studies', 'bị tụt lại trong việc học', 'He fell behind with his studies after missing two weeks of school.', 'to fail to keep up with the required pace of schoolwork'],
  ['make progress', 'tiến bộ', 'He has made real progress since he started the course.', 'to improve or move forward gradually'],
  ['under academic pressure', 'chịu áp lực học tập', 'Many students feel under academic pressure before exams.', 'experiencing stress caused by the demands of studying'],
  ['broaden one\'s knowledge', 'mở rộng kiến thức', 'Travelling can really broaden your knowledge of the world.', 'to increase the amount of knowledge one has'],
  ['put knowledge into practice', 'áp dụng kiến thức vào thực tế', 'The internship let her put her knowledge into practice.', 'to use what one has learned in a real situation'],
  ['employment', 'việc làm', 'The government aims to increase employment across the country.', 'the state of having paid work'],
  ['unemployment', 'thất nghiệp', 'Unemployment rose sharply during the recession.', 'the state of not having a paid job'],
  ['job', 'công việc', 'She found a job as a marketing assistant.', 'a paid position of regular employment'],
  ['career', 'sự nghiệp', 'He built a successful career in finance.', 'a job or profession followed over a long period of a person\'s life'],
  ['profession', 'nghề nghiệp', 'Teaching is a demanding but rewarding profession.', 'a paid occupation that requires special training and qualifications'],
  ['occupation', 'nghề nghiệp', 'Please state your occupation on the form.', 'a person\'s job or profession'],
  ['career path', 'con đường sự nghiệp', 'An internship can help you decide on a career path.', 'the sequence of jobs that make up a person\'s working life'],
  ['career prospects', 'triển vọng nghề nghiệp', 'A university degree can improve your career prospects.', 'the likely chances of success or advancement in a career'],
  ['job satisfaction', 'sự hài lòng trong công việc', 'Job satisfaction is often more important than salary.', 'the feeling of pleasure and fulfilment one gets from their job'],
  ['job security', 'sự ổn định trong công việc', 'Many workers value job security over a high salary.', 'confidence that one will keep their job'],
  ['job opportunity', 'cơ hội việc làm', 'The new factory created many job opportunities in the area.', 'a chance to get a job'],
  ['job market', 'thị trường việc làm', 'The job market has become more competitive in recent years.', 'the availability of jobs, especially in relation to demand'],
  ['recruit staff', 'tuyển dụng nhân viên', 'The company is recruiting new staff for its sales team.', 'to find and hire new employees'],
  ['hire someone', 'thuê ai đó', 'The restaurant hired two new waiters last month.', 'to employ someone for a job'],
  ['apply for a job', 'nộp đơn xin việc', 'She applied for a job at the local hospital.', 'to formally request to be considered for a position'],
  ['job interview', 'phỏng vấn xin việc', 'He was nervous before his first job interview.', 'a meeting in which an employer asks a candidate questions to decide if they should be hired'],
  ['work experience', 'kinh nghiệm làm việc', 'Work experience is often as important as qualifications.', 'practical experience gained by doing a job'],
  ['internship', 'thực tập', 'She did an internship at a law firm during the summer.', 'a period of supervised practical work, often unpaid, to gain experience'],
  ['promotion', 'sự thăng chức', 'He received a promotion after five years with the company.', 'advancement to a higher position or rank at work'],
  ['get promoted', 'được thăng chức', 'She got promoted to team leader last month.', 'to be given a higher position at work'],
  ['salary', 'lương', 'Her salary increased after she completed the training.', 'a fixed regular payment made by an employer, usually monthly'],
  ['income', 'thu nhập', 'Her income covers all of her living expenses.', 'money received, especially from work'],
  ['minimum wage', 'lương tối thiểu', 'The government raised the minimum wage this year.', 'the lowest wage employers are legally allowed to pay'],
  ['employee benefits', 'phúc lợi nhân viên', 'The company offers generous employee benefits, including healthcare.', 'additional advantages given to workers besides salary, such as insurance'],
  ['work environment', 'môi trường làm việc', 'A positive work environment improves productivity.', 'the setting and conditions in which people work'],
  ['workplace', 'nơi làm việc', 'The company introduced new safety rules in the workplace.', 'the place where someone works'],
  ['employer', 'người sử dụng lao động', 'Her employer offered her a permanent contract.', 'a person or organisation that employs people'],
  ['self-employed', 'tự kinh doanh/tự làm chủ', 'He has been self-employed as a graphic designer for years.', 'working for oneself rather than an employer'],
  ['full-time job', 'công việc toàn thời gian', 'She switched from part-time to a full-time job.', 'a job involving the standard number of working hours per week'],
  ['part-time job', 'công việc bán thời gian', 'Many students take a part-time job to earn extra money.', 'a job involving fewer hours than a full-time job'],
  ['work overtime', 'làm thêm giờ', 'He often has to work overtime to meet deadlines.', 'to work beyond one\'s normal working hours'],
  ['workload', 'khối lượng công việc', 'Her workload has increased since the new project started.', 'the amount of work a person or organisation has to do'],
  ['meet a deadline', 'hoàn thành đúng hạn', 'The team worked late to meet the deadline.', 'to complete a task by the required time'],
  ['resign from a job', 'từ chức', 'She resigned from her job to start her own business.', 'to formally leave a job'],
  ['quit a job', 'nghỉ việc', 'He quit his job after finding a better opportunity.', 'to leave a job, often informally'],
  ['lay off employees', 'sa thải nhân viên', 'The company had to lay off staff due to falling profits.', 'to end someone\'s employment, usually due to lack of work'],
  ['lose one\'s job', 'mất việc', 'Many workers lost their jobs during the recession.', 'to become unemployed, especially unexpectedly'],
  ['redundancy', 'dư thừa lao động/sa thải', 'Hundreds of workers faced redundancy when the factory closed.', 'the state of losing a job because it is no longer needed'],
];

// ── Unit 4: Food and Drink ────────────────────────────────────────────────
const unit4 = [
  ['food', 'thức ăn', 'Fresh food is important for a healthy diet.', 'any nutritious substance that people eat to maintain life and growth'],
  ['drink', 'đồ uống', 'Cold drinks are popular in the summer.', 'any liquid that can be swallowed'],
  ['cuisine', 'ẩm thực', 'Italian cuisine is famous worldwide for its pasta and pizza.', 'a style of cooking, especially as characteristic of a particular country'],
  ['local cuisine', 'ẩm thực địa phương', 'Trying local cuisine is one of the joys of travelling.', 'the traditional food of a particular region or country'],
  ['traditional dish', 'món ăn truyền thống', 'Pho is a traditional Vietnamese dish.', 'a food that is typically prepared in a particular culture'],
  ['staple food', 'lương thực chính', 'Rice is the staple food in many Asian countries.', 'a food that forms the main part of a person\'s diet'],
  ['ingredient', 'nguyên liệu', 'Fresh ingredients make a big difference to the taste.', 'any of the foods or substances used to make a particular dish'],
  ['recipe', 'công thức nấu ăn', 'She followed her grandmother\'s recipe for the cake.', 'a set of instructions for preparing a dish'],
  ['flavour', 'hương vị', 'The soup has a rich, spicy flavour.', 'the distinctive taste of a food or drink'],
  ['taste', 'vị/hương vị', 'The dish has a slightly sweet taste.', 'the sensation produced by food in the mouth'],
  ['aroma', 'mùi thơm', 'The aroma of fresh bread filled the kitchen.', 'a pleasant, distinctive smell'],
  ['texture', 'kết cấu (của món ăn)', 'The cake has a light, fluffy texture.', 'the way a food feels in the mouth or looks'],
  ['nutritious', 'bổ dưỡng', 'A nutritious breakfast helps you concentrate at school.', 'containing substances the body needs to stay healthy'],
  ['nutritional value', 'giá trị dinh dưỡng', 'Fresh vegetables have a high nutritional value.', 'the amount of nutrients a food contains'],
  ['balanced diet', 'chế độ ăn cân bằng', 'A balanced diet should include protein, carbohydrates and fats.', 'a diet containing the right proportions of different food types'],
  ['healthy diet', 'chế độ ăn lành mạnh', 'Eating a healthy diet can prevent many illnesses.', 'a diet that is good for one\'s physical health'],
  ['unhealthy diet', 'chế độ ăn không lành mạnh', 'An unhealthy diet can lead to weight gain and disease.', 'a diet that is harmful to one\'s physical health'],
  ['fast food', 'thức ăn nhanh', 'Fast food is convenient but often high in fat and salt.', 'food that can be prepared and served very quickly'],
  ['junk food', 'đồ ăn vặt không lành mạnh', 'Eating too much junk food can cause health problems.', 'food that is quick to prepare but not very nutritious'],
  ['processed food', 'thực phẩm chế biến sẵn', 'Doctors advise eating less processed food.', 'food that has been treated or changed before being eaten'],
  ['organic food', 'thực phẩm hữu cơ', 'Organic food is grown without artificial chemicals.', 'food produced without the use of artificial fertilisers or pesticides'],
  ['fresh produce', 'thực phẩm tươi', 'The market sells fresh produce straight from local farms.', 'fruits and vegetables that are recently harvested'],
  ['genetically modified food', 'thực phẩm biến đổi gen', 'Some countries have strict laws about genetically modified food.', 'food that has had its genetic material altered artificially'],
  ['street food', 'đồ ăn đường phố', 'The night market is famous for its cheap and delicious street food.', 'food sold and eaten in public places, such as on the street'],
  ['home-cooked meal', 'bữa ăn tự nấu', 'Nothing beats a home-cooked meal after a long trip.', 'a meal prepared at home rather than bought'],
  ['eat out', 'ăn ngoài', 'We eat out at a restaurant once a week.', 'to have a meal at a restaurant rather than at home'],
  ['dine out', 'ăn ngoài (trang trọng)', 'They like to dine out to celebrate special occasions.', 'to eat a meal at a restaurant'],
  ['eating habits', 'thói quen ăn uống', 'Her eating habits changed after she started working night shifts.', 'the typical patterns of what and how a person eats'],
  ['dietary requirements', 'yêu cầu về chế độ ăn', 'The restaurant can accommodate special dietary requirements.', 'the specific food needs of a person, e.g. due to allergies'],
  ['food allergy', 'dị ứng thực phẩm', 'He has a food allergy to peanuts.', 'a reaction of the body\'s immune system to a particular food'],
  ['vegetarian', 'người ăn chay', 'She has been a vegetarian for over ten years.', 'a person who does not eat meat or fish'],
  ['vegan', 'người ăn thuần chay', 'Vegan diets avoid all animal products, including dairy and eggs.', 'a person who eats no animal products at all'],
  ['food waste', 'lãng phí thực phẩm', 'Restaurants are being encouraged to reduce food waste.', 'food that is thrown away instead of eaten'],
  ['food shortage', 'thiếu hụt lương thực', 'The drought led to a serious food shortage in the region.', 'a situation in which there is not enough food available'],
  ['food security', 'an ninh lương thực', 'Improving farming methods can help ensure food security.', 'reliable access to enough affordable, nutritious food'],
  ['food industry', 'ngành công nghiệp thực phẩm', 'The food industry is under pressure to reduce sugar in products.', 'the businesses involved in producing and selling food'],
  ['food production', 'sản xuất thực phẩm', 'Modern technology has increased food production worldwide.', 'the process of growing or making food'],
  ['agriculture', 'nông nghiệp', 'Agriculture remains a major part of the country\'s economy.', 'the practice of farming, including growing crops and raising animals'],
  ['farming', 'canh tác/chăn nuôi', 'Organic farming avoids the use of artificial chemicals.', 'the activity of growing crops or keeping animals'],
  ['crop', 'vụ mùa/nông sản', 'A poor harvest can seriously damage a farmer\'s income from crops.', 'a plant grown in large amounts for food'],
  ['harvest', 'thu hoạch', 'Farmers harvest the wheat in late summer.', 'to gather a crop when it is ready'],
  ['livestock', 'gia súc', 'The farm raises livestock, including cows and sheep.', 'animals kept on a farm for meat, milk or other products'],
  ['food delivery', 'giao đồ ăn', 'Food delivery apps have become very popular since the pandemic.', 'the service of bringing prepared meals to a customer\'s location'],
  ['takeaway food', 'đồ ăn mang đi', 'We ordered takeaway food because we were too tired to cook.', 'food prepared at a restaurant to be eaten elsewhere'],
  ['portion size', 'khẩu phần ăn', 'Restaurant portion sizes have increased over the years.', 'the amount of food served to one person'],
  ['overeat', 'ăn quá nhiều', 'It\'s easy to overeat when food tastes really good.', 'to eat more food than one needs'],
  ['skip a meal', 'bỏ bữa', 'Skipping breakfast can affect concentration during the day.', 'to not eat a particular meal'],
  ['cut down on sugar', 'giảm lượng đường', 'Doctors recommend cutting down on sugar to prevent illness.', 'to reduce the amount of sugar eaten or drunk'],
  ['maintain a balanced diet', 'duy trì chế độ ăn cân bằng', 'Athletes need to maintain a balanced diet for good performance.', 'to keep eating the right mix of different food types'],
  ['try local delicacies', 'thử các món đặc sản địa phương', 'One of the best parts of travelling is trying local delicacies.', 'to taste special or unusual foods typical of a place'],
  ['have a sweet tooth', 'thích đồ ngọt', 'She has a sweet tooth and loves desserts.', 'to have a strong liking for sweet food'],
  ['be full of nutrients', 'giàu chất dinh dưỡng', 'Leafy greens are full of nutrients.', 'containing a lot of substances that support health'],
  ['be high in fat/sugar/salt', 'chứa nhiều chất béo/đường/muối', 'Many snacks are high in fat and sugar.', 'containing large amounts of fat, sugar or salt'],
  ['be low in calories', 'ít calo', 'Vegetables are generally low in calories.', 'containing a small number of calories'],
  ['play a role in one\'s health', 'đóng vai trò trong sức khỏe', 'Diet plays a huge role in one\'s overall health.', 'to be an important factor influencing something'],
  ['contribute to obesity', 'góp phần gây béo phì', 'A poor diet can contribute to obesity.', 'to be one of the causes of a problem, in this case weight gain'],
];

// ── Unit 5: Consumerism ───────────────────────────────────────────────────
const unit5 = [
  ['consumerism', 'chủ nghĩa tiêu dùng', 'Consumerism has led to a huge increase in household waste.', 'the preoccupation of society with buying and owning goods'],
  ['consumer', 'người tiêu dùng', 'Consumers now have access to products from all over the world.', 'a person who buys goods or services'],
  ['consumer society', 'xã hội tiêu dùng', 'We live in a consumer society that values owning the latest products.', 'a society in which buying and consuming goods is a central activity'],
  ['consumer behaviour', 'hành vi tiêu dùng', 'Advertisers study consumer behaviour to sell more products.', 'the way people decide what, when and how to buy things'],
  ['consumer goods', 'hàng tiêu dùng', 'The store sells a wide range of consumer goods.', 'products bought by individuals for personal use'],
  ['consumer spending', 'chi tiêu tiêu dùng', 'Consumer spending increased during the holiday season.', 'the amount of money spent by people on goods and services'],
  ['consumer demand', 'nhu cầu tiêu dùng', 'Consumer demand for eco-friendly products is growing.', 'the desire of consumers to buy particular goods or services'],
  ['consumer rights', 'quyền lợi người tiêu dùng', 'Consumer rights protect buyers from unfair business practices.', 'the legal rights of people who buy goods and services'],
  ['consumer protection', 'bảo vệ người tiêu dùng', 'The new law strengthens consumer protection online.', 'measures taken to protect the interests of buyers'],
  ['purchasing power', 'sức mua', 'Rising prices have reduced people\'s purchasing power.', 'the amount of goods or services that money can buy'],
  ['disposable income', 'thu nhập khả dụng', 'Higher disposable income allows people to spend more on leisure.', 'the money a person has left to spend after paying taxes and bills'],
  ['make a purchase', 'thực hiện việc mua sắm', 'More customers now make a purchase using their phone.', 'to buy something'],
  ['purchase decision', 'quyết định mua hàng', 'Reviews online often influence a customer\'s purchase decision.', 'the choice a consumer makes about whether and what to buy'],
  ['impulse buying', 'mua sắm bốc đồng', 'Impulse buying often leads to regret later.', 'the act of buying something without planning to, on a sudden urge'],
  ['impulse purchase', 'món đồ mua bốc đồng', 'The chocolate bar at the checkout was an impulse purchase.', 'an item bought suddenly and without planning'],
  ['compulsive buying', 'mua sắm mất kiểm soát', 'Compulsive buying can cause serious financial problems.', 'a pattern of buying things excessively and without control'],
  ['retail therapy', 'liệu pháp mua sắm', 'She went shopping for some retail therapy after a stressful week.', 'shopping done to improve one\'s mood'],
  ['window shopping', 'đi ngắm hàng (không mua)', 'We spent the afternoon window shopping in the city centre.', 'looking at goods in shop windows without intending to buy'],
  ['bargain hunting', 'săn hàng giá hời', 'She enjoys bargain hunting at the weekend markets.', 'the activity of looking for goods sold at a low price'],
  ['brand loyalty', 'lòng trung thành với thương hiệu', 'The company has built strong brand loyalty over the years.', 'a consumer\'s continued preference for a particular brand'],
  ['brand awareness', 'nhận diện thương hiệu', 'The advertising campaign increased brand awareness significantly.', 'the extent to which consumers recognise a brand'],
  ['advertising', 'quảng cáo', 'Advertising plays a huge role in shaping what people buy.', 'the business of promoting products or services to the public'],
  ['advertisement', 'quảng cáo (cái)', 'The advertisement targets young, active consumers.', 'a public notice promoting a product, service or event'],
  ['marketing campaign', 'chiến dịch tiếp thị', 'The company launched a marketing campaign for its new product.', 'a planned set of activities to promote a product'],
  ['marketing strategy', 'chiến lược tiếp thị', 'Their marketing strategy focuses heavily on social media.', 'a plan for promoting and selling a product or service'],
  ['product placement', 'quảng cáo lồng ghép sản phẩm', 'The film used product placement to promote the car brand.', 'the practice of featuring a brand\'s product within media content, e.g. a film'],
  ['celebrity endorsement', 'sự chứng thực từ người nổi tiếng', 'The brand relies on celebrity endorsement to attract young buyers.', 'the promotion of a product by a famous person'],
  ['peer influence', 'ảnh hưởng từ bạn bè', 'Peer influence often shapes what teenagers choose to buy.', 'the effect that friends or people of a similar age have on one\'s decisions'],
  ['social pressure to buy', 'áp lực xã hội để mua sắm', 'Social media can create social pressure to buy the latest trends.', 'the influence from others that makes someone feel they should purchase something'],
  ['planned obsolescence', 'lỗi thời có chủ đích', 'Critics accuse manufacturers of planned obsolescence to boost sales.', 'the practice of designing products to become outdated or stop working quickly'],
  ['throwaway culture', 'văn hóa dùng một lần rồi bỏ', 'Throwaway culture has led to a rise in electronic waste.', 'a society\'s habit of quickly discarding used items instead of repairing them'],
  ['mass production', 'sản xuất hàng loạt', 'Mass production made clothes much cheaper to buy.', 'the manufacture of large quantities of a standard product'],
  ['fast fashion', 'thời trang nhanh', 'Fast fashion has been criticised for its environmental impact.', 'cheap, trendy clothing produced quickly to meet current fashion trends'],
  ['materialism', 'chủ nghĩa vật chất', 'Some people believe modern society has become too focused on materialism.', 'the belief that owning material possessions is the most important thing in life'],
  ['materialistic', 'trọng vật chất', 'He\'s quite materialistic and always wants the newest gadgets.', 'placing too much value on money and material possessions'],
  ['status symbol', 'biểu tượng địa vị', 'A luxury car is seen as a status symbol by many.', 'a possession that shows a person\'s high social or financial position'],
  ['keep up with the latest trends', 'theo kịp xu hướng mới nhất', 'Many young people try to keep up with the latest trends.', 'to stay updated with current fashions or popular things'],
  ['keeping up with the Joneses', 'đua đòi theo người khác', 'Some families overspend just to keep up with the Joneses.', 'trying to match the possessions or lifestyle of one\'s neighbours or peers'],
  ['luxury goods', 'hàng xa xỉ', 'Luxury goods, such as designer handbags, are very expensive.', 'expensive, high-quality goods that are not necessities'],
  ['luxury brand', 'thương hiệu xa xỉ', 'The luxury brand is known for its high prices and exclusivity.', 'a brand associated with high quality and high price'],
  ['discount', 'giảm giá', 'The store offered a 20% discount on all items.', 'a reduction in the usual price of something'],
  ['sale', 'đợt giảm giá', 'She bought a new coat in the winter sale.', 'a period when goods are sold at reduced prices'],
  ['bargain', 'món hời', 'She found a real bargain at the second-hand shop.', 'something bought for a lower price than it is worth'],
  ['affordable', 'có thể mua được/giá cả phải chăng', 'The company offers affordable products for budget-conscious shoppers.', 'not too expensive; able to be bought without financial difficulty'],
  ['overpriced', 'giá quá cao', 'Many tourists complain that souvenirs near attractions are overpriced.', 'priced higher than something is really worth'],
  ['online shopping', 'mua sắm trực tuyến', 'Online shopping has become extremely popular in recent years.', 'buying goods over the internet'],
  ['e-commerce', 'thương mại điện tử', 'E-commerce has changed the way people shop for almost everything.', 'the buying and selling of goods over the internet'],
  ['shopping addiction', 'nghiện mua sắm', 'Shopping addiction can lead to serious debt problems.', 'a compulsive and uncontrollable urge to shop'],
  ['spend beyond one\'s means', 'chi tiêu vượt quá khả năng', 'It\'s easy to spend beyond your means when using credit cards.', 'to spend more money than one can actually afford'],
  ['live within one\'s means', 'sống trong khả năng tài chính', 'Learning to live within your means is an important financial skill.', 'to spend no more money than one earns'],
  ['get into debt', 'rơi vào nợ nần', 'Overspending on credit cards can quickly lead to debt.', 'to owe money that one struggles to repay'],
  ['credit card debt', 'nợ thẻ tín dụng', 'Credit card debt is a growing problem for many young adults.', 'money owed as a result of spending on a credit card'],
  ['consumer debt', 'nợ tiêu dùng', 'Consumer debt has risen sharply in recent years.', 'money owed by individuals from buying goods or services'],
  ['environmentally conscious consumer', 'người tiêu dùng có ý thức môi trường', 'Environmentally conscious consumers prefer eco-friendly packaging.', 'a buyer who considers the environmental impact of their purchases'],
  ['ethical consumerism', 'tiêu dùng có đạo đức', 'Ethical consumerism encourages people to buy from responsible companies.', 'the practice of buying products made in a fair and environmentally responsible way'],
  ['sustainable consumption', 'tiêu dùng bền vững', 'Sustainable consumption means buying only what one really needs.', 'using goods and resources in a way that does not harm the environment long-term'],
  ['second-hand goods', 'hàng đã qua sử dụng', 'Buying second-hand goods is a cheap and eco-friendly option.', 'goods that have previously been owned by someone else'],
  ['minimalism', 'chủ nghĩa tối giản', 'Minimalism encourages people to own fewer, more meaningful possessions.', 'a lifestyle that involves owning very few possessions'],
  ['drive economic growth', 'thúc đẩy tăng trưởng kinh tế', 'Consumer spending helps drive economic growth.', 'to cause an economy to expand'],
  ['have a negative impact on the environment', 'gây tác động tiêu cực đến môi trường', 'Overconsumption has a negative impact on the environment.', 'to cause harm to the natural world'],
];

// ── Unit 6: Leisure Time ──────────────────────────────────────────────────
const unit6 = [
  ['leisure time', 'thời gian rảnh', 'People today have more leisure time than previous generations.', 'time when a person is not working, free to relax or enjoy activities'],
  ['free time', 'thời gian rảnh', 'She plays the guitar in her free time.', 'time when a person is not working or studying'],
  ['spare time', 'thời gian rảnh rỗi', 'He reads novels in his spare time.', 'time when a person is not working or studying'],
  ['leisure activity', 'hoạt động giải trí', 'Gardening is her favourite leisure activity.', 'an activity done for enjoyment in one\'s free time'],
  ['recreational activity', 'hoạt động vui chơi giải trí', 'The park offers many recreational activities for families.', 'an activity done for enjoyment and relaxation'],
  ['hobby', 'sở thích', 'Painting has been her hobby since childhood.', 'an activity done regularly for pleasure in one\'s free time'],
  ['pastime', 'thú tiêu khiển', 'Reading is a relaxing pastime for many people.', 'an activity that someone does regularly for enjoyment'],
  ['take up a hobby', 'bắt đầu một sở thích', 'She took up painting as a hobby last year.', 'to start doing an activity regularly for pleasure'],
  ['pursue a hobby', 'theo đuổi sở thích', 'He pursues his hobby of photography every weekend.', 'to continue doing an activity for pleasure over time'],
  ['outdoor activity', 'hoạt động ngoài trời', 'Hiking is a popular outdoor activity in the region.', 'an activity done outside, in the open air'],
  ['indoor activity', 'hoạt động trong nhà', 'On rainy days, they enjoy indoor activities like board games.', 'an activity done inside a building'],
  ['relaxation', 'sự thư giãn', 'Yoga is a great way to achieve relaxation.', 'the state of being free from tension and worry'],
  ['unwind', 'thư giãn', 'She likes to unwind by listening to music after work.', 'to relax after a period of work or stress'],
  ['de-stress', 'giải tỏa căng thẳng', 'Going for a walk is a simple way to de-stress.', 'to relax and reduce feelings of stress'],
  ['entertainment', 'sự giải trí', 'The city offers plenty of entertainment options, from cinemas to concerts.', 'activities designed to give people pleasure or amusement'],
  ['entertainment industry', 'ngành công nghiệp giải trí', 'The entertainment industry has grown rapidly with streaming services.', 'the businesses involved in providing films, music, TV and similar entertainment'],
  ['socialise', 'giao lưu/kết bạn', 'Joining a club is a great way to socialise with new people.', 'to spend time with others in a friendly, informal way'],
  ['hang out with friends', 'đi chơi với bạn bè', 'They like to hang out with friends at the café after school.', 'to spend time relaxing with friends'],
  ['spend time with family', 'dành thời gian cho gia đình', 'Weekends are usually spent time with family.', 'to pass time together with one\'s relatives'],
  ['go on holiday', 'đi nghỉ mát', 'The family goes on holiday to the coast every summer.', 'to travel somewhere for leisure or relaxation'],
  ['weekend getaway', 'chuyến đi ngắn ngày cuối tuần', 'They booked a weekend getaway to the mountains.', 'a short trip taken over a weekend for relaxation'],
  ['day trip', 'chuyến đi trong ngày', 'We took a day trip to a nearby island.', 'a trip made and completed within one day'],
  ['play sports', 'chơi thể thao', 'He plays sports every weekend to stay fit.', 'to take part in physical games and activities'],
  ['team sport', 'môn thể thao đồng đội', 'Football is one of the most popular team sports.', 'a sport played by two or more groups of people together'],
  ['individual sport', 'môn thể thao cá nhân', 'Tennis is an individual sport that requires great focus.', 'a sport played alone rather than as part of a team'],
  ['exercise', 'tập thể dục', 'Regular exercise helps reduce stress.', 'physical activity done to stay fit and healthy'],
  ['go to the gym', 'đến phòng gym', 'She goes to the gym three times a week.', 'to visit a place with equipment for physical exercise'],
  ['play video games', 'chơi trò chơi điện tử', 'Many teenagers play video games in their spare time.', 'to play electronic games, usually on a computer or console'],
  ['watch television', 'xem tivi', 'The whole family gathers to watch television in the evening.', 'to look at programmes broadcast on TV'],
  ['binge-watch a series', 'xem liên tục một series', 'They binge-watched the entire series over the weekend.', 'to watch many episodes of a TV show in one sitting'],
  ['go to the cinema', 'đi xem phim', 'We went to the cinema to watch the new film.', 'to visit a place where films are shown'],
  ['attend a concert', 'tham dự một buổi hòa nhạc', 'She attended a concert last Friday night.', 'to go to a live music performance'],
  ['go to a museum', 'đi bảo tàng', 'We went to the art gallery on a rainy afternoon.', 'to visit a place displaying art or historical objects'],
  ['read a book', 'đọc sách', 'He reads a book before bed every night.', 'to look at and understand the words in a written text'],
  ['listen to music', 'nghe nhạc', 'She listens to music while doing housework.', 'to pay attention to sounds of songs or musical pieces'],
  ['play a musical instrument', 'chơi một nhạc cụ', 'He has played the piano since he was six.', 'to perform music using an instrument'],
  ['gardening', 'làm vườn', 'Gardening helps her relax after a long week.', 'the activity of growing and taking care of plants'],
  ['cooking as a hobby', 'nấu ăn như một sở thích', 'Cooking as a hobby lets him experiment with new recipes.', 'preparing food for enjoyment rather than necessity'],
  ['crafts', 'thủ công', 'She enjoys crafts like knitting and pottery.', 'activities involving skill in making things by hand'],
  ['board game', 'trò chơi board game', 'The family played a board game together on Sunday evening.', 'a game played by moving pieces on a flat board'],
  ['video game addiction', 'nghiện game', 'Video game addiction can affect a young person\'s studies.', 'an excessive and uncontrollable urge to play video games'],
  ['screen time', 'thời gian sử dụng màn hình', 'Parents try to limit their children\'s screen time.', 'the amount of time spent using devices with screens'],
  ['digital detox', 'cai nghiện thiết bị số', 'She did a digital detox during her holiday, avoiding her phone entirely.', 'a period of time when a person avoids using electronic devices'],
  ['get some fresh air', 'hít thở không khí trong lành', 'A walk in the park is a good way to get some fresh air.', 'to go outside, especially for health or relaxation'],
  ['recharge one\'s batteries', 'nạp lại năng lượng', 'A weekend away helps her recharge her batteries.', 'to rest and restore one\'s energy'],
  ['take a break', 'nghỉ ngơi một chút', 'It\'s important to take a break from work now and then.', 'to stop an activity for a short period of rest'],
  ['have a well-deserved rest', 'có một kỳ nghỉ xứng đáng', 'After the exams, she had a well-deserved rest.', 'to rest after working hard, having earned it'],
  ['keep oneself entertained', 'tự giải trí', 'Children need activities to keep themselves entertained on long journeys.', 'to occupy oneself with enjoyable activities'],
  ['broaden one\'s horizons', 'mở rộng tầm hiểu biết', 'Trying new hobbies can broaden your horizons.', 'to increase the range of one\'s knowledge and experience'],
  ['relieve boredom', 'giải tỏa sự nhàm chán', 'Puzzles are a good way to relieve boredom on a long flight.', 'to reduce the feeling of having nothing interesting to do'],
  ['have a positive effect on mental health', 'có tác động tích cực đến sức khỏe tinh thần', 'Regular leisure activities can have a positive effect on mental health.', 'to improve a person\'s emotional and psychological well-being'],
];

// ── Unit 7: Fame and the Media ────────────────────────────────────────────
const unit7 = [
  ['fame', 'sự nổi tiếng', 'The singer achieved fame at a very young age.', 'the state of being known and talked about by many people'],
  ['famous', 'nổi tiếng', 'She became famous after starring in a hit film.', 'known about by many people'],
  ['celebrity', 'người nổi tiếng', 'The event was attended by several celebrities.', 'a famous person, especially in entertainment or sport'],
  ['celebrity culture', 'văn hóa người nổi tiếng', 'Celebrity culture has a strong influence on young people\'s values.', 'the widespread public interest in the lives of famous people'],
  ['celebrity status', 'địa vị người nổi tiếng', 'Winning the award gave her celebrity status overnight.', 'the position or fame of being a well-known public figure'],
  ['public figure', 'nhân vật của công chúng', 'As a public figure, she is often followed by photographers.', 'a person who is well known and has some public role'],
  ['public image', 'hình ảnh trước công chúng', 'The actor works hard to maintain a positive public image.', 'the way a person is generally perceived by the public'],
  ['reputation', 'danh tiếng', 'The scandal damaged his reputation badly.', 'the general opinion held about someone or something'],
  ['rise to fame', 'nổi tiếng lên', 'She rose to fame after appearing on a talent show.', 'to become well known, often suddenly'],
  ['become famous overnight', 'nổi tiếng chỉ sau một đêm', 'The video went viral and he became famous overnight.', 'to become well known very quickly'],
  ['gain popularity', 'trở nên nổi tiếng', 'The show gained popularity among younger audiences.', 'to become liked or well known by many people'],
  ['lose popularity', 'mất đi sự nổi tiếng', 'The band lost popularity after their controversial comments.', 'to become less liked or admired'],
  ['media', 'truyền thông', 'The media plays a powerful role in shaping public opinion.', 'the main means of mass communication, e.g. television, newspapers'],
  ['mass media', 'truyền thông đại chúng', 'Mass media reaches millions of people every day.', 'means of communication that reach large numbers of people'],
  ['social media', 'mạng xã hội', 'Many celebrities use social media to connect with fans.', 'websites and apps that let people create and share content'],
  ['news media', 'truyền thông tin tức', 'The news media covered the event extensively.', 'organisations that report news to the public'],
  ['tabloid', 'báo lá cải', 'The tabloid published an exaggerated story about the celebrity.', 'a newspaper with small pages, often focused on sensational stories'],
  ['tabloid press', 'báo chí lá cải', 'The tabloid press often invades celebrities\' privacy.', 'newspapers known for sensational, often gossip-based, stories'],
  ['paparazzi', 'phóng viên ảnh săn tin', 'The paparazzi followed the actress everywhere she went.', 'photographers who follow celebrities to take pictures for newspapers'],
  ['gossip', 'tin đồn/lời bàn tán', 'Magazines are full of celebrity gossip.', 'casual talk about other people\'s private lives, often unconfirmed'],
  ['gossip column', 'chuyên mục tin đồn', 'The gossip column reported on the couple\'s break-up.', 'a section of a newspaper or magazine focused on celebrity news'],
  ['invade someone\'s privacy', 'xâm phạm quyền riêng tư của ai đó', 'Reporters often invade celebrities\' privacy to get a good story.', 'to intrude on someone\'s personal life without permission'],
  ['right to privacy', 'quyền riêng tư', 'Celebrities often complain about their right to privacy being ignored.', 'the right of a person to keep their personal life free from public attention'],
  ['media coverage', 'sự đưa tin của truyền thông', 'The trial received extensive media coverage.', 'the amount and type of reporting given to an event by the media'],
  ['media attention', 'sự chú ý của truyền thông', 'The scandal attracted a lot of media attention.', 'the interest and focus given to something by news outlets'],
  ['attract media attention', 'thu hút sự chú ý của truyền thông', 'The unusual event attracted media attention worldwide.', 'to cause journalists and news outlets to focus on something'],
  ['under the spotlight', 'dưới sự chú ý của công chúng', 'Being under the spotlight can be stressful for young stars.', 'receiving a great deal of public attention'],
  ['influencer', 'người có sức ảnh hưởng', 'The influencer promotes beauty products to her followers.', 'a person who has the power to affect others\' opinions, often via social media'],
  ['follower', 'người theo dõi', 'She has millions of followers on social media.', 'a person who follows someone\'s account or updates online'],
  ['go viral', 'lan truyền nhanh chóng', 'The video went viral within hours of being posted.', 'to become extremely popular very quickly online'],
  ['viral video', 'video lan truyền', 'The viral video was viewed millions of times in one day.', 'a video that spreads rapidly and widely online'],
  ['trending topic', 'chủ đề đang thịnh hành', 'The news became a trending topic on social media.', 'a subject that is currently very popular in online discussions'],
  ['fan base', 'lượng người hâm mộ', 'The band has built a loyal fan base over the years.', 'the group of people who admire and support a public figure'],
  ['fan', 'người hâm mộ', 'She has been a fan of the singer since she was a teenager.', 'a person who admires and supports a public figure or group'],
  ['idol', 'thần tượng', 'The young singer became an idol for teenagers around the world.', 'a person who is greatly admired or idealised'],
  ['role model', 'hình mẫu/tấm gương', 'Athletes often become role models for young people.', 'a person whose behaviour is copied by others as a positive example'],
  ['influence public opinion', 'ảnh hưởng đến dư luận', 'The media can strongly influence public opinion.', 'to affect what a large number of people think about an issue'],
  ['shape public perception', 'định hình nhận thức công chúng', 'News coverage can shape public perception of an event.', 'to influence how the public understands or views something'],
  ['media bias', 'sự thiên vị của truyền thông', 'Some viewers accuse the channel of media bias.', 'unfair or one-sided reporting by news organisations'],
  ['sensationalism', 'chủ nghĩa giật gân', 'Critics accuse the tabloids of sensationalism to sell more copies.', 'the use of exaggerated or shocking stories to attract attention'],
  ['exaggerate a story', 'phóng đại câu chuyện', 'The newspaper was accused of exaggerating the story for effect.', 'to make a report seem more extreme or dramatic than it really is'],
  ['spread misinformation', 'lan truyền thông tin sai lệch', 'Social media can spread misinformation very quickly.', 'to share false or inaccurate information'],
  ['fake news', 'tin giả', 'Fake news can spread faster than accurate reporting.', 'false information presented as if it were true news'],
  ['reliable source', 'nguồn tin đáng tin cậy', 'Always check whether the news comes from a reliable source.', 'a source of information that can be trusted to be accurate'],
  ['freedom of the press', 'tự do báo chí', 'Freedom of the press is essential to a healthy democracy.', 'the right of journalists to report news without government control'],
  ['censorship', 'kiểm duyệt', 'Some countries impose strict censorship on the media.', 'the control or suppression of information by authorities'],
  ['be in the public eye', 'ở trong tầm mắt công chúng', 'Politicians are constantly in the public eye.', 'to be closely observed and discussed by the public'],
  ['live in the limelight', 'sống trong ánh hào quang', 'Growing up in the limelight isn\'t always easy for child stars.', 'to live with a lot of public attention'],
  ['deal with public scrutiny', 'đối mặt với sự giám sát của công chúng', 'Celebrities have to learn to deal with public scrutiny.', 'to cope with being closely watched and judged by the public'],
  ['maintain a positive image', 'duy trì hình ảnh tích cực', 'Companies work hard to maintain a positive public image.', 'to keep being seen favourably by the public'],
  ['have a huge impact on society', 'có tác động lớn đến xã hội', 'The media has a huge impact on society\'s values.', 'to strongly influence how a society behaves or thinks'],
  ['celebrity endorsement', 'sự chứng thực từ người nổi tiếng', 'Brands often pay for celebrity endorsement to boost sales.', 'the promotion of a product by a famous person'],
];

// ── Unit 8: Natural World ─────────────────────────────────────────────────
const unit8 = [
  ['natural world', 'thế giới tự nhiên', 'The documentary explores the beauty of the natural world.', 'the physical environment, including plants, animals and landscapes'],
  ['natural environment', 'môi trường tự nhiên', 'Pollution is damaging the natural environment.', 'the surroundings in which plants, animals and people exist, unaffected by humans'],
  ['nature', 'thiên nhiên', 'She loves spending time in nature.', 'the physical world, including plants, animals and landscapes'],
  ['ecosystem', 'hệ sinh thái', 'The coral reef is a fragile ecosystem.', 'a community of living things and their environment functioning together'],
  ['habitat', 'môi trường sống', 'Deforestation destroys the habitat of many animals.', 'the natural home of a plant or animal'],
  ['wildlife', 'động vật hoang dã', 'The national park is home to a wide range of wildlife.', 'wild animals and plants living in their natural environment'],
  ['wildlife conservation', 'bảo tồn động vật hoang dã', 'The organisation focuses on wildlife conservation in Africa.', 'the protection of wild animals and their habitats'],
  ['endangered species', 'các loài có nguy cơ tuyệt chủng', 'The tiger is an endangered species.', 'a type of plant or animal that is at risk of dying out completely'],
  ['rare species', 'loài quý hiếm', 'The forest is home to several rare species of birds.', 'a type of plant or animal that is uncommon'],
  ['animal species', 'loài động vật', 'Thousands of animal species live in the rainforest.', 'a particular type of animal'],
  ['plant species', 'loài thực vật', 'Scientists discovered a new plant species in the jungle.', 'a particular type of plant'],
  ['biodiversity', 'đa dạng sinh học', 'The rainforest has some of the highest biodiversity on Earth.', 'the variety of plant and animal life in a particular area'],
  ['natural resources', 'tài nguyên thiên nhiên', 'The country is rich in natural resources such as oil and minerals.', 'materials or substances found in nature that are useful to people'],
  ['renewable resources', 'tài nguyên tái tạo', 'Solar and wind power are examples of renewable resources.', 'resources that can be naturally replenished, such as sunlight or wind'],
  ['non-renewable resources', 'tài nguyên không tái tạo', 'Fossil fuels are non-renewable resources.', 'resources that cannot be replaced once they are used up'],
  ['fossil fuels', 'nhiên liệu hóa thạch', 'Burning fossil fuels releases large amounts of carbon dioxide.', 'fuels such as coal, oil and gas formed from ancient remains'],
  ['solar energy', 'năng lượng mặt trời', 'The house is powered entirely by solar energy.', 'energy produced from sunlight'],
  ['wind power', 'năng lượng gió', 'The country plans to invest more in wind power.', 'energy produced by the movement of wind, usually via turbines'],
  ['hydroelectric power', 'thủy điện', 'The dam generates hydroelectric power for the whole region.', 'electricity produced by the force of moving water'],
  ['climate', 'khí hậu', 'The region has a warm, dry climate.', 'the general weather conditions typical of an area'],
  ['climate change', 'biến đổi khí hậu', 'Climate change is causing more extreme weather events.', 'long-term changes in temperature and weather patterns, largely caused by humans'],
  ['global warming', 'nóng lên toàn cầu', 'Global warming is causing ice caps to melt.', 'the gradual increase in the Earth\'s average temperature'],
  ['greenhouse effect', 'hiệu ứng nhà kính', 'The greenhouse effect traps heat in the Earth\'s atmosphere.', 'the process by which gases trap heat near the Earth\'s surface'],
  ['greenhouse gases', 'khí nhà kính', 'Carbon dioxide is one of the main greenhouse gases.', 'gases that trap heat in the atmosphere, contributing to global warming'],
  ['carbon emissions', 'lượng khí thải carbon', 'The company aims to reduce its carbon emissions by 2030.', 'the release of carbon dioxide into the atmosphere, especially from burning fuel'],
  ['air pollution', 'ô nhiễm không khí', 'Air pollution in big cities can cause health problems.', 'the presence of harmful substances in the air'],
  ['water pollution', 'ô nhiễm nước', 'Factory waste is a major cause of water pollution.', 'the contamination of rivers, lakes or oceans with harmful substances'],
  ['soil pollution', 'ô nhiễm đất', 'Soil pollution can affect crop growth for years.', 'the contamination of land with harmful chemicals or waste'],
  ['environmental pollution', 'ô nhiễm môi trường', 'Environmental pollution is a growing concern worldwide.', 'the contamination of air, water or land with harmful substances'],
  ['deforestation', 'nạn phá rừng', 'Deforestation is destroying habitats around the world.', 'the cutting down of large areas of forest'],
  ['forest', 'rừng', 'The forest covers most of the northern part of the country.', 'a large area covered mainly with trees'],
  ['rainforest', 'rừng nhiệt đới', 'The Amazon rainforest produces a large share of the world\'s oxygen.', 'a dense forest found in tropical areas with heavy rainfall'],
  ['desert', 'sa mạc', 'Very few plants can survive in the desert.', 'a large, dry area of land with little rainfall'],
  ['ocean', 'đại dương', 'Plastic waste is polluting the ocean.', 'a large body of salt water covering much of the Earth'],
  ['coastline', 'đường bờ biển', 'Rising sea levels threaten the country\'s coastline.', 'the outline or shape of a coast'],
  ['mountain range', 'dãy núi', 'The mountain range stretches across three countries.', 'a line of connected mountains'],
  ['natural disaster', 'thiên tai', 'The region is prone to natural disasters like floods and earthquakes.', 'a sudden event caused by nature that causes great damage'],
  ['earthquake', 'động đất', 'The earthquake destroyed hundreds of buildings.', 'a sudden violent shaking of the ground'],
  ['flood', 'lũ lụt', 'Heavy rain caused severe flooding in the region.', 'an overflow of water onto land that is usually dry'],
  ['drought', 'hạn hán', 'The drought has lasted for over a year, damaging crops.', 'a long period of unusually low rainfall'],
  ['storm', 'bão', 'The storm brought strong winds and heavy rain.', 'a period of very bad weather with strong wind and rain'],
  ['hurricane', 'bão lớn', 'The hurricane caused widespread damage along the coast.', 'a violent tropical storm with very strong winds'],
  ['volcanic eruption', 'núi lửa phun trào', 'The volcanic eruption forced thousands of people to evacuate.', 'a sudden release of lava, ash and gas from a volcano'],
  ['destroy a habitat', 'phá hủy môi trường sống', 'Deforestation destroys the habitat of countless species.', 'to completely damage or ruin the natural home of animals or plants'],
  ['protect the environment', 'bảo vệ môi trường', 'We should all do our part to protect the environment.', 'to take action to keep the natural world safe from harm'],
  ['preserve nature', 'bảo tồn thiên nhiên', 'National parks help preserve nature for future generations.', 'to keep the natural world safe and unspoiled'],
  ['protect wildlife', 'bảo vệ động vật hoang dã', 'Laws have been passed to protect wildlife in the region.', 'to take action to keep wild animals safe from harm'],
  ['conserve natural resources', 'bảo tồn tài nguyên thiên nhiên', 'We need to conserve natural resources for future generations.', 'to use natural materials carefully so they are not wasted or destroyed'],
  ['reduce pollution', 'giảm ô nhiễm', 'Stricter laws could help reduce pollution in cities.', 'to lower the amount of harmful substances released into the environment'],
  ['reduce carbon emissions', 'giảm khí thải carbon', 'Countries have agreed to reduce carbon emissions.', 'to lower the amount of carbon dioxide released into the atmosphere'],
  ['cut down on', 'cắt giảm', 'We should cut down on single-use plastic.', 'to reduce the amount of something used'],
  ['recycle waste', 'tái chế rác thải', 'The city encourages residents to recycle waste.', 'to process used materials so they can be used again'],
  ['dispose of waste', 'xử lý rác thải', 'Factories must dispose of waste safely.', 'to get rid of unwanted materials properly'],
  ['produce waste', 'tạo ra rác thải', 'Households produce a huge amount of waste every year.', 'to create unwanted material as a result of an activity'],
  ['save energy', 'tiết kiệm năng lượng', 'Turning off lights when not needed helps save energy.', 'to use less power or fuel'],
  ['use renewable energy', 'sử dụng năng lượng tái tạo', 'More countries are choosing to use renewable energy.', 'to use energy from sources that can be naturally replenished'],
  ['raise environmental awareness', 'nâng cao nhận thức về môi trường', 'Schools are working to raise environmental awareness among students.', 'to help more people understand and care about environmental issues'],
  ['take action', 'hành động', 'Governments must take action to address climate change.', 'to do something in order to achieve a result'],
  ['take measures', 'thực hiện các biện pháp', 'The city has taken measures to reduce traffic pollution.', 'to carry out specific actions to achieve a goal'],
  ['tackle climate change', 'giải quyết vấn đề biến đổi khí hậu', 'World leaders met to discuss how to tackle climate change.', 'to take action to deal with the problem of climate change'],
  ['combat global warming', 'chống lại hiện tượng nóng lên toàn cầu', 'Renewable energy is one way to combat global warming.', 'to take action against the rise in global temperatures'],
  ['be responsible for', 'chịu trách nhiệm về/gây ra', 'Human activity is largely responsible for climate change.', 'to be the cause of something, especially something negative'],
  ['be harmful to', 'có hại cho', 'Plastic waste is harmful to marine life.', 'to cause damage or harm to something'],
  ['be beneficial to', 'có lợi cho', 'Planting trees is beneficial to the environment.', 'to be helpful or good for something'],
  ['have an impact on', 'có ảnh hưởng đến', 'Pollution has a huge impact on public health.', 'to cause an effect on something'],
  ['pose a threat to', 'đe dọa', 'Rising sea levels pose a threat to coastal cities.', 'to be a possible source of danger to something'],
  ['be at risk of extinction', 'có nguy cơ tuyệt chủng', 'Many marine species are at risk of extinction.', 'to be in danger of dying out completely'],
  ['be threatened with extinction', 'bị đe dọa tuyệt chủng', 'The panda was once threatened with extinction.', 'to be in danger of dying out completely'],
  ['a major environmental issue', 'một vấn đề môi trường lớn', 'Plastic pollution is a major environmental issue today.', 'an important problem affecting the natural world'],
  ['a serious threat', 'một mối đe dọa nghiêm trọng', 'Climate change poses a serious threat to coastal communities.', 'a significant danger or risk'],
  ['environmentally friendly', 'thân thiện với môi trường', 'The company now uses environmentally friendly packaging.', 'not harmful to the natural environment'],
  ['environmentally sustainable', 'bền vững về môi trường', 'The city aims to become environmentally sustainable by 2040.', 'able to continue without causing long-term damage to the environment'],
  ['protect future generations', 'bảo vệ các thế hệ tương lai', 'We must act now to protect future generations.', 'to take action to keep people who will live in the future safe'],
];

const lessons = [
  {
    title: 'Mindset 1 Unit 1-2',
    description: 'Relationships · Places and Buildings — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 15,
    words: dedupeWords([...unit1, ...unit2]),
  },
  {
    title: 'Mindset 1 Unit 3-4',
    description: 'Education and Employment · Food and Drink — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 16,
    words: dedupeWords([...unit3, ...unit4]),
  },
  {
    title: 'Mindset 1 Unit 5-6',
    description: 'Consumerism · Leisure Time — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 17,
    words: dedupeWords([...unit5, ...unit6]),
  },
  {
    title: 'Mindset 1 Unit 7-8',
    description: 'Fame and the Media · Natural World — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 18,
    words: dedupeWords([...unit7, ...unit8]),
  },
];

function toWordDoc([word, meaning, example, definition]) {
  return { word, meaning, example, definition, ipa: '', partOfSpeech: '', collocations: [], distractors: [] };
}

// A handful of general phrases can recur across adjacent units' own source
// lists — drop later repeats so a single lesson never quizzes the same
// word twice.
function dedupeWords(entries) {
  const seen = new Set();
  return entries.filter(([word]) => {
    const key = word.trim().toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

async function runSeed() {
  const VocabularyLesson = require('../models/VocabularyLesson');
  const User = require('../models/User');

  const admin = await User.findOne({ email: ADMIN_EMAIL }).select('_id').lean();
  if (!admin) throw new Error(`Admin user not found: ${ADMIN_EMAIL}`);

  for (const lesson of lessons) {
    const existing = await VocabularyLesson.findOne({ title: lesson.title }).lean();
    if (existing) {
      console.log(`[SeedVocabMindset1] "${lesson.title}" already exists (_id=${existing._id}) – skip`);
      continue;
    }
    const doc = await VocabularyLesson.create({
      title: lesson.title,
      description: lesson.description,
      difficulty: lesson.difficulty,
      order: lesson.order,
      targetClass: '',
      published: false, // review before publishing to students
      createdBy: admin._id,
      words: lesson.words.map(toWordDoc),
    });
    console.log(`[SeedVocabMindset1] Inserted "${doc.title}" (_id=${doc._id}, ${doc.words.length} words)`);
  }
}

if (require.main === module) {
  require('dotenv').config();
  const mongoose = require('mongoose');
  (async () => {
    await mongoose.connect(process.env.MONGO_URI);
    try {
      await runSeed();
    } finally {
      await mongoose.disconnect();
    }
  })().catch(e => { console.error('[SeedVocabMindset1] FAILED', e); process.exit(1); });
}

module.exports = { runSeed, lessons };
