// One-time content backfill: Mindset 1 vocabulary, grouped 2 units per
// VocabularyLesson ("Mindset 1 Unit X-Y") — same shared/curriculum-lesson
// approach as scripts/seedVocabLessonsMindset0.js (see that file for the
// full rationale: VocabularyLesson vs VocabBook, required parser fields).
//
// Run: node scripts/seedVocabLessonsMindset1.js
'use strict';

const ADMIN_EMAIL = 'tranhadeeptry@gmail.com'; // existing admin — createdBy

// ── Unit 1: Education ────────────────────────────────────────────────────
const unit1 = [
  ['education', 'giáo dục', 'Education plays a vital role in a country\'s development.', 'the process of teaching and learning, especially in schools'],
  ['educational institution', 'cơ sở giáo dục', 'The university is one of the oldest educational institutions in the country.', 'an organisation such as a school or university that provides education'],
  ['academic achievement', 'thành tích học tập', 'Her academic achievement earned her a place at a top university.', 'success reached in schoolwork or study'],
  ['academic performance', 'kết quả học tập', 'Regular sleep can improve a student\'s academic performance.', 'how well a student does in their studies'],
  ['academic subject', 'môn học', 'Maths is her strongest academic subject.', 'a subject studied at school or university'],
  ['higher education', 'giáo dục đại học', 'Higher education gives graduates better job prospects.', 'education at university level or above'],
  ['primary education', 'giáo dục tiểu học', 'Primary education usually starts at the age of six.', 'education for young children, usually the first stage of schooling'],
  ['secondary education', 'giáo dục trung học', 'Secondary education prepares students for university or work.', 'education for older children, after primary school'],
  ['compulsory education', 'giáo dục bắt buộc', 'Compulsory education in this country lasts until the age of sixteen.', 'education that is required by law'],
  ['further education', 'giáo dục sau phổ thông', 'She took a further education course to gain new skills.', 'education after secondary school, below university level'],
  ['undergraduate', 'sinh viên đại học', 'He is an undergraduate studying economics.', 'a student studying for their first university degree'],
  ['postgraduate', 'sau đại học', 'She is doing a postgraduate degree in psychology.', 'relating to study after completing a first university degree'],
  ['degree', 'bằng cấp', 'He earned a degree in engineering.', 'a qualification given by a university after a course of study'],
  ['qualification', 'trình độ/bằng cấp', 'A teaching qualification is required for this job.', 'an official record showing that someone has completed training or an exam'],
  ['scholarship', 'học bổng', 'She was awarded a scholarship to study abroad.', 'money given to a student to help pay for their education'],
  ['tuition fee', 'học phí', 'Tuition fees have increased significantly in recent years.', 'the money charged for teaching, especially at a university'],
  ['lecture', 'bài giảng', 'The professor gave a fascinating lecture on climate change.', 'a talk given to teach people about a subject, especially at university'],
  ['assignment', 'bài tập được giao', 'She finished her assignment before the deadline.', 'a piece of work given to a student to complete'],
  ['assessment', 'sự đánh giá', 'The course includes both written and oral assessment.', 'the process of judging a student\'s knowledge or performance'],
  ['examination', 'kỳ thi', 'Students must pass the final examination to graduate.', 'a formal test of knowledge or skill'],
  ['curriculum', 'chương trình học', 'The school introduced coding into the curriculum.', 'the subjects included in a course of study'],
  ['course', 'khóa học/môn học', 'He enrolled in a business course at the local college.', 'a series of lessons on a particular subject'],
  ['subject', 'môn học', 'History is her favourite subject.', 'an area of knowledge studied in school or university'],
  ['semester', 'học kỳ', 'The first semester ends in December.', 'one of the two main periods a school or university year is divided into'],
  ['campus', 'khuôn viên trường', 'The university campus has several modern buildings.', 'the land and buildings of a university or college'],
  ['faculty', 'khoa/giảng viên', 'She works in the Faculty of Engineering.', 'a department of a university, or the teaching staff there'],
  ['classmate', 'bạn cùng lớp', 'She studied with her classmates for the exam.', 'a person who is in the same class as you'],
  ['lecturer', 'giảng viên', 'The lecturer explained the theory using real examples.', 'a person who teaches at a university or college'],
  ['professor', 'giáo sư', 'Professor Smith has taught at the university for twenty years.', 'a senior university teacher, usually an expert in their field'],
  ['academic year', 'năm học', 'The academic year usually starts in September.', 'the period of time schools and universities are open, divided into terms'],
  ['learning environment', 'môi trường học tập', 'A positive learning environment helps students perform better.', 'the setting and conditions in which learning takes place'],
  ['educational background', 'nền tảng học vấn', 'Her educational background is in mathematics and computer science.', 'a person\'s history of schooling and qualifications'],
  ['learning experience', 'trải nghiệm học tập', 'Studying abroad was a valuable learning experience for her.', 'something that teaches a person new knowledge or skills'],
  ['teaching method', 'phương pháp giảng dạy', 'The school adopted a new teaching method based on group work.', 'a particular way of teaching a subject'],
  ['learning style', 'phong cách học tập', 'Everyone has a different learning style, some prefer visuals.', 'the particular way a person prefers to learn'],
  ['study skills', 'kỹ năng học tập', 'The workshop taught useful study skills like note-taking.', 'techniques that help a person learn effectively'],
  ['critical thinking', 'tư duy phản biện', 'The course helps students develop critical thinking.', 'the ability to analyse facts and form a reasoned judgement'],
  ['problem-solving skills', 'kỹ năng giải quyết vấn đề', 'Maths lessons help build problem-solving skills.', 'the ability to find solutions to difficult situations'],
  ['practical skills', 'kỹ năng thực tế', 'The course focuses on practical skills rather than just theory.', 'abilities that involve doing tasks rather than just knowing facts'],
  ['develop a skill', 'phát triển một kỹ năng', 'She developed her writing skill through daily practice.', 'to gradually build an ability through practice'],
  ['gain knowledge', 'tiếp thu kiến thức', 'Reading widely helps you gain knowledge about many topics.', 'to acquire information or understanding'],
  ['acquire knowledge', 'tiếp thu kiến thức', 'Students acquire knowledge through both lectures and reading.', 'to obtain new information or understanding'],
  ['gain experience', 'tích lũy kinh nghiệm', 'Internships help students gain experience before graduating.', 'to acquire practical knowledge or skill through doing something'],
  ['attend a lecture', 'tham dự một buổi giảng', 'Students are expected to attend every lecture.', 'to go to and listen to a talk given to teach a subject'],
  ['take an exam', 'tham gia kỳ thi', 'Thousands of students take the exam every year.', 'to sit and complete a test'],
  ['sit an exam', 'dự thi', 'She sat her final exam last week.', 'to take a formal test'],
  ['pass an exam', 'vượt qua kỳ thi', 'She worked hard and passed her exam with a great score.', 'to succeed in a test'],
  ['fail an exam', 'trượt kỳ thi', 'He failed the exam because he didn\'t study enough.', 'to be unsuccessful in a test'],
  ['do well in an exam', 'làm tốt trong kỳ thi', 'She did well in the exam thanks to careful preparation.', 'to perform successfully in a test'],
  ['get a degree', 'lấy bằng', 'She got a degree in law after four years of study.', 'to complete a university course and receive a degree'],
  ['pursue a degree', 'theo đuổi một bằng cấp', 'He decided to pursue a degree in medicine.', 'to work towards completing a university qualification'],
  ['enrol in a course', 'đăng ký một khóa học', 'She enrolled in an online course to learn graphic design.', 'to officially register to join a course of study'],
  ['keep up with studies', 'theo kịp việc học', 'She works hard to keep up with her studies despite a busy schedule.', 'to stay on track with schoolwork and not fall behind'],
  ['fall behind with studies', 'bị tụt lại trong việc học', 'He fell behind with his studies after missing two weeks of school.', 'to fail to keep up with the required pace of schoolwork'],
  ['make progress', 'tiến bộ', 'He has made real progress since he started the course.', 'to improve or move forward gradually'],
  ['meet academic requirements', 'đáp ứng yêu cầu học tập', 'Students must meet academic requirements to graduate.', 'to satisfy the standards set by a school or course'],
  ['under academic pressure', 'chịu áp lực học tập', 'Many students feel under academic pressure before exams.', 'experiencing stress caused by the demands of studying'],
  ['broaden one\'s knowledge', 'mở rộng kiến thức', 'Travelling can really broaden your knowledge of the world.', 'to increase the amount of knowledge one has'],
  ['develop critical thinking', 'phát triển tư duy phản biện', 'Discussion-based lessons help develop critical thinking.', 'to build the ability to analyse and evaluate information'],
  ['put knowledge into practice', 'áp dụng kiến thức vào thực tế', 'The internship let her put her knowledge into practice.', 'to use what one has learned in a real situation'],
];

// ── Unit 2: Lifestyle ─────────────────────────────────────────────────────
const unit2 = [
  ['lifestyle', 'lối sống', 'His lifestyle changed completely after he started working from home.', 'the way in which a person lives their everyday life'],
  ['daily routine', 'thói quen hằng ngày', 'Waking up at six is part of her daily routine.', 'the usual things a person does every day, in the same order'],
  ['way of life', 'cách sống', 'City life offers a very different way of life from the countryside.', 'the typical pattern of behaviour of a person or group'],
  ['quality of life', 'chất lượng cuộc sống', 'A shorter commute would greatly improve his quality of life.', 'the general level of comfort and well-being in a person\'s life'],
  ['healthy lifestyle', 'lối sống lành mạnh', 'Eating well and exercising are key parts of a healthy lifestyle.', 'a way of living that keeps you physically and mentally well'],
  ['active lifestyle', 'lối sống năng động', 'She leads an active lifestyle, cycling to work every day.', 'a way of living that involves a lot of physical movement'],
  ['sedentary lifestyle', 'lối sống ít vận động', 'A sedentary lifestyle can lead to health problems over time.', 'a way of living that involves little physical movement, often sitting'],
  ['work-life balance', 'sự cân bằng giữa công việc và cuộc sống', 'Flexible working hours can improve work-life balance.', 'a healthy balance between time spent working and personal life'],
  ['leisure activity', 'hoạt động giải trí', 'Gardening is her favourite leisure activity.', 'an activity done for enjoyment in one\'s free time'],
  ['free time', 'thời gian rảnh', 'She plays the guitar in her free time.', 'time when a person is not working or studying'],
  ['spare time', 'thời gian rảnh', 'He reads novels in his spare time.', 'time when a person is not working or studying'],
  ['physical activity', 'hoạt động thể chất', 'Doctors recommend at least 30 minutes of physical activity a day.', 'any movement of the body that uses energy'],
  ['exercise regularly', 'tập thể dục thường xuyên', 'People who exercise regularly tend to feel more energetic.', 'to do physical activity often and consistently'],
  ['keep fit', 'giữ dáng/giữ sức khỏe', 'He plays football to keep fit.', 'to stay physically healthy through activity'],
  ['stay healthy', 'duy trì sức khỏe', 'Drinking water and sleeping well help you stay healthy.', 'to remain in good physical condition'],
  ['balanced diet', 'chế độ ăn cân bằng', 'A balanced diet should contain protein, carbohydrates and fats.', 'a diet containing the right proportions of different food types'],
  ['healthy eating habits', 'thói quen ăn uống lành mạnh', 'Parents can help children develop healthy eating habits.', 'regular patterns of eating that are good for the body'],
  ['junk food', 'đồ ăn nhanh/đồ ăn không lành mạnh', 'Eating too much junk food can cause weight gain.', 'food that is quick to prepare but not very healthy'],
  ['fast food', 'thức ăn nhanh', 'Fast food is convenient but often high in fat and salt.', 'food that can be prepared and served very quickly'],
  ['processed food', 'thực phẩm chế biến sẵn', 'Doctors advise eating less processed food.', 'food that has been treated or changed before being eaten'],
  ['fresh produce', 'thực phẩm tươi', 'The market sells fresh produce straight from local farms.', 'fruits and vegetables that are recently harvested, not preserved'],
  ['social life', 'đời sống xã hội', 'University gave her an active social life.', 'the part of a person\'s life involving friends and social activities'],
  ['social activity', 'hoạt động xã hội', 'Joining a club is a great way to add more social activity to your week.', 'an activity that involves spending time with other people'],
  ['close relationship', 'mối quan hệ thân thiết', 'She has a close relationship with her sister.', 'a relationship in which people know and trust each other well'],
  ['spend time with', 'dành thời gian với', 'He likes to spend time with his family at the weekend.', 'to pass time together with someone'],
  ['get together', 'tụ họp', 'The whole family gets together every Sunday for lunch.', 'to meet with other people, especially socially'],
  ['hang out', 'đi chơi/thư giãn cùng nhau', 'They like to hang out at the café after school.', 'to spend time relaxing with friends'],
  ['take up a hobby', 'bắt đầu một sở thích', 'She took up painting as a hobby last year.', 'to start doing an activity regularly for pleasure'],
  ['give up a habit', 'từ bỏ một thói quen', 'He gave up the habit of checking his phone before bed.', 'to stop doing something one regularly does'],
  ['break a habit', 'bỏ một thói quen', 'It took months to break the habit of skipping breakfast.', 'to stop doing something that has become automatic'],
  ['form a habit', 'hình thành một thói quen', 'It usually takes weeks to form a new habit.', 'to gradually develop a regular pattern of behaviour'],
  ['develop a routine', 'xây dựng thói quen', 'She developed a morning routine to start the day well.', 'to gradually build a regular way of doing things'],
  ['stick to a routine', 'duy trì một thói quen', 'It can be hard to stick to a routine during holidays.', 'to continue following a fixed pattern of behaviour'],
  ['manage one\'s time', 'quản lý thời gian', 'Learning to manage your time well reduces stress.', 'to organise how much time is spent on different tasks'],
  ['save time', 'tiết kiệm thời gian', 'Meal prepping on Sundays saves time during the week.', 'to use less time than usual'],
  ['waste time', 'lãng phí thời gian', 'It\'s easy to waste time scrolling through social media.', 'to use time in a way that achieves nothing useful'],
  ['have a busy schedule', 'có lịch trình bận rộn', 'She has a busy schedule with work and evening classes.', 'to have many planned activities and little free time'],
  ['lead a busy life', 'có cuộc sống bận rộn', 'He leads a busy life juggling work and family.', 'to live in a way that involves many activities and little rest'],
  ['get enough sleep', 'ngủ đủ giấc', 'Try to get enough sleep before an exam.', 'to sleep for a sufficient amount of time'],
  ['get plenty of rest', 'nghỉ ngơi đầy đủ', 'It\'s important to get plenty of rest when you\'re ill.', 'to rest for a generous amount of time'],
  ['reduce stress', 'giảm căng thẳng', 'Yoga is a good way to reduce stress.', 'to lower the level of mental tension one feels'],
  ['cope with stress', 'đối phó với căng thẳng', 'Exercise helps many people cope with stress.', 'to deal successfully with a difficult or stressful situation'],
  ['relieve stress', 'giải tỏa căng thẳng', 'Listening to music helps relieve stress after a busy day.', 'to make stress or tension less severe'],
  ['feel exhausted', 'cảm thấy kiệt sức', 'She felt exhausted after the long journey.', 'to feel extremely tired'],
  ['feel energetic', 'cảm thấy tràn đầy năng lượng', 'I feel more energetic after a good night\'s sleep.', 'to feel full of energy and enthusiasm'],
  ['be physically active', 'năng động về thể chất', 'Children need to be physically active every day.', 'to regularly move the body through exercise or activity'],
  ['maintain a healthy lifestyle', 'duy trì lối sống lành mạnh', 'It takes discipline to maintain a healthy lifestyle.', 'to continue living in a way that is good for one\'s health'],
  ['improve one\'s quality of life', 'cải thiện chất lượng cuộc sống', 'Regular exercise can greatly improve your quality of life.', 'to make one\'s general well-being and happiness better'],
  ['have a positive impact on', 'có tác động tích cực đến', 'A good diet has a positive impact on overall health.', 'to cause a good change or effect on something'],
  ['have a negative impact on', 'có tác động tiêu cực đến', 'Lack of sleep can have a negative impact on concentration.', 'to cause a harmful change or effect on something'],
  ['be beneficial to', 'có lợi cho', 'Regular exercise is beneficial to both body and mind.', 'to be helpful or good for something'],
  ['be harmful to', 'có hại cho', 'Too much stress can be harmful to your health.', 'to cause damage or harm to something'],
];

// ── Unit 3: Travel ───────────────────────────────────────────────────────
// Merged from two source lists the admin compiled (general travel terms +
// a more detailed flight/booking-focused pass) — deduped below.
const unit3 = [
  ['travel', 'du lịch', 'Travel broadens the mind and builds confidence.', 'to make a journey, usually to a distant place'],
  ['traveller', 'du khách/người đi du lịch', 'The hostel was full of travellers from all over the world.', 'a person who is travelling or who often travels'],
  ['tourist', 'khách du lịch', 'The city gets thousands of tourists every summer.', 'a person who visits a place for pleasure'],
  ['tourism', 'ngành du lịch', 'Tourism is one of the country\'s biggest industries.', 'the business of providing services for tourists'],
  ['destination', 'điểm đến', 'After a long flight, we finally reached our destination.', 'the place where someone is travelling to'],
  ['tourist attraction', 'điểm thu hút khách du lịch', 'The waterfall is the region\'s biggest tourist attraction.', 'a place that many tourists like to visit'],
  ['popular destination', 'điểm đến phổ biến', 'Thailand is a popular destination for beach holidays.', 'a place that many people choose to travel to'],
  ['travel abroad', 'đi du lịch nước ngoài', 'Many students travel abroad during the summer break.', 'to travel to a foreign country'],
  ['domestic travel', 'du lịch trong nước', 'Domestic travel increased after international flights were restricted.', 'travel within one\'s own country'],
  ['international travel', 'du lịch quốc tế', 'International travel requires a valid passport.', 'travel to a foreign country'],
  ['package holiday', 'kỳ nghỉ trọn gói', 'They booked a package holiday that included flights and hotels.', 'a holiday in which flights, accommodation and often meals are sold together'],
  ['guided tour', 'chuyến tham quan có hướng dẫn', 'We joined a guided tour of the old city.', 'a tour led by a person who explains the sights'],
  ['sightseeing', 'việc tham quan', 'We spent the afternoon sightseeing around the old town.', 'the activity of visiting interesting or famous places'],
  ['go sightseeing', 'đi tham quan', 'On our first day, we went sightseeing around the city.', 'to visit interesting or famous places as a tourist'],
  ['travel agency', 'công ty du lịch', 'We booked our trip through a local travel agency.', 'a business that arranges holidays and travel for customers'],
  ['travel agent', 'đại lý du lịch', 'The travel agent recommended a resort near the beach.', 'a person who arranges holidays and travel for customers'],
  ['accommodation', 'chỗ ở', 'Finding affordable accommodation was the hardest part of planning the trip.', 'a place to live or stay'],
  ['hotel', 'khách sạn', 'We stayed in a hotel near the city centre.', 'a building providing rooms for travellers to stay in'],
  ['hostel', 'nhà nghỉ', 'Backpackers often stay in hostels to save money.', 'cheap accommodation, often with shared rooms, for travellers'],
  ['guesthouse', 'nhà khách', 'The guesthouse offered a warm, homely atmosphere.', 'a small, privately owned house offering paid accommodation'],
  ['campsite', 'khu cắm trại', 'We pitched our tent at a campsite near the lake.', 'an area where people can camp'],
  ['book accommodation', 'đặt chỗ ở', 'We booked accommodation online a month before the trip.', 'to reserve a place to stay in advance'],
  ['make a reservation', 'đặt chỗ', 'She made a reservation at a restaurant near the hotel.', 'to arrange in advance to have a room, table or seat'],
  ['check in', 'làm thủ tục', 'We checked in at the hotel around noon.', 'to register on arrival at a hotel or airport'],
  ['check out', 'trả phòng', 'Guests must check out by eleven in the morning.', 'to leave a hotel after paying the bill'],
  ['flight', 'chuyến bay', 'Our flight was delayed by two hours.', 'a journey made by aeroplane'],
  ['departure', 'sự khởi hành', 'Please arrive two hours before departure.', 'the act of leaving a place'],
  ['arrival', 'sự đến nơi', 'The arrival hall was crowded with passengers.', 'the act of reaching a place'],
  ['departure time', 'giờ khởi hành', 'Check the departure time before leaving for the airport.', 'the time at which a journey begins'],
  ['arrival time', 'giờ đến', 'The arrival time was delayed due to bad weather.', 'the time at which a journey ends'],
  ['boarding pass', 'thẻ lên máy bay', 'She showed her boarding pass at the gate.', 'a document allowing a passenger to board a plane'],
  ['luggage', 'hành lý', 'We had to pay extra for heavy luggage.', 'the bags and suitcases a traveller takes with them'],
  ['hand luggage', 'hành lý xách tay', 'Only one piece of hand luggage is allowed on this flight.', 'a small bag a passenger carries with them onto a plane'],
  ['suitcase', 'va-li', 'She packed her suitcase the night before the flight.', 'a rectangular case used for carrying clothes when travelling'],
  ['journey', 'hành trình/chuyến đi', 'The journey to the airport took about 40 minutes.', 'an act of travelling from one place to another'],
  ['trip', 'chuyến đi', 'We\'re planning a short trip to the mountains.', 'a journey made for a particular purpose'],
  ['voyage', 'chuyến hải trình', 'The voyage across the ocean took nearly two weeks.', 'a long journey, especially by sea'],
  ['commute', 'đi lại hằng ngày', 'His daily commute to work takes about an hour.', 'the regular journey between home and work'],
  ['public transport', 'phương tiện giao thông công cộng', 'Many people take public transport to avoid traffic jams.', 'buses, trains and other vehicles that anyone can use to travel'],
  ['means of transport', 'phương tiện đi lại', 'The bicycle is a popular means of transport in this city.', 'a method or vehicle used to travel from place to place'],
  ['traffic jam', 'tắc đường', 'We were stuck in a traffic jam for almost an hour.', 'a long line of vehicles that cannot move or move very slowly'],
  ['rush hour', 'giờ cao điểm', 'It\'s best to avoid travelling during rush hour.', 'the time of day when traffic is heaviest'],
  ['get around', 'đi lại trong một khu vực', 'It\'s easy to get around by bicycle in this city.', 'to travel or move from place to place'],
  ['get lost', 'bị lạc', 'We got lost trying to find the museum.', 'to be unable to find your way to a place'],
  ['ask for directions', 'hỏi đường', 'We stopped to ask for directions to the station.', 'to ask someone how to get to a place'],
  ['find one\'s way', 'tìm đường', 'It took a while to find our way back to the hotel.', 'to succeed in reaching a place, especially after being unsure how'],
  ['travel light', 'mang ít hành lý khi đi du lịch', 'Backpackers usually travel light to make moving around easier.', 'to travel carrying only a small amount of luggage'],
  ['set off', 'khởi hành', 'We set off early to avoid the traffic.', 'to begin a journey'],
  ['go on a trip', 'đi du lịch', 'We went on a trip to the mountains for the long weekend.', 'to travel somewhere for a period of time'],
  ['take a trip', 'thực hiện một chuyến đi', 'We decided to take a trip to the coast.', 'to go on a journey somewhere'],
  ['have a memorable experience', 'có một trải nghiệm đáng nhớ', 'Watching the sunrise gave us a memorable experience.', 'to have something happen that is easy to remember because it is special'],
  ['enjoy the scenery', 'tận hưởng phong cảnh', 'We stopped the car several times just to enjoy the scenery.', 'to take pleasure in looking at beautiful natural views'],
  ['explore a new place', 'khám phá một địa điểm mới', 'She loves exploring new places whenever she travels.', 'to travel around an unfamiliar place to learn about it'],
  ['visit a tourist attraction', 'tham quan điểm du lịch', 'We visited several tourist attractions during our stay.', 'to go and see a place that is popular with tourists'],
  ['experience local culture', 'trải nghiệm văn hóa địa phương', 'Homestays are a great way to experience local culture.', 'to encounter and take part in the customs of a place'],
  ['try local food', 'thử đồ ăn địa phương', 'One of the best parts of travelling is trying local food.', 'to eat food that is typical of a country or region'],
  ['meet new people', 'gặp gỡ những người mới', 'Travelling alone gives you more chances to meet new people.', 'to become acquainted with people you have not met before'],
  ['learn about other cultures', 'tìm hiểu về các nền văn hóa khác', 'Travelling helps young people learn about other cultures.', 'to gain knowledge about the customs and traditions of other places'],
  ['broaden one\'s horizons', 'mở rộng tầm hiểu biết', 'Studying abroad really broadened her horizons.', 'to increase the range of one\'s knowledge and experience'],
  ['escape from everyday life', 'thoát khỏi cuộc sống thường ngày', 'Travelling helps people escape from everyday life and relax.', 'to get away from one\'s usual, routine daily activities'],
  ['take a break from work', 'tạm nghỉ khỏi công việc', 'She took a break from work to travel around Europe.', 'to stop working for a period of time to rest'],
  ['travel on a budget', 'du lịch với ngân sách tiết kiệm', 'Backpackers often travel on a budget, staying in cheap hostels.', 'to travel while spending as little money as possible'],
  ['travel independently', 'du lịch tự túc', 'She prefers to travel independently rather than join a tour group.', 'to travel by oneself, without a guide or organised group'],
  ['travel with a group', 'đi du lịch theo nhóm', 'Travelling with a group can feel safer in unfamiliar places.', 'to travel together with an organised group of people'],
  ['be crowded with tourists', 'đông khách du lịch', 'The beach is crowded with tourists in the summer.', 'to be full of visitors, especially tourists'],
  ['be famous for', 'nổi tiếng về', 'The city is famous for its ancient temples.', 'to be widely known for a particular quality or feature'],
  ['be well worth visiting', 'rất đáng để tham quan', 'The old town is well worth visiting if you have time.', 'to be a place that is definitely worth the effort to see'],
  ['a wide range of', 'nhiều loại/phạm vi đa dạng', 'The resort offers a wide range of activities for guests.', 'many different types or varieties of something'],
  ['a memorable trip', 'một chuyến đi đáng nhớ', 'Our trip to Japan was a truly memorable trip.', 'a journey that is easy to remember because it was special'],
  ['adventure', 'chuyến phiêu lưu', 'Backpacking through South America was a real adventure.', 'an exciting and sometimes risky experience'],
  ['attraction', 'điểm tham quan', 'The old castle is the town\'s main attraction.', 'a place, event or person that people find interesting'],
  ['backpacking', 'du lịch bụi', 'Backpacking is a cheap way to see many countries.', 'travelling with a backpack, usually on a low budget'],
  ['brochure', 'tờ quảng cáo/tờ giới thiệu', 'She picked up a brochure about local tours.', 'a printed booklet giving information about a place or service'],
  ['excursion', 'chuyến tham quan ngắn', 'We went on a day excursion to a nearby island.', 'a short trip made for pleasure'],
  ['holiday resort', 'khu nghỉ dưỡng', 'The holiday resort has three swimming pools and a private beach.', 'a place people visit for a relaxing holiday, offering facilities for guests'],
  ['itinerary', 'lịch trình chuyến đi', 'Our itinerary included five cities in ten days.', 'a planned schedule or route for a journey'],
  ['passenger', 'hành khách', 'The bus was full of passengers heading to the airport.', 'a person travelling in a vehicle but not driving it'],
  ['souvenir', 'quà lưu niệm', 'We bought souvenirs to remember our trip.', 'an item bought to remember a place or event'],
  ['travel insurance', 'bảo hiểm du lịch', 'It\'s wise to buy travel insurance before an international trip.', 'insurance that covers costs related to travel, such as illness or lost luggage'],
  ['travel itinerary', 'lịch trình du lịch', 'She planned a detailed travel itinerary for the trip.', 'a planned schedule of places to visit during a journey'],
  ['visa', 'thị thực', 'You need a visa to visit that country.', 'an official document that allows entry to a foreign country'],
  ['delay', 'sự trì hoãn', 'The flight delay meant we missed our connection.', 'a period of time by which something is made late'],
  ['destination airport', 'sân bay đến', 'Check the weather at your destination airport before flying.', 'the airport where a flight is scheduled to arrive'],
  ['domestic flight', 'chuyến bay nội địa', 'Domestic flights are usually shorter than international ones.', 'a flight within one country'],
  ['international flight', 'chuyến bay quốc tế', 'International flights require a passport.', 'a flight between different countries'],
  ['direct flight', 'chuyến bay thẳng', 'We booked a direct flight to avoid a long layover.', 'a flight with no stops along the way'],
  ['return ticket', 'vé khứ hồi', 'A return ticket is often cheaper than two one-way tickets.', 'a ticket for a journey to a place and back again'],
  ['one-way ticket', 'vé một chiều', 'He bought a one-way ticket because he wasn\'t sure when he\'d return.', 'a ticket for a journey to a place only, not back'],
  ['book a flight', 'đặt vé máy bay', 'It\'s cheaper to book a flight several months in advance.', 'to reserve a seat on a flight in advance'],
  ['miss a flight', 'lỡ chuyến bay', 'He missed his flight because of heavy traffic.', 'to arrive too late to travel on a planned flight'],
  ['catch a flight', 'kịp chuyến bay', 'We left home early to catch our flight.', 'to arrive in time to travel on a flight'],
  ['explore a destination', 'khám phá một điểm đến', 'We spent a week exploring the destination on foot.', 'to travel around a place to learn about it'],
  ['try local cuisine', 'thử ẩm thực địa phương', 'Trying local cuisine is one of the joys of travelling.', 'to eat the typical food of a particular region'],
  ['meet the locals', 'gặp gỡ người dân địa phương', 'Staying with a host family let us meet the locals.', 'to get to know people who live in the place you are visiting'],
  ['take a break from everyday life', 'tạm thoát khỏi cuộc sống thường ngày', 'A weekend away lets you take a break from everyday life.', 'to temporarily stop one\'s usual routine to rest'],
  ['a popular tourist destination', 'điểm đến du lịch nổi tiếng', 'Bali is a popular tourist destination in Southeast Asia.', 'a place that many tourists choose to visit'],
  ['a breathtaking view', 'khung cảnh ngoạn mục', 'The mountain offered a breathtaking view of the valley.', 'a view that is extremely impressive or beautiful'],
  ['a historic site', 'địa điểm lịch sử', 'The old fort is a historic site protected by the government.', 'a place that is important because of its connection to history'],
  ['a remote area', 'khu vực hẻo lánh', 'The village is located in a remote area, far from the city.', 'a place that is far away and difficult to reach'],
  ['a crowded tourist attraction', 'điểm du lịch đông đúc', 'The museum is a crowded tourist attraction during summer.', 'a popular sightseeing place that is often full of visitors'],
  ['rich in history', 'giàu lịch sử', 'The old town is rich in history and culture.', 'having a lot of historical significance or interest'],
  ['be worth visiting', 'đáng để tham quan', 'The gallery is definitely worth visiting.', 'to be interesting or valuable enough to justify a visit'],
  ['be packed with tourists', 'chật kín khách du lịch', 'The beach is packed with tourists in July and August.', 'to be extremely full of visitors, especially tourists'],
];

// ── Unit 4: Technology ────────────────────────────────────────────────────
const unit4 = [
  ['technology', 'công nghệ', 'Technology has changed the way people communicate.', 'the use of scientific knowledge for practical purposes, especially in machines'],
  ['technological development', 'sự phát triển công nghệ', 'Technological development has transformed the healthcare industry.', 'the process of new technology being created and improved'],
  ['technological advancement', 'tiến bộ công nghệ', 'Recent technological advancement has made devices smaller and faster.', 'an improvement or new development in technology'],
  ['innovation', 'sự đổi mới', 'The company is known for its innovation in renewable energy.', 'a new idea, method or invention'],
  ['invention', 'phát minh', 'The smartphone is one of the most influential inventions of the century.', 'something newly created or designed'],
  ['device', 'thiết bị', 'This app works on almost any device.', 'a piece of equipment made for a particular purpose'],
  ['electronic device', 'thiết bị điện tử', 'Students are asked to turn off electronic devices during exams.', 'a device that uses electricity and often contains a circuit board'],
  ['digital technology', 'công nghệ kỹ thuật số', 'Digital technology has transformed how we shop and communicate.', 'technology based on computers and electronic systems'],
  ['digital age', 'thời đại kỹ thuật số', 'Privacy is a growing concern in the digital age.', 'the current period of time, characterised by widespread digital technology'],
  ['the Internet', 'Internet', 'The Internet has made it easier to access information.', 'the global network that connects computers around the world'],
  ['social media', 'mạng xã hội', 'Many young people spend hours on social media every day.', 'websites and apps that let people create and share content'],
  ['website', 'trang web', 'You can find more details on the company\'s website.', 'a set of related pages on the internet'],
  ['application', 'ứng dụng', 'She downloaded a new application to help her study.', 'a computer program designed for a particular purpose'],
  ['app', 'ứng dụng', 'There\'s an app for almost everything nowadays.', 'a short word for "application", a computer program, usually on a phone'],
  ['software', 'phần mềm', 'The company develops software for small businesses.', 'the programs used to operate computers'],
  ['hardware', 'phần cứng', 'The computer\'s hardware needed an upgrade to run the new software.', 'the physical parts of a computer or electronic system'],
  ['smartphone', 'điện thoại thông minh', 'Most people now own a smartphone.', 'a mobile phone that can access the internet and run apps'],
  ['tablet', 'máy tính bảng', 'The children use a tablet to watch videos.', 'a small, flat portable computer operated by touching the screen'],
  ['laptop', 'máy tính xách tay', 'He carries his laptop with him everywhere.', 'a small, portable computer'],
  ['computer screen', 'màn hình máy tính', 'Staring at a computer screen for too long can strain your eyes.', 'the flat surface of a computer that displays images or text'],
  ['keyboard', 'bàn phím', 'She types very quickly on the keyboard.', 'a set of keys used to enter information into a computer'],
  ['online platform', 'nền tảng trực tuyến', 'The course is taught entirely on an online platform.', 'a website or app that provides a particular service'],
  ['artificial intelligence', 'trí tuệ nhân tạo', 'Artificial intelligence is being used in many industries today.', 'computer systems able to perform tasks that normally require human intelligence'],
  ['robotics', 'ngành robot học', 'She studies robotics at university.', 'the branch of technology dealing with the design and use of robots'],
  ['automation', 'tự động hóa', 'Automation has replaced many manual jobs in factories.', 'the use of machines or computers to do work automatically'],
  ['cybersecurity', 'an ninh mạng', 'Companies invest heavily in cybersecurity to prevent hacking.', 'the protection of computer systems from digital attacks'],
  ['data', 'dữ liệu', 'The company collects data about its customers\' habits.', 'information, especially facts or numbers, collected for analysis'],
  ['personal information', 'thông tin cá nhân', 'Never share your personal information with strangers online.', 'private details about a person, such as their address or phone number'],
  ['online shopping', 'mua sắm trực tuyến', 'Online shopping has become very popular in recent years.', 'buying goods over the internet'],
  ['online banking', 'ngân hàng trực tuyến', 'Online banking lets you check your balance anytime.', 'managing bank accounts and transactions over the internet'],
  ['digital communication', 'giao tiếp kỹ thuật số', 'Digital communication has made staying in touch easier than ever.', 'communication carried out through electronic devices and the internet'],
  ['virtual reality', 'thực tế ảo', 'Virtual reality is increasingly used in education and training.', 'a computer-generated environment that feels real to the user'],
  ['access to information', 'khả năng tiếp cận thông tin', 'The internet has given people much greater access to information.', 'the ability to obtain facts and data'],
  ['access the Internet', 'truy cập Internet', 'It\'s difficult to access the Internet in remote areas.', 'to connect to and use the internet'],
  ['browse the Internet', 'lướt Internet', 'He spends his free time browsing the Internet.', 'to look casually at information or websites on the internet'],
  ['surf the Internet', 'lướt mạng', 'She surfs the Internet for hours after school.', 'to spend time looking at different websites for enjoyment'],
  ['download a file', 'tải một tệp xuống', 'It only takes a few seconds to download the file.', 'to copy a document or data from the internet onto a device'],
  ['upload a file', 'tải một tệp lên', 'He uploaded a file to share with his classmates.', 'to send a document or data to the internet or another device'],
  ['install software', 'cài đặt phần mềm', 'You need to install the software before you can use it.', 'to put a computer program onto a device so it can be used'],
  ['update an app', 'cập nhật ứng dụng', 'Remember to update the app to get the latest features.', 'to install the newest version of a computer program'],
  ['send a message', 'gửi tin nhắn', 'He sent a message to confirm the meeting time.', 'to communicate information to someone in written form'],
  ['make a video call', 'gọi video', 'We made a video call to celebrate her birthday together.', 'to make a call where participants can see each other on screen'],
  ['stay connected', 'duy trì kết nối', 'Smartphones help people stay connected with friends and family.', 'to remain in contact with others, often through technology'],
  ['keep in touch', 'giữ liên lạc', 'We keep in touch through video calls every week.', 'to communicate with someone regularly'],
  ['search for information', 'tìm kiếm thông tin', 'Students often search for information online for their homework.', 'to look for facts or data, usually online'],
  ['share information', 'chia sẻ thông tin', 'Social media makes it easy to share information quickly.', 'to give facts or data to other people'],
  ['store data', 'lưu trữ dữ liệu', 'The company stores data on secure servers.', 'to keep information saved for later use'],
  ['protect personal information', 'bảo vệ thông tin cá nhân', 'It\'s important to protect personal information online.', 'to keep private details safe from misuse'],
  ['save time', 'tiết kiệm thời gian', 'Online banking saves time compared to visiting a branch.', 'to use less time than usual'],
  ['increase efficiency', 'tăng hiệu quả', 'New software has helped increase efficiency at work.', 'to make a process work better with less waste of time or effort'],
  ['improve productivity', 'cải thiện năng suất', 'The new system has helped improve productivity across the company.', 'to make people or businesses produce more in less time'],
  ['reduce costs', 'giảm chi phí', 'Automation can help companies reduce costs.', 'to lower the amount of money spent'],
  ['make life easier', 'làm cuộc sống dễ dàng hơn', 'Smartphones have made life easier in many ways.', 'to make daily tasks simpler or more convenient'],
  ['have access to', 'có quyền/khả năng tiếp cận', 'Every student has access to the school\'s computers.', 'to be able to use or reach something'],
  ['depend on technology', 'phụ thuộc vào công nghệ', 'Modern life depends heavily on technology.', 'to rely on technology for everyday tasks'],
  ['rely on technology', 'dựa vào công nghệ', 'Many businesses rely on technology to function efficiently.', 'to depend on technology to do or achieve something'],
  ['keep up with technology', 'theo kịp công nghệ', 'It can be hard for older people to keep up with technology.', 'to stay updated with the latest technological developments'],
  ['adapt to technological changes', 'thích nghi với những thay đổi công nghệ', 'Employees need to adapt to technological changes quickly.', 'to adjust one\'s habits to make use of new technology'],
  ['be addicted to technology', 'nghiện công nghệ', 'Some teenagers seem to be addicted to technology.', 'to feel unable to stop using technology, especially devices'],
  ['spend time online', 'dành thời gian trực tuyến', 'Teenagers spend a lot of time online every day.', 'to use the internet for a period of time'],
  ['have a negative impact on', 'có tác động tiêu cực đến', 'Too much screen time can have a negative impact on sleep.', 'to cause a harmful change in something'],
  ['have a positive impact on', 'có tác động tích cực đến', 'Technology can have a positive impact on education.', 'to cause a good change in something'],
  ['pose a threat to', 'gây ra mối đe dọa đối với', 'Automation may pose a threat to certain jobs.', 'to be a possible source of danger or harm to something'],
  ['raise privacy concerns', 'làm dấy lên những lo ngại về quyền riêng tư', 'Facial recognition technology has raised privacy concerns.', 'to cause worries about how personal information is kept safe'],
  ['protect someone\'s privacy', 'bảo vệ quyền riêng tư của ai đó', 'Strong passwords help protect your privacy.', 'to keep a person\'s personal information and life safe from others'],
  ['technological progress', 'tiến bộ công nghệ', 'Technological progress has changed almost every industry.', 'the ongoing improvement and development of technology'],
  ['rapid technological change', 'sự thay đổi công nghệ nhanh chóng', 'Companies must adapt quickly to rapid technological change.', 'fast and continuous development in technology'],
  ['state-of-the-art technology', 'công nghệ hiện đại nhất', 'The hospital uses state-of-the-art technology to treat patients.', 'the most modern and advanced technology available'],
];

// ── Unit 5: The Natural World ────────────────────────────────────────────
const unit5 = [
  ['natural world', 'thế giới tự nhiên', 'The documentary explores the beauty of the natural world.', 'the physical environment, including plants, animals and landscapes'],
  ['natural environment', 'môi trường tự nhiên', 'Pollution is damaging the natural environment.', 'the surroundings in which plants, animals and people exist, unaffected by humans'],
  ['nature', 'thiên nhiên', 'She loves spending time in nature.', 'the physical world, including plants, animals and landscapes'],
  ['ecosystem', 'hệ sinh thái', 'The coral reef is a fragile ecosystem.', 'a community of living things and their environment functioning together'],
  ['habitat', 'môi trường sống', 'Deforestation destroys the habitat of many animals.', 'the natural home of a plant or animal'],
  ['wildlife', 'động vật hoang dã', 'The national park is home to a wide range of wildlife.', 'wild animals and plants living in their natural environment'],
  ['wildlife conservation', 'bảo tồn động vật hoang dã', 'The organisation focuses on wildlife conservation in Africa.', 'the protection of wild animals and their habitats'],
  ['endangered species', 'các loài có nguy cơ tuyệt chủng', 'The tiger is an endangered species.', 'a type of plant or animal that is at risk of dying out completely'],
  ['rare species', 'loài quý hiếm', 'The forest is home to several rare species of birds.', 'a type of plant or animal that is uncommon'],
  ['animal species', 'loài động vật', 'Thousands of animal species live in the rainforest.', 'a particular type of animal'],
  ['plant species', 'loài thực vật', 'Scientists discovered a new plant species in the jungle.', 'a particular type of plant'],
  ['biodiversity', 'đa dạng sinh học', 'The rainforest has some of the highest biodiversity on Earth.', 'the variety of plant and animal life in a particular area'],
  ['natural resources', 'tài nguyên thiên nhiên', 'The country is rich in natural resources such as oil and minerals.', 'materials or substances found in nature that are useful to people'],
  ['renewable resources', 'tài nguyên tái tạo', 'Solar and wind power are examples of renewable resources.', 'resources that can be naturally replenished, such as sunlight or wind'],
  ['non-renewable resources', 'tài nguyên không tái tạo', 'Fossil fuels are non-renewable resources.', 'resources that cannot be replaced once they are used up'],
  ['fossil fuels', 'nhiên liệu hóa thạch', 'Burning fossil fuels releases large amounts of carbon dioxide.', 'fuels such as coal, oil and gas formed from ancient remains'],
  ['solar energy', 'năng lượng mặt trời', 'The house is powered entirely by solar energy.', 'energy produced from sunlight'],
  ['wind power', 'năng lượng gió', 'The country plans to invest more in wind power.', 'energy produced by the movement of wind, usually via turbines'],
  ['hydroelectric power', 'thủy điện', 'The dam generates hydroelectric power for the whole region.', 'electricity produced by the force of moving water'],
  ['climate', 'khí hậu', 'The region has a warm, dry climate.', 'the general weather conditions typical of an area'],
  ['climate change', 'biến đổi khí hậu', 'Climate change is causing more extreme weather events.', 'long-term changes in temperature and weather patterns, largely caused by humans'],
  ['global warming', 'nóng lên toàn cầu', 'Global warming is causing ice caps to melt.', 'the gradual increase in the Earth\'s average temperature'],
  ['greenhouse effect', 'hiệu ứng nhà kính', 'The greenhouse effect traps heat in the Earth\'s atmosphere.', 'the process by which gases trap heat near the Earth\'s surface'],
  ['greenhouse gases', 'khí nhà kính', 'Carbon dioxide is one of the main greenhouse gases.', 'gases that trap heat in the atmosphere, contributing to global warming'],
  ['carbon emissions', 'lượng khí thải carbon', 'The company aims to reduce its carbon emissions by 2030.', 'the release of carbon dioxide into the atmosphere, especially from burning fuel'],
  ['air pollution', 'ô nhiễm không khí', 'Air pollution in big cities can cause health problems.', 'the presence of harmful substances in the air'],
  ['water pollution', 'ô nhiễm nước', 'Factory waste is a major cause of water pollution.', 'the contamination of rivers, lakes or oceans with harmful substances'],
  ['soil pollution', 'ô nhiễm đất', 'Soil pollution can affect crop growth for years.', 'the contamination of land with harmful chemicals or waste'],
  ['environmental pollution', 'ô nhiễm môi trường', 'Environmental pollution is a growing concern worldwide.', 'the contamination of air, water or land with harmful substances'],
  ['deforestation', 'nạn phá rừng', 'Deforestation is destroying habitats around the world.', 'the cutting down of large areas of forest'],
  ['forest', 'rừng', 'The forest covers most of the northern part of the country.', 'a large area covered mainly with trees'],
  ['rainforest', 'rừng nhiệt đới', 'The Amazon rainforest produces a large share of the world\'s oxygen.', 'a dense forest found in tropical areas with heavy rainfall'],
  ['desert', 'sa mạc', 'Very few plants can survive in the desert.', 'a large, dry area of land with little rainfall'],
  ['ocean', 'đại dương', 'Plastic waste is polluting the ocean.', 'a large body of salt water covering much of the Earth'],
  ['coastline', 'đường bờ biển', 'Rising sea levels threaten the country\'s coastline.', 'the outline or shape of a coast'],
  ['mountain range', 'dãy núi', 'The mountain range stretches across three countries.', 'a line of connected mountains'],
  ['natural disaster', 'thiên tai', 'The region is prone to natural disasters like floods and earthquakes.', 'a sudden event caused by nature that causes great damage'],
  ['earthquake', 'động đất', 'The earthquake destroyed hundreds of buildings.', 'a sudden violent shaking of the ground'],
  ['flood', 'lũ lụt', 'Heavy rain caused severe flooding in the region.', 'an overflow of water onto land that is usually dry'],
  ['drought', 'hạn hán', 'The drought has lasted for over a year, damaging crops.', 'a long period of unusually low rainfall'],
  ['storm', 'bão', 'The storm brought strong winds and heavy rain.', 'a period of very bad weather with strong wind and rain'],
  ['hurricane', 'bão lớn', 'The hurricane caused widespread damage along the coast.', 'a violent tropical storm with very strong winds'],
  ['volcanic eruption', 'núi lửa phun trào', 'The volcanic eruption forced thousands of people to evacuate.', 'a sudden release of lava, ash and gas from a volcano'],
  ['destroy a habitat', 'phá hủy môi trường sống', 'Deforestation destroys the habitat of countless species.', 'to completely damage or ruin the natural home of animals or plants'],
  ['protect the environment', 'bảo vệ môi trường', 'We should all do our part to protect the environment.', 'to take action to keep the natural world safe from harm'],
  ['preserve nature', 'bảo tồn thiên nhiên', 'National parks help preserve nature for future generations.', 'to keep the natural world safe and unspoiled'],
  ['protect wildlife', 'bảo vệ động vật hoang dã', 'Laws have been passed to protect wildlife in the region.', 'to take action to keep wild animals safe from harm'],
  ['conserve natural resources', 'bảo tồn tài nguyên thiên nhiên', 'We need to conserve natural resources for future generations.', 'to use natural materials carefully so they are not wasted or destroyed'],
  ['reduce pollution', 'giảm ô nhiễm', 'Stricter laws could help reduce pollution in cities.', 'to lower the amount of harmful substances released into the environment'],
  ['reduce carbon emissions', 'giảm khí thải carbon', 'Countries have agreed to reduce carbon emissions.', 'to lower the amount of carbon dioxide released into the atmosphere'],
  ['cut down on', 'cắt giảm', 'We should cut down on single-use plastic.', 'to reduce the amount of something used'],
  ['recycle waste', 'tái chế rác thải', 'The city encourages residents to recycle waste.', 'to process used materials so they can be used again'],
  ['dispose of waste', 'xử lý rác thải', 'Factories must dispose of waste safely.', 'to get rid of unwanted materials properly'],
  ['produce waste', 'tạo ra rác thải', 'Households produce a huge amount of waste every year.', 'to create unwanted material as a result of an activity'],
  ['save energy', 'tiết kiệm năng lượng', 'Turning off lights when not needed helps save energy.', 'to use less power or fuel'],
  ['use renewable energy', 'sử dụng năng lượng tái tạo', 'More countries are choosing to use renewable energy.', 'to use energy from sources that can be naturally replenished'],
  ['raise environmental awareness', 'nâng cao nhận thức về môi trường', 'Schools are working to raise environmental awareness among students.', 'to help more people understand and care about environmental issues'],
  ['take action', 'hành động', 'Governments must take action to address climate change.', 'to do something in order to achieve a result'],
  ['take measures', 'thực hiện các biện pháp', 'The city has taken measures to reduce traffic pollution.', 'to carry out specific actions to achieve a goal'],
  ['tackle climate change', 'giải quyết vấn đề biến đổi khí hậu', 'World leaders met to discuss how to tackle climate change.', 'to take action to deal with the problem of climate change'],
  ['combat global warming', 'chống lại hiện tượng nóng lên toàn cầu', 'Renewable energy is one way to combat global warming.', 'to take action against the rise in global temperatures'],
  ['be responsible for', 'chịu trách nhiệm về/gây ra', 'Human activity is largely responsible for climate change.', 'to be the cause of something, especially something negative'],
  ['be harmful to', 'có hại cho', 'Plastic waste is harmful to marine life.', 'to cause damage or harm to something'],
  ['be beneficial to', 'có lợi cho', 'Planting trees is beneficial to the environment.', 'to be helpful or good for something'],
  ['have an impact on', 'có ảnh hưởng đến', 'Pollution has a huge impact on public health.', 'to cause an effect on something'],
  ['pose a threat to', 'đe dọa', 'Rising sea levels pose a threat to coastal cities.', 'to be a possible source of danger to something'],
  ['be at risk of extinction', 'có nguy cơ tuyệt chủng', 'Many marine species are at risk of extinction.', 'to be in danger of dying out completely'],
  ['be threatened with extinction', 'bị đe dọa tuyệt chủng', 'The panda was once threatened with extinction.', 'to be in danger of dying out completely'],
  ['a major environmental issue', 'một vấn đề môi trường lớn', 'Plastic pollution is a major environmental issue today.', 'an important problem affecting the natural world'],
  ['a serious threat', 'một mối đe dọa nghiêm trọng', 'Climate change poses a serious threat to coastal communities.', 'a significant danger or risk'],
  ['environmentally friendly', 'thân thiện với môi trường', 'The company now uses environmentally friendly packaging.', 'not harmful to the natural environment'],
  ['environmentally sustainable', 'bền vững về môi trường', 'The city aims to become environmentally sustainable by 2040.', 'able to continue without causing long-term damage to the environment'],
  ['protect future generations', 'bảo vệ các thế hệ tương lai', 'We must act now to protect future generations.', 'to take action to keep people who will live in the future safe'],
];

// ── Unit 6: Globalisation ────────────────────────────────────────────────
const unit6 = [
  ['globalisation', 'toàn cầu hóa', 'Globalisation has made it easier for businesses to trade internationally.', 'the process by which the world becomes more interconnected through trade and culture'],
  ['global economy', 'nền kinh tế toàn cầu', 'The global economy was badly affected by the crisis.', 'the economy of the whole world, seen as a single connected system'],
  ['global market', 'thị trường toàn cầu', 'The company sells its products in the global market.', 'the worldwide system of trade and commerce'],
  ['international trade', 'thương mại quốc tế', 'International trade has increased rapidly over the past decades.', 'the exchange of goods and services between countries'],
  ['international business', 'kinh doanh quốc tế', 'She studied international business at university.', 'business activities that take place across national borders'],
  ['multinational company', 'công ty đa quốc gia', 'He works for a multinational company with offices in ten countries.', 'a company that operates in more than one country'],
  ['developing country', 'nước đang phát triển', 'Many developing countries rely heavily on agriculture.', 'a country with a less developed economy and infrastructure'],
  ['developed country', 'nước phát triển', 'Developed countries often have higher living standards.', 'a country with an advanced economy and infrastructure'],
  ['economic development', 'phát triển kinh tế', 'Investment in education supports long-term economic development.', 'the process of improving a country\'s economy and living standards'],
  ['economic growth', 'tăng trưởng kinh tế', 'The country has seen strong economic growth this year.', 'an increase in the amount of goods and services a country produces'],
  ['economic opportunity', 'cơ hội kinh tế', 'The new factory created economic opportunity for local residents.', 'a chance to improve one\'s financial situation'],
  ['living standards', 'mức sống', 'Living standards have improved significantly in recent decades.', 'the level of comfort and wealth available to a person or group'],
  ['standard of living', 'mức sống', 'The standard of living in the city is higher than in rural areas.', 'the level of comfort and wealth available to a person or group'],
  ['labour market', 'thị trường lao động', 'The labour market has become more competitive in recent years.', 'the system where workers find jobs and employers find workers'],
  ['workforce', 'lực lượng lao động', 'Technology has changed the skills needed in today\'s workforce.', 'all the people who work in a country, company or industry'],
  ['employment', 'việc làm', 'The new factory created hundreds of jobs and boosted local employment.', 'the state of having paid work'],
  ['unemployment', 'thất nghiệp', 'Unemployment rose sharply during the recession.', 'the state of not having a paid job'],
  ['income', 'thu nhập', 'Her monthly income covers all of her living expenses.', 'the money a person or country earns'],
  ['wages', 'tiền lương', 'Factory workers are paid weekly wages.', 'payment made for work, usually calculated by the hour or week'],
  ['consumer', 'người tiêu dùng', 'Consumers now have access to products from all over the world.', 'a person who buys goods or services'],
  ['consumer goods', 'hàng tiêu dùng', 'The store sells a wide range of consumer goods.', 'products bought by individuals for personal use'],
  ['local business', 'doanh nghiệp địa phương', 'Large supermarkets can make it hard for local businesses to survive.', 'a business that operates within a particular area'],
  ['foreign investment', 'đầu tư nước ngoài', 'Foreign investment has helped boost the country\'s economy.', 'money invested in a country by people or companies from another country'],
  ['foreign company', 'công ty nước ngoài', 'The factory is owned by a foreign company.', 'a company based in a different country'],
  ['international organisation', 'tổ chức quốc tế', 'The United Nations is a well-known international organisation.', 'an organisation that operates across multiple countries'],
  ['cultural exchange', 'trao đổi văn hóa', 'The programme promotes cultural exchange between students from different countries.', 'the sharing of ideas, customs and traditions between different cultures'],
  ['cultural diversity', 'đa dạng văn hóa', 'The city is known for its cultural diversity.', 'the existence of many different cultures within a society'],
  ['cultural identity', 'bản sắc văn hóa', 'Some people worry that globalisation threatens cultural identity.', 'the sense of belonging to a particular culture'],
  ['cultural differences', 'khác biệt văn hóa', 'Understanding cultural differences is important when travelling.', 'the ways in which different cultures vary from one another'],
  ['national identity', 'bản sắc quốc gia', 'Language plays an important role in national identity.', 'a sense of belonging to a particular nation'],
  ['western culture', 'văn hóa phương Tây', 'Western culture has had a strong influence on fashion worldwide.', 'the customs and traditions typical of Western countries'],
  ['local culture', 'văn hóa địa phương', 'Homestays are a great way to learn about local culture.', 'the customs and traditions of a particular place'],
  ['global culture', 'văn hóa toàn cầu', 'Some argue that a shared global culture is emerging.', 'a set of customs and values shared across many countries'],
  ['migration', 'sự di cư', 'Migration to cities has increased rapidly in recent decades.', 'the movement of people from one place to another to live'],
  ['immigration', 'nhập cư', 'Immigration has shaped the culture of many major cities.', 'the process of coming to live permanently in a foreign country'],
  ['immigrant', 'người nhập cư', 'The city has welcomed many immigrants over the years.', 'a person who comes to live permanently in a foreign country'],
  ['migrant', 'người di cư', 'Many migrants move to cities in search of work.', 'a person who moves from one place to another, often for work'],
  ['migration patterns', 'xu hướng di cư', 'Climate change is affecting global migration patterns.', 'the general trends in how and where people move'],
  ['urbanisation', 'đô thị hóa', 'Rapid urbanisation has led to overcrowding in many cities.', 'the process by which more people come to live in cities'],
  ['population growth', 'gia tăng dân số', 'Population growth is putting pressure on housing and resources.', 'an increase in the number of people living in an area'],
  ['population movement', 'sự di chuyển dân số', 'War often causes large-scale population movement.', 'the movement of large numbers of people from one place to another'],
  ['international cooperation', 'hợp tác quốc tế', 'Tackling climate change requires international cooperation.', 'countries working together to achieve a common goal'],
  ['cross-cultural communication', 'giao tiếp liên văn hóa', 'Cross-cultural communication skills are valuable in global business.', 'communication between people from different cultural backgrounds'],
  ['communicate across cultures', 'giao tiếp giữa các nền văn hóa', 'The training helps employees communicate across cultures effectively.', 'to exchange information successfully with people from other cultures'],
  ['be exposed to', 'được tiếp xúc với', 'Children today are exposed to global culture from a young age.', 'to experience or come into contact with something'],
  ['have access to', 'có quyền/khả năng tiếp cận', 'People now have access to news from around the world instantly.', 'to be able to use or reach something'],
  ['benefit from', 'hưởng lợi từ', 'Small businesses can benefit from access to global markets.', 'to gain an advantage from something'],
  ['contribute to', 'đóng góp vào', 'Tourism contributes significantly to the local economy.', 'to help cause or bring about something'],
  ['lead to', 'dẫn đến', 'Globalisation has led to greater cultural exchange.', 'to result in something happening'],
  ['result in', 'dẫn đến', 'The new policy resulted in higher employment rates.', 'to cause a particular outcome'],
  ['result from', 'bắt nguồn từ', 'Many economic problems result from a lack of investment.', 'to be caused by something'],
  ['depend on', 'phụ thuộc vào', 'The country\'s economy depends heavily on exports.', 'to rely on something or someone'],
  ['compete with', 'cạnh tranh với', 'Local businesses often struggle to compete with large corporations.', 'to try to be more successful than another person or company'],
  ['adapt to', 'thích nghi với', 'Companies must adapt to changing market conditions.', 'to adjust to new conditions or circumstances'],
  ['take advantage of', 'tận dụng', 'Businesses can take advantage of new markets abroad.', 'to make good use of an opportunity'],
  ['create opportunities', 'tạo ra cơ hội', 'Globalisation has created opportunities for international careers.', 'to make new chances for success or advancement'],
  ['create jobs', 'tạo việc làm', 'The new factory will create thousands of jobs.', 'to generate new employment opportunities'],
  ['increase employment', 'tăng việc làm', 'The government hopes the policy will increase employment.', 'to raise the number of people who have paid work'],
  ['boost the economy', 'thúc đẩy nền kinh tế', 'Tourism helps boost the local economy.', 'to help an economy grow stronger'],
  ['promote economic growth', 'thúc đẩy tăng trưởng kinh tế', 'The government introduced policies to promote economic growth.', 'to encourage an increase in a country\'s economic activity'],
  ['improve living standards', 'cải thiện mức sống', 'Economic development has helped improve living standards.', 'to make people\'s quality of life better'],
  ['reduce poverty', 'giảm nghèo', 'Education plays a key role in reducing poverty.', 'to lower the number of people living without enough money'],
  ['increase inequality', 'gia tăng bất bình đẳng', 'Some argue that globalisation can increase inequality.', 'to widen the gap between rich and poor'],
  ['create a wider gap', 'tạo ra khoảng cách lớn hơn', 'Unequal access to technology can create a wider gap between groups.', 'to make the difference between two groups larger'],
  ['preserve cultural identity', 'bảo tồn bản sắc văn hóa', 'Some communities work hard to preserve their cultural identity.', 'to protect and maintain the traditions of a particular culture'],
  ['promote cultural exchange', 'thúc đẩy giao lưu văn hóa', 'Student exchange programmes promote cultural exchange.', 'to encourage the sharing of ideas and traditions between cultures'],
  ['embrace cultural diversity', 'đón nhận sự đa dạng văn hóa', 'The school encourages students to embrace cultural diversity.', 'to welcome and accept the variety of cultures within a society'],
  ['have a significant impact on', 'có ảnh hưởng đáng kể đến', 'Globalisation has had a significant impact on local industries.', 'to cause a large and noticeable effect on something'],
  ['bring people closer together', 'đưa con người đến gần nhau hơn', 'Technology has helped bring people closer together across the world.', 'to help people feel more connected to one another'],
  ['a wide range of products', 'nhiều loại sản phẩm', 'The supermarket offers a wide range of products from around the world.', 'a large variety of different goods'],
  ['a major advantage', 'một lợi thế lớn', 'Speaking multiple languages is a major advantage in global business.', 'a significant benefit'],
  ['a potential disadvantage', 'một bất lợi tiềm tàng', 'Job loss is a potential disadvantage of automation.', 'a possible negative effect'],
  ['economic inequality', 'bất bình đẳng kinh tế', 'Economic inequality remains a major challenge worldwide.', 'an unequal distribution of income or wealth between people'],
  ['cultural homogenisation', 'sự đồng nhất hóa văn hóa', 'Some fear that globalisation leads to cultural homogenisation.', 'the process by which cultures become more similar to one another'],
];

// ── Unit 7: Society ───────────────────────────────────────────────────────
const unit7 = [
  ['society', 'xã hội', 'Technology has changed society in many ways.', 'a large group of people living together in an organised community'],
  ['social issue', 'vấn đề xã hội', 'Homelessness is a serious social issue in many cities.', 'a problem that affects many people within a society'],
  ['social problem', 'vấn đề xã hội', 'Unemployment is a major social problem in the region.', 'a difficulty that affects a large number of people in society'],
  ['social change', 'thay đổi xã hội', 'Social change often happens slowly over generations.', 'a shift in society\'s attitudes, behaviour or structure'],
  ['social development', 'phát triển xã hội', 'The country has made progress in social development.', 'improvement in the well-being and structure of society'],
  ['social responsibility', 'trách nhiệm xã hội', 'Many companies now focus on social responsibility.', 'the duty of individuals or organisations to act for the benefit of society'],
  ['social class', 'tầng lớp xã hội', 'People from different social classes often have different opportunities.', 'a group of people with a similar economic and social position'],
  ['community', 'cộng đồng', 'The festival brought the whole community together.', 'a group of people living in the same area or sharing common interests'],
  ['local community', 'cộng đồng địa phương', 'The charity supports the local community with food and shelter.', 'the people living in a particular area'],
  ['neighbourhood', 'khu dân cư', 'It\'s a quiet neighbourhood with friendly residents.', 'a district or area within a town or city'],
  ['citizen', 'công dân', 'Every citizen has the right to vote.', 'a legally recognised member of a country'],
  ['population', 'dân số', 'The city\'s population has grown rapidly in recent years.', 'the number of people living in a particular area'],
  ['generation', 'thế hệ', 'Each generation faces different challenges.', 'all the people born and living at about the same time'],
  ['younger generation', 'thế hệ trẻ', 'The younger generation is more comfortable with technology.', 'people who are young compared to an older group'],
  ['older generation', 'thế hệ lớn tuổi', 'The older generation often values face-to-face communication more.', 'people who are older compared to a younger group'],
  ['family structure', 'cấu trúc gia đình', 'Family structure has changed significantly over the past century.', 'the way a family is organised, e.g. who lives together'],
  ['nuclear family', 'gia đình hạt nhân', 'A nuclear family usually consists of parents and their children.', 'a family unit made up of parents and their children only'],
  ['extended family', 'gia đình nhiều thế hệ', 'She grew up in a house full of extended family.', 'a family including relatives beyond parents and children, e.g. grandparents'],
  ['household', 'hộ gia đình', 'The average household has around four people.', 'a group of people, usually a family, living together in one home'],
  ['parenting', 'việc nuôi dạy con cái', 'Modern parenting looks very different from a generation ago.', 'the process of raising and caring for children'],
  ['childcare', 'chăm sóc trẻ em', 'Affordable childcare allows more parents to return to work.', 'the care of children, especially while parents are at work'],
  ['elderly people', 'người cao tuổi', 'The community centre offers activities for elderly people.', 'people who are old, especially those over retirement age'],
  ['young people', 'người trẻ', 'Young people today face a very competitive job market.', 'people who are young, especially teenagers and young adults'],
  ['peer pressure', 'áp lực từ bạn bè đồng trang lứa', 'Peer pressure can influence teenagers\' decisions.', 'the influence from people of a similar age to act in a certain way'],
  ['social pressure', 'áp lực xã hội', 'She felt social pressure to follow the latest trends.', 'the influence from society to behave or think in a certain way'],
  ['gender equality', 'bình đẳng giới', 'The company promotes gender equality in the workplace.', 'the state of men and women having equal rights and opportunities'],
  ['gender roles', 'vai trò giới', 'Traditional gender roles are changing in many societies.', 'the behaviours and responsibilities expected of men and women'],
  ['equal opportunities', 'cơ hội bình đẳng', 'The organisation works to provide equal opportunities for all.', 'the same chances for everyone, regardless of background'],
  ['discrimination', 'sự phân biệt đối xử', 'The law protects workers from discrimination.', 'unfair treatment of a person based on race, gender or other factors'],
  ['poverty', 'nghèo đói', 'Education can help reduce poverty in the long term.', 'the state of being extremely poor'],
  ['wealth', 'sự giàu có/tài sản', 'The country\'s wealth comes mainly from natural resources.', 'a large amount of money or valuable possessions'],
  ['wealth gap', 'khoảng cách giàu nghèo', 'The wealth gap between rich and poor continues to widen.', 'the difference in wealth between rich and poor people'],
  ['income inequality', 'bất bình đẳng thu nhập', 'Income inequality remains a major challenge in many countries.', 'an unequal distribution of income among people'],
  ['homelessness', 'tình trạng vô gia cư', 'The city launched a programme to reduce homelessness.', 'the state of having no home'],
  ['crime', 'tội phạm', 'Crime rates have fallen in the city centre.', 'illegal activity or acts'],
  ['criminal behaviour', 'hành vi phạm tội', 'Poverty is sometimes linked to criminal behaviour.', 'behaviour that breaks the law'],
  ['crime rate', 'tỷ lệ tội phạm', 'The crime rate has dropped significantly this year.', 'the number of crimes committed in a particular area or period'],
  ['law', 'luật pháp', 'Everyone must obey the law.', 'the system of rules a society enforces'],
  ['law enforcement', 'thực thi pháp luật', 'Law enforcement has increased in the city centre.', 'the activity of making sure people obey the law'],
  ['government policy', 'chính sách chính phủ', 'The new government policy aims to reduce unemployment.', 'a plan of action decided by a government'],
  ['public services', 'dịch vụ công', 'Public services such as healthcare and education need more funding.', 'services provided by the government for everyone, e.g. healthcare'],
  ['healthcare', 'chăm sóc sức khỏe', 'Access to good healthcare is essential for a healthy society.', 'services provided to maintain or improve people\'s health'],
  ['education system', 'hệ thống giáo dục', 'The education system has undergone major reforms.', 'the way education is organised and delivered in a country'],
  ['social welfare', 'phúc lợi xã hội', 'The government provides social welfare for people in need.', 'financial and other support provided to help people in need'],
  ['volunteer', 'tình nguyện viên', 'She works as a volunteer at the local hospital.', 'a person who does work without being paid'],
  ['voluntary work', 'công việc tình nguyện', 'He does voluntary work at a homeless shelter every weekend.', 'work done without payment, usually to help others'],
  ['charity', 'tổ chức từ thiện', 'The charity provides food and shelter to those in need.', 'an organisation that helps people in need'],
  ['donate', 'quyên góp', 'They donated clothes and food to the local shelter.', 'to give money or goods to help a person or cause'],
  ['support a community', 'hỗ trợ cộng đồng', 'The programme was created to support the local community.', 'to help a group of people in a particular area'],
  ['help those in need', 'giúp đỡ những người cần giúp đỡ', 'The charity was set up to help those in need.', 'to assist people who are struggling or lacking basic necessities'],
  ['take responsibility for', 'chịu trách nhiệm về', 'Everyone should take responsibility for reducing waste.', 'to accept that something is your duty or fault'],
  ['make a contribution to', 'đóng góp cho', 'Volunteers make a valuable contribution to the community.', 'to give something, such as time or money, to help a cause'],
  ['play a role in', 'đóng vai trò trong', 'Schools play a role in shaping young people\'s values.', 'to be involved in or contribute to something'],
  ['have a responsibility to', 'có trách nhiệm làm gì', 'Governments have a responsibility to protect vulnerable citizens.', 'to have a duty to do something'],
  ['raise awareness of', 'nâng cao nhận thức về', 'The campaign aims to raise awareness of mental health issues.', 'to help more people understand and know about an issue'],
  ['address a problem', 'giải quyết một vấn đề', 'The government is working to address the housing problem.', 'to take action to deal with a problem'],
  ['tackle a problem', 'giải quyết một vấn đề', 'New policies were introduced to tackle unemployment.', 'to make a determined effort to deal with a difficult problem'],
  ['solve a problem', 'giải quyết một vấn đề', 'Community programmes can help solve local problems.', 'to find an answer to a problem'],
  ['reduce inequality', 'giảm bất bình đẳng', 'Fairer taxation could help reduce inequality.', 'to lower the gap in wealth or opportunity between groups'],
  ['provide equal opportunities', 'cung cấp cơ hội bình đẳng', 'Schools should provide equal opportunities for all students.', 'to give everyone the same chances, regardless of background'],
  ['protect vulnerable people', 'bảo vệ những người dễ bị tổn thương', 'The policy aims to protect vulnerable people in society.', 'to keep people who are at risk of harm safe'],
  ['provide financial support', 'cung cấp hỗ trợ tài chính', 'The government provides financial support to low-income families.', 'to give money to help someone in need'],
  ['improve social welfare', 'cải thiện phúc lợi xã hội', 'New policies were introduced to improve social welfare.', 'to make support systems for people in need better'],
  ['strengthen communities', 'củng cố cộng đồng', 'Local events help strengthen communities.', 'to make the bonds between people in a community stronger'],
  ['promote social equality', 'thúc đẩy bình đẳng xã hội', 'The organisation works to promote social equality.', 'to encourage fair treatment and opportunities for everyone'],
  ['prevent crime', 'ngăn chặn tội phạm', 'Better street lighting can help prevent crime.', 'to stop illegal activity from happening'],
  ['reduce the crime rate', 'giảm tỷ lệ tội phạm', 'Community policing has helped reduce the crime rate.', 'to lower the number of crimes committed in an area'],
  ['commit a crime', 'phạm tội', 'The suspect was accused of committing a crime.', 'to carry out an illegal act'],
  ['break the law', 'vi phạm pháp luật', 'People who break the law can face serious consequences.', 'to do something illegal'],
  ['follow the law', 'tuân thủ pháp luật', 'Most citizens follow the law without any issue.', 'to obey the legal rules of a country'],
  ['obey the rules', 'tuân thủ các quy định', 'Students are expected to obey the school rules.', 'to follow instructions or regulations'],
  ['have a positive effect on', 'có tác động tích cực đến', 'Volunteering can have a positive effect on mental health.', 'to cause a good change in something'],
  ['have a negative effect on', 'có tác động tiêu cực đến', 'Poverty can have a negative effect on children\'s education.', 'to cause a harmful change in something'],
  ['a serious social issue', 'một vấn đề xã hội nghiêm trọng', 'Homelessness remains a serious social issue in many cities.', 'an important problem that affects a large part of society'],
  ['a growing problem', 'một vấn đề ngày càng gia tăng', 'Traffic congestion is a growing problem in the city.', 'a problem that is becoming more serious over time'],
  ['a sense of community', 'ý thức tinh thần cộng đồng', 'The festival helped create a strong sense of community.', 'a feeling of belonging and connection with others in a group'],
];

// ── Unit 8: The Future ───────────────────────────────────────────────────
const unit8 = [
  ['the future', 'tương lai', 'No one can predict the future with certainty.', 'the period of time that is yet to come'],
  ['future generation', 'thế hệ tương lai', 'We must protect the environment for future generations.', 'people who will be born and live after us'],
  ['future development', 'sự phát triển trong tương lai', 'The plan takes future development of the city into account.', 'growth or progress that will happen later'],
  ['future prospects', 'triển vọng tương lai', 'A university degree can improve your future prospects.', 'the likely chances of success in the future'],
  ['long-term', 'dài hạn', 'The company is focused on long-term growth.', 'relating to a period extending far into the future'],
  ['short-term', 'ngắn hạn', 'The plan addresses short-term needs first.', 'relating to a period covering only the near future'],
  ['long-term plan', 'kế hoạch dài hạn', 'The government announced a long-term plan for renewable energy.', 'a plan designed to be carried out over many years'],
  ['short-term goal', 'mục tiêu ngắn hạn', 'Her short-term goal is to finish the course by June.', 'an aim that can be achieved in the near future'],
  ['prediction', 'dự đoán', 'His prediction about the market turned out to be correct.', 'a statement about what will happen in the future'],
  ['forecast', 'dự báo', 'The weather forecast predicts rain tomorrow.', 'a statement about what is likely to happen, based on current information'],
  ['possibility', 'khả năng', 'There\'s a possibility that the meeting will be postponed.', 'a chance that something might happen'],
  ['probability', 'xác suất/khả năng xảy ra', 'The probability of success increases with more preparation.', 'the likelihood that something will happen'],
  ['expectation', 'sự kỳ vọng', 'The results did not meet expectations.', 'a strong belief that something will happen'],
  ['trend', 'xu hướng', 'There\'s a growing trend towards remote working.', 'a general direction in which something is developing'],
  ['future trend', 'xu hướng tương lai', 'Experts discussed future trends in technology.', 'a direction of change that is expected to continue'],
  ['potential', 'tiềm năng', 'The young player has a lot of potential.', 'the ability to develop or achieve something in the future'],
  ['potential problem', 'vấn đề tiềm ẩn', 'The engineers identified a potential problem with the design.', 'a problem that might happen but has not happened yet'],
  ['potential solution', 'giải pháp tiềm năng', 'Solar power is a potential solution to rising energy costs.', 'a possible way of solving a problem'],
  ['opportunity', 'cơ hội', 'Studying abroad gave her a great opportunity to grow.', 'a chance to do something beneficial'],
  ['challenge', 'thách thức', 'Climate change is one of the biggest challenges we face.', 'a difficult task or situation that tests one\'s abilities'],
  ['innovation', 'sự đổi mới', 'The company is known for its innovation in renewable energy.', 'a new idea, method or invention'],
  ['technological innovation', 'đổi mới công nghệ', 'Technological innovation continues to transform daily life.', 'the creation and development of new technology'],
  ['scientific development', 'phát triển khoa học', 'Scientific development has led to major medical breakthroughs.', 'progress made in scientific knowledge and technology'],
  ['scientific research', 'nghiên cứu khoa học', 'Scientific research is essential for finding new treatments.', 'systematic study carried out to discover new knowledge'],
  ['artificial intelligence', 'trí tuệ nhân tạo', 'Artificial intelligence is being used in many industries today.', 'computer systems able to perform tasks that normally require human intelligence'],
  ['automation', 'tự động hóa', 'Automation has replaced many manual jobs in factories.', 'the use of machines or computers to do work automatically'],
  ['renewable energy', 'năng lượng tái tạo', 'More countries are investing in renewable energy.', 'energy from sources that can be naturally replenished'],
  ['sustainable development', 'phát triển bền vững', 'Sustainable development balances economic growth with environmental protection.', 'development that meets present needs without harming the future'],
  ['sustainable future', 'tương lai bền vững', 'Renewable energy is key to building a sustainable future.', 'a future in which resources are used without long-term harm'],
  ['population growth', 'gia tăng dân số', 'Population growth is putting pressure on housing and resources.', 'an increase in the number of people living in an area'],
  ['population ageing', 'già hóa dân số', 'Population ageing is a major concern in many developed countries.', 'the increasing proportion of older people within a population'],
  ['climate change', 'biến đổi khí hậu', 'Climate change is causing more extreme weather events.', 'long-term changes in temperature and weather patterns'],
  ['global warming', 'nóng lên toàn cầu', 'Global warming is causing ice caps to melt.', 'the gradual increase in the Earth\'s average temperature'],
  ['natural resources', 'tài nguyên thiên nhiên', 'The country is rich in natural resources such as oil and minerals.', 'materials found in nature that are useful to people'],
  ['energy consumption', 'mức tiêu thụ năng lượng', 'Energy consumption rises sharply during the winter months.', 'the amount of energy used'],
  ['energy production', 'sản xuất năng lượng', 'The country is increasing its renewable energy production.', 'the process of generating energy'],
  ['urban development', 'phát triển đô thị', 'Urban development has transformed the city skyline.', 'the growth and construction of buildings and infrastructure in cities'],
  ['smart city', 'thành phố thông minh', 'The government plans to turn the capital into a smart city.', 'a city that uses technology to improve services and quality of life'],
  ['make a prediction', 'đưa ra dự đoán', 'Scientists made a prediction about future sea levels.', 'to say what one thinks will happen in the future'],
  ['predict the future', 'dự đoán tương lai', 'No one can predict the future with complete accuracy.', 'to say what will happen before it happens'],
  ['plan for the future', 'lên kế hoạch cho tương lai', 'It\'s important to plan for the future financially.', 'to make arrangements for events that will happen later'],
  ['prepare for the future', 'chuẩn bị cho tương lai', 'Schools should help students prepare for the future.', 'to get ready for what will happen later'],
  ['look ahead', 'hướng tới tương lai', 'It\'s important to look ahead and set long-term goals.', 'to think about and plan for the future'],
  ['adapt to change', 'thích nghi với sự thay đổi', 'Businesses must adapt to change to remain competitive.', 'to adjust one\'s behaviour to new conditions'],
  ['keep up with change', 'theo kịp sự thay đổi', 'It can be difficult to keep up with change in fast-moving industries.', 'to stay updated with new developments'],
  ['respond to change', 'ứng phó với sự thay đổi', 'Companies need to respond to change quickly to survive.', 'to react appropriately to new circumstances'],
  ['embrace change', 'đón nhận sự thay đổi', 'Successful companies tend to embrace change rather than resist it.', 'to accept and welcome new circumstances'],
  ['face a challenge', 'đối mặt với thách thức', 'The city faces a challenge in reducing traffic congestion.', 'to be confronted with a difficult situation'],
  ['overcome a challenge', 'vượt qua thách thức', 'The team worked together to overcome the challenge.', 'to succeed in dealing with a difficult situation'],
  ['take advantage of an opportunity', 'tận dụng cơ hội', 'She took advantage of the opportunity to study abroad.', 'to make good use of a favourable situation'],
  ['create new opportunities', 'tạo ra những cơ hội mới', 'New technology can create new opportunities for small businesses.', 'to make new chances for success or advancement possible'],
  ['make progress', 'đạt được tiến bộ', 'Scientists have made progress in developing new vaccines.', 'to improve or move forward gradually'],
  ['make an improvement', 'tạo ra sự cải thiện', 'The new policy made a real improvement to public transport.', 'to make something better than before'],
  ['bring about change', 'tạo ra sự thay đổi', 'Education can bring about lasting social change.', 'to cause something to happen or develop'],
  ['lead to change', 'dẫn đến sự thay đổi', 'Public pressure often leads to change in government policy.', 'to result in something being different'],
  ['have an impact on the future', 'có ảnh hưởng đến tương lai', 'Today\'s decisions will have an impact on the future.', 'to cause an effect on what happens later'],
  ['shape the future', 'định hình tương lai', 'Young people today will shape the future of technology.', 'to strongly influence how something will develop'],
  ['transform the way we live', 'thay đổi cách chúng ta sống', 'Smartphones have transformed the way we live.', 'to completely change people\'s everyday habits and lifestyle'],
  ['improve people\'s lives', 'cải thiện cuộc sống con người', 'Access to clean water can greatly improve people\'s lives.', 'to make people\'s everyday experience better'],
  ['reduce our dependence on', 'giảm sự phụ thuộc vào', 'Renewable energy can reduce our dependence on fossil fuels.', 'to lower how much we rely on something'],
  ['find a solution to', 'tìm giải pháp cho', 'Scientists are working to find a solution to plastic pollution.', 'to discover a way of solving a problem'],
  ['deal with a problem', 'giải quyết một vấn đề', 'The government must deal with the housing problem urgently.', 'to handle or manage a difficult situation'],
  ['tackle future challenges', 'giải quyết những thách thức trong tương lai', 'Investment in education helps us tackle future challenges.', 'to take action to deal with difficulties that lie ahead'],
  ['meet future needs', 'đáp ứng nhu cầu tương lai', 'The city is expanding its infrastructure to meet future needs.', 'to satisfy the requirements that will arise later'],
  ['ensure a sustainable future', 'đảm bảo một tương lai bền vững', 'We must act now to ensure a sustainable future.', 'to make certain that future generations can live without long-term harm'],
  ['protect future generations', 'bảo vệ các thế hệ tương lai', 'We must act now to protect future generations.', 'to take action to keep people who will live in the future safe'],
  ['be likely to', 'có khả năng', 'Prices are likely to rise next year.', 'to be expected or probable'],
  ['be unlikely to', 'khó có khả năng', 'It is unlikely to rain this weekend.', 'to be improbable or not expected'],
  ['be expected to', 'được dự đoán sẽ', 'The economy is expected to grow next year.', 'to be predicted or anticipated to happen'],
  ['be predicted to', 'được dự đoán sẽ', 'Sea levels are predicted to rise over the coming decades.', 'to be forecast to happen'],
  ['be expected to increase', 'được dự kiến sẽ tăng', 'Demand for renewable energy is expected to increase.', 'to be predicted to become larger in amount'],
  ['be expected to decline', 'được dự kiến sẽ giảm', 'The population of the region is expected to decline.', 'to be predicted to become smaller in amount'],
  ['in the near future', 'trong tương lai gần', 'The company plans to expand in the near future.', 'happening soon, within a short period of time'],
  ['in the long term', 'về lâu dài', 'The investment will pay off in the long term.', 'over an extended period of time in the future'],
  ['over the next few decades', 'trong vài thập kỷ tới', 'Cities are expected to grow rapidly over the next few decades.', 'during the period covering the next 20-30 years'],
  ['in the years to come', 'trong những năm tới', 'Technology will continue to evolve in the years to come.', 'in the future, over the coming years'],
];

const lessons = [
  {
    title: 'Mindset 1 Unit 1-2',
    description: 'Education · Lifestyle — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 15,
    words: dedupeWords([...unit1, ...unit2]),
  },
  {
    title: 'Mindset 1 Unit 3-4',
    description: 'Travel · Technology — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 16,
    words: dedupeWords([...unit3, ...unit4]),
  },
  {
    title: 'Mindset 1 Unit 5-6',
    description: 'The Natural World · Globalisation — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 17,
    words: dedupeWords([...unit5, ...unit6]),
  },
  {
    title: 'Mindset 1 Unit 7-8',
    description: 'Society · The Future — từ vựng & cụm từ tự nhiên hay dùng trong IELTS Speaking/Writing',
    difficulty: 'B1',
    order: 18,
    words: dedupeWords([...unit7, ...unit8]),
  },
];

function toWordDoc([word, meaning, example, definition]) {
  return { word, meaning, example, definition, ipa: '', partOfSpeech: '', collocations: [], distractors: [] };
}

// A handful of general phrases can recur across adjacent units' own source
// lists — drop later repeats so a single lesson never quizzes the same
// word twice.
function dedupeWords(entries) {
  const seen = new Set();
  return entries.filter(([word]) => {
    const key = word.trim().toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

async function runSeed() {
  const VocabularyLesson = require('../models/VocabularyLesson');
  const User = require('../models/User');

  const admin = await User.findOne({ email: ADMIN_EMAIL }).select('_id').lean();
  if (!admin) throw new Error(`Admin user not found: ${ADMIN_EMAIL}`);

  for (const lesson of lessons) {
    const existing = await VocabularyLesson.findOne({ title: lesson.title }).lean();
    if (existing) {
      console.log(`[SeedVocabMindset1] "${lesson.title}" already exists (_id=${existing._id}) – skip`);
      continue;
    }
    const doc = await VocabularyLesson.create({
      title: lesson.title,
      description: lesson.description,
      difficulty: lesson.difficulty,
      order: lesson.order,
      targetClass: '',
      published: false, // review before publishing to students
      createdBy: admin._id,
      words: lesson.words.map(toWordDoc),
    });
    console.log(`[SeedVocabMindset1] Inserted "${doc.title}" (_id=${doc._id}, ${doc.words.length} words)`);
  }
}

if (require.main === module) {
  require('dotenv').config();
  const mongoose = require('mongoose');
  (async () => {
    await mongoose.connect(process.env.MONGO_URI);
    try {
      await runSeed();
    } finally {
      await mongoose.disconnect();
    }
  })().catch(e => { console.error('[SeedVocabMindset1] FAILED', e); process.exit(1); });
}

module.exports = { runSeed, lessons };
