// Same approach/format as seedListeningTranscripts.js (Cam 21) — sourced
// from published Cambridge IELTS 17 audioscripts (ieltstrainingonline.com),
// verified sentence by sentence against every question's correctAnswer
// already in the DB before being written here.
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const ListeningTest = require('../models/ListeningTest');
const ListeningSection = require('../models/ListeningSection');
const { sectionTitle } = require('./seedListeningSectionsFromTests');

function fmt(title, turns) {
  const body = turns.map(([speaker, text]) => speaker ? `${speaker}:\n${text}` : text).join('\n');
  return `❓ Transcript\n${title}\n${body}`;
}

const TARGETS = [
  // ══════════════════════════ Cam 17 - Test 1 ══════════════════════════
  {
    testName: 'Cam 17 - Test 1', partNumber: 1,
    transcript: fmt('Buckworth Conservation Group', [
      ['Peter', 'Hello?'],
      ['Jan', "Oh hello. My name's Jan. Are you the right person to talk to about the Buckworth Conservation Group?"],
      ['Peter', "Yes, I'm Peter. I'm the secretary."],
      ['Jan', "Good. I've just moved to this area, and I'm interested in getting involved. I was in a similar group where I used to live. Could you tell me something about your activities, please?"],
      ['Peter', "Of course. Well, we have a mixture of regular activities and special events. One of the regular ones is trying to keep the beach free of litter. A few of us spend a couple of hours a month on it, and it's awful how much there is so clear. I wish people would be more responsible and take it home with them."],
      ['Jan', "I totally agree. I'd be happy to help with that. Is it OK to take dogs?"],
      ['Peter', "I'm afraid not, as they're banned from the beach itself. You can take them along the cliffs, though. And children are welcome."],
      ['Jan', 'Right.'],
      ['Peter', "We also manage a nature reserve, and there's a lot to do there all year round. For example, because it's a popular place to visit, we spend a lot of time looking after the paths and making sure they're in good condition for walking."],
      ['Jan', 'I could certainly help with that.'],
      ['Peter', "Good. And we have a programme of creating new habitats there. We're just finished making and installing nesting boxes for birds to use, and next we're going to work on encouraging insects – they're important for the biodiversity of the reserve."],
      ['Jan', 'They certainly are.'],
      ['Peter', "Oh, and we're also running a project to identify the different species of butterflies that visit the reserve. You might be interested in taking part in that."],
      ['Jan', "Sure. I was involved in something similar where I used to live, counting all the species of months. I'd enjoy that."],
      ['Peter', "Another job we're doing at the reserve is replacing the wall on the southern side, between the parking area and our woodshed. It was badly damaged in a storm last month."],
      ['Jan', 'OK.'],
      ['Peter', 'Then as I said, we have a programme of events as well, both at the weekend, and during the week.'],
      ['Jan', "Right. I presume you have guided walks? I'd like to get to know the local countryside, as I'm new to the area."],
      ['Peter', "Yes, we do. The next walk is to Ruston Island, a week on Saturday. We'll be meeting in the car park at Dunsmore Beach at low tide – that's when the sands are dry enough for us to walk to the island without getting wet."],
      ['Jan', 'Sounds good.'],
      ['Peter', "The island's a great place to explore. It's quite small, and it's got a range of habitats. It's also an ideal location for seeing seals just off the coast, or even on the beach."],
      ['Jan', 'OK. And is there anything we should bring, like a picnic, for instance?'],
      ['Peter', "Yes, do bring one, as it's a full-day walk. And of course it'll be wet walking across and back, so make sure your boots are waterproof."],
      ['Jan', "I must buy a new pair – there's a hole in one of my current ones! Well, I'd definitely like to come on the walk."],
      ['Peter', 'Great. Then later this month we\'re having a one-day woodwork session in Hopton Wood.'],
      ['Jan', "I've never tried that before. Is it OK for beginners to take part?"],
      ['Peter', "Definitely. There'll be a couple of experts leading the session, and we keep the number of participants down, so you'll get as much help as you need."],
      ['Jan', "Excellent! I'd love to be able to make chairs."],
      ['Peter', "That's probably too ambitious for one day! You'll be starting with wooden spoons, and of course learning how to use the tools. And anything you make is yours to take home with you."],
      ['Jan', 'That sounds like fun. When is it?'],
      ['Peter', "It's on the 17th, from 10 a.m. until 3. There's a charge of £35, including lunch, or £40 if you want to camp in the wood."],
      ['Jan', "I should think I'll come home the same day. Well, I'd certainly like to join the group."],
    ]),
  },
  {
    testName: 'Cam 17 - Test 1', partNumber: 2,
    transcript: fmt('Boat trip round Tasmania', [
      [null, "So, hello everyone. My name's Lou Miller and I'm going to be your tour guide today as we take this fantastic boat trip around the Tasmanian coast. Before we set off, I just want to tell you a few things about our journey."],
      [null, "Our boats aren't huge as you can see. We already have three staff members on board and on top of that, we can transport a further fifteen people – that's you – around the coastline. But please note if there are more than nine people on either side of the boat, we'll move some of you over, otherwise all eighteen of us will end up in the sea!"],
      [null, "We've recently upgraded all our boats. They used to be jet black, but our new ones now have these comfortable dark red seats and a light-green exterior in order to stand out from others and help promote our company. This gives our boats a rather unique appearance, don't you think?"],
      [null, "We offer you a free lunchbox during the trip and we have three types. Lunchbox 1 contains ham and tomato sandwiches. Lunchbox 2 contains a cheddar cheese roll and Lunchbox 3 is salad-based and also contains eggs and tuna. All three lunchboxes also have a packet of crisps and chocolate bar inside. Please let staff know which lunchbox you prefer."],
      [null, "I'm sure I don't have to ask you not to throw anything into the sea. We don't have any bins to put litter in, but Jess, myself or Ray, our other guide, will collect it from you after lunch and put it all in a large plastic sack."],
      [null, "The engine on the boat makes quite a lot of noise so before we head off, let me tell you a few things about what you're going to see."],
      [null, "This area is famous for its ancient lighthouse, which you'll see from the boat as we turn past the first little island. It was built in 1838 to protect sailors as a number of shipwrecks had led to significant loss of life. The construction itself was complicated as some of the original drawings kept by the local council show. It sits right on top of the cliffs in a very isolated spot. In the nineteenth century there were many jobs there, such as polishing the brass lamps, chopping firewood and cleaning windows, that kept lighthouse keepers busy. These workers were mainly prison convicts until the middle of that century when ordinary families willing to live in such circumstances took over."],
      [null, "Some of you have asked me what creatures we can expect to see. I know everyone loves the penguins, but they're very shy and, unfortunately, tend to hide from passing boats, but you might see birds in the distance, such as sea eagles, flying around the cliff edges where they nest. When we get to the rocky area inhabited by fur seals, we'll stop and watch them swimming around the coast. They're inquisitive creatures so don't be surprised if one pops up right in front of you. Their predators, orca whales, hunt along the coastline too, but spotting one of these is rare. Dolphins, on the other hand, can sometimes approach on their own or in groups as they ride the waves beside us."],
      [null, "Lastly, I want to mention the caves. Tasmania is famous for its caves and the ones we'll pass by are so amazing that people are lost for words when they see them. They can only be approached by sea, but if you feel that you want to see more than we're able to show you, then you can take a kayak into the area on another day and one of our staff will give you more information on that. What we'll do is to go through a narrow channel, past some incredible rock formations and from there we'll be able to see the openings to the caves, and at that point we'll talk to you about what lies beyond."],
    ]),
  },
  {
    testName: 'Cam 17 - Test 1', partNumber: 3,
    transcript: fmt('Work experience for veterinary science students', [
      ['Diana', 'So, Tim, we have to do a short summary of our work experience on a farm.'],
      ['Tim', "Right. My farm was great, but arranging the work experience was hard. One problem was it was miles away and I don't drive. And also, I'd really wanted a placement for a month, but I could only get one for two weeks."],
      ['Diana', "I was lucky, the farmer let me stay on the farm so I didn't have to travel. But finding the right sort of farm to apply to wasn't easy."],
      ['Tim', "No, they don't seem to have websites, do they. I found mine through a friend of my mother's, but it wasn't easy."],
      ['Diana', 'No.'],
      ['Tim', "My farm was mostly livestock, especially sheep. I really enjoyed helping out with them. I was up most of one night helping a sheep deliver a lamb …"],
      ['Diana', 'On your own?'],
      ['Tim', "No, the farmer was there, and he told me what to do. It wasn't a straightforward birth, but I managed. It was a great feeling to see the lamb stagger to its feet and start feeding almost straightaway, and to know that it was OK."],
      ['Diana', 'Mm.'],
      ['Tim', 'Then another time a lamb had broken its leg, and they got the vet in to set it, and he talked me through what he was doing. That was really useful.'],
      ['Diana', "Yes, my farm had sheep too. The farm was in a valley and they had a lowland breed called Suffolks, although the farmer said they'd had other breeds in the past."],
      ['Tim', 'So were they bred for their meat?'],
      ['Diana', "Mostly, yes. They're quite big and solid."],
      ['Tim', 'My farm was up in the hills and they had a different breed of sheep, they were Cheviots.'],
      ['Diana', "Oh, I heard their wool's really sought after."],
      ['Tim', "Yes. It's very hardwearing and they use it for carpets."],
      ['Diana', 'Right.'],
      ['Tim', "I was interested in the amount of supplements they add to animals' feed nowadays. Like, even the chickens got extra vitamins and electrolytes in their feed."],
      ['Diana', "Yes, I found that too. And they're not cheap. But my farmer said some are overpriced for what they are. And he didn't give them as a matter of routine, just at times when the chickens seemed to particularly require them."],
      ['Tim', "Yes, mine said the same. He said certain breeds of chickens might need more supplements than the others, but the cheap and expensive ones are all basically the same."],
      ['Diana', 'Mm.'],
      ['Tim', 'So did your farm have any other livestock, Diana?'],
      ['Diana', "Yes, dairy cows. I made a really embarrassing mistake when I was working in the milk shed. Some cows had been treated with antibiotics, so their milk wasn't suitable for human consumption, and it had to be put in a separate container. But I got mixed up, and I poured some milk from the wrong cow in with the milk for humans, so the whole lot had to be thrown away. The farmer wasn't too happy with me."],
      ['Tim', "I asked my farmer how much he depended on the vet to deal with health problems. I'd read reports that the livestock's health is being affected as farmers are under pressure to increase production. Well, he didn't agree with that, but he said that actually some of the stuff the vets do, like minor operations, he'd be quite capable of doing himself."],
      ['Diana', "Yeah. My farmer said the same. But he reckons vets' skills are still needed."],
      ['Diana', "Now we've got to give a bit of feedback about last term's modules – just short comments, apparently. Shall we do that now?"],
      ['Tim', 'OK. So medical terminology.'],
      ['Diana', 'Well, my heart sank when I saw that, especially right at the beginning of the course. And I did struggle with it.'],
      ['Tim', "I'd thought it'd be hard, but actually I found it all quite straightforward. What did you think about diet and nutrition?"],
      ['Diana', 'OK, I suppose.'],
      ['Tim', "Do you remember what they told us about pet food and the fact that there's such limited checking into whether or not it's contaminated? I mean in comparison with the checks on food for humans – I thought that was terrible."],
      ['Diana', "Mm. I think the module that really impressed me was the animal disease one, when we looked at domesticated animals in different parts of the world, like camels and water buffalo and alpaca. The economies of so many countries depend on these, but scientists don't know much about the diseases that affect them."],
      ['Tim', "Yes, I thought they'd know a lot about ways of controlling and eradicating those diseases, but that's not the case at all. I loved the wildlife medication unit. Things like helping birds that have been caught in oil spills. That's something I hadn't thought about before."],
      ['Diana', 'Yeah, I thought I might write my dissertation on something connected with that.'],
      ['Tim', 'Right. So …'],
    ]),
  },
  {
    testName: 'Cam 17 - Test 1', partNumber: 4,
    transcript: fmt('Labyrinths', [
      [null, "Labyrinths have existed for well over 4,000 years. Labyrinths and labyrinthine symbols have been found in regions as diverse as modern-day Turkey, Ireland, Greece, and India. There are various designs of labyrinth but what they all have in common is a winding spiral path which leads to a central area. There is one starting point at the entrance and the goal is to reach the central area. Finding your way through a labyrinth involves many twists and turns, but it's not possible to get lost as there is only one single path."],
      [null, "In modern times, the word labyrinth has taken on a different meaning and is often used as a synonym for a maze. A maze is quite different as it is a kind of puzzle with an intricate network of paths. Mazes became fashionable in the 15th and 16th centuries in Europe, and can still be found in the gardens of great houses and palaces. The paths are usually surrounded by thick, high hedges so that it's not possible to see over them. Entering a maze usually involves getting lost a few times before using logic to work out the pattern and find your way to the centre and then out again. There are lots of dead ends and paths which lead you back to where you started. The word 'maze' is believed to come from a Scandinavian word for a state of confusion. This is where the word 'amazing' comes from."],
      [null, "Labyrinths, on the other hand, have a very different function. Although people now often refer to things they find complicated as labyrinths, this is not how they were seen in the past. the winding spiral of the labyrinth has been used for centuries as a metaphor for life's journey. It served as a spiritual reminder that there is purpose and meaning to our lives and helped to give people a sense of direction. Labyrinths are thought to encourage a feeling of calm and have been used as a meditation and prayer tool in many cultures over many centuries."],
      [null, "The earliest examples of the labyrinth spiral pattern have been found carved into stone, from Sardinia to Scandinavia, from Arizona to India to Africa. In Europe, these spiral carvings date from the late Bronze Age. The Native American Pima tribe wove baskets with a circular labyrinth design that depicted their own cosmology. In Ancient Greece, the labyrinth spiral was used on coins around four thousand years ago. Labyrinths made of mosaics were commonly found in bathhouses, villas and tombs throughout the Roman Empire."],
      [null, "In Northern Europe, there were actual physical labyrinths designed for walking on. These were cut into the turf or grass, usually in a circular pattern. The origin of these walking labyrinths remains unclear, but they were probably used for fertility rites which may date back thousands of years. Eleven examples of turf labyrinths survive today, including the largest one at Saffron Walden, England, which used to have a large tree in the middle of it."],
      [null, "More recently labyrinths have experienced something of a revival. Some believe that walking a labyrinth promotes healing and mindfulness, and there are those who believe in its emotional and physical benefits, which include slower breathing and a restored sense of balance and perspective. This idea has become so popular that labyrinths have been laid into the floors of spas, wellness centres and even prisons in recent years."],
      [null, "A pamphlet at Colorado Children's Hospital informs patients that 'walking a labyrinth can often calm people in the midst of a crisis'. And apparently, it's not only patients who benefit. Many visitors find walking a labyrinth less stressful than sitting in a corridor or waiting room. Some doctors even walk the labyrinth during their breaks. In some hospitals, patients who can't walk can have a paper 'finger labyrinth' brought to their bed. The science behind the theory is a little sketchy, but there are dozens of small-scale studies which support claims about the benefits of labyrinths. For example, one study found that walking a labyrinth provided 'short-term calming, relaxation, and relief from anxiety' for Alzheimer's patients."],
    ]),
  },

  // ══════════════════════════ Cam 17 - Test 2 ══════════════════════════
  {
    testName: 'Cam 17 - Test 2', partNumber: 1,
    transcript: fmt('Voluntary work in Southoe village', [
      ['Jane', 'Hello, Jane Fairbanks speaking.'],
      ['Frank', "Oh, good morning. My name's Frank Pritchard. I've just retired and moved to Southoe. I'd like to become a volunteer, and I gather you co-ordinate voluntary work in the village."],
      ['Jane', "That's right."],
      ['Frank', 'What sort of thing could I do?'],
      ['Jane', "Well, we need help with the village library. We borrow books from the town library, and individuals also donate them. So, one thing you could do is get involved in collecting them – if you've got a car, that is."],
      ['Frank', "Yes, that's no problem."],
      ['Jane', "The times are pretty flexible so we can arrange it to suit you. Another thing is the records that we keep of the books we're given, and those we borrow and need to return to the town library. It would be very useful to have another person to help keep them up to date."],
      ['Frank', "Right. I'm used to working on a computer – I presume they're computerised?"],
      ['Jane', 'Oh yes.'],
      ['Frank', "Is the library purpose-built? I haven't noticed it when I've walked round the village."],
      ['Jane', "No, we simply have the use of a room in the village hall, the West Room. It's on the left as you go in."],
      ['Frank', 'I must go and have a look inside the hall.'],
      ['Jane', "Yes, it's a nice building."],
      ['Frank', 'Do you run a lunch club in the village for elderly people? I know a lot of places do.'],
      ['Jane', 'Yes, we have a very successful club.'],
      ['Frank', "I could help with transport, if that's of any use."],
      ['Jane', "Ooo definitely. People come to the club from neighbouring villages, and we're always in need of more drivers."],
      ['Frank', 'And does the club have groups that focus on a particular hobby, too? I could get involved in one or two, particularly if there are any art groups.'],
      ['Jane', "Excellent. I'll find out where we need help and get back to you."],
      ['Frank', 'Fine. What about help for individual residents. Do you arrange that at all?'],
      ['Jane', "Yes, we do it as a one-off. In fact, there's Mrs Carroll. She needs a lift to the hospital next week, and we're struggling to find someone."],
      ['Frank', "When's her appointment?"],
      ['Jane', 'On Tuesday. It would take the whole morning.'],
      ['Frank', 'I could do that.'],
      ['Jane', "Oh, that would be great. Thank you. And also, next week, we're arranging to have some work done to Mr Selsbury's house before he moves, as he isn't healthy enough to do it himself. We're got some people to decorate his kitchen, but if you could do some weeding in his garden, that would be wonderful."],
      ['Frank', "OK. I'd enjoy that. And presumably the day and time are flexible."],
      ['Jane', "Oh yes. Just say when would suit you best, and we'll let Mr Selsbury know."],
      ['Frank', 'Good.'],
      ['Jane', 'The volunteers group also organises monthly social events, which is a great way to meet other people, of course.'],
      ['Frank', 'Uhuh.'],
      ['Jane', "So next month, on the 19th of October, we're holding a quiz – a couple of residents are great at planning unusual ones, and we always fill the village hall."],
      ['Frank', 'That sounds like fun. Can I do anything to help?'],
      ['Jane', "Well, because of the summer of people, we need plenty of refreshments for halfway through. So, if you could provide any, we'd be grateful."],
      ['Frank', "I'm sure I could. I'll think about what to make, and let you know."],
      ['Jane', "Thank you. Then on November the 18th, we're holding a dance, also in the village hall. We've booked a band that specialises in music of the 1930s – they've been before, and we've had a lot of requests to bring them back."],
      ['Frank', "I'm not really a dancer, but I'd like to do something to help."],
      ['Jane', "Well, we sell tickets in advance, and having an extra person to check them at the door, as people arrive, would be good – it can be quite a bottleneck if everyone arrives at once!"],
      ['Frank', "OK, I'm happy with that."],
      ['Jane', "We're also arranging a New Year's Eve party. We're expecting that to be a really big event, so instead of the village hall, it'll be held in the Mountfort Hotel."],
      ['Frank', 'The …?'],
      ['Jane', "Mountfort. M-O-U-N-T-F-O-R-T Hotel. It isn't in Southoe itself, but it's only a couple of miles away. The hotel will be providing dinner and we've booked a band. The one thing we haven't got yet is a poster. That isn't something you could do, by any chance, is it?"],
      ['Frank', "Well actually, yes. Before I retired I was a graphic designer, so that's right up my street."],
      ['Jane', "Oh perfect! I'll give you the details, and then perhaps you could send me a draft …"],
      ['Frank', 'Of course.'],
    ]),
  },
  {
    testName: 'Cam 17 - Test 2', partNumber: 2,
    transcript: fmt('Oniton Hall', [
      [null, "Good morning, and welcome to Oniton Hall, one of the largest estates in the area. My name's Nick, and I'm one of the guides. I'll give you a brief introduction to the estate while you're sitting down, and then we'll walk round."],
      [null, "The estate consists of the house, gardens, parkland and farm, and it dates back to the fourteenth century. The original house was replaced in the late seventeenth century, and of course it has had a large number of owners. Almost all of them have left their mark, generally by adding new rooms, like the ballroom and conservatory, or by demolishing others. The farm looks much as it's always done, although the current owner has done a great deal of work to the flower beds."],
      [null, "In the seventeenth century, the estate was owned by a very wealthy man called Sir Edward Downes. His intention was to escape from the world of politics, after years as an active politician, and to build a new house worthy of his big collection of books, paintings and sculptures. He broke off contact with his former political allies, and hosted meeting of creative and literary people, like painters and poets. Unusually for his time, he didn't care whether his guests were rich or poor, as long as they had talent."],
      [null, "Big houses like Oniton had dozens of servants until the 1920s or 30s, and we've tried to show what their working lives were like. Photographs of course don't give much of an idea, so instead, as you go round the house, you'll see volunteers dressed up as nineteenth-century servants, going about their work. They'll explain what they're doing, and tell you their recipes, or what tools they're using. We've just introduced this feature to replace the audio guide we used to have available."],
      [null, "I see there are a number of children here with you today. Well, we have several activities specially for children, like dressing up in the sorts of clothes that children wore in the past, and as it's a fine day, some of you will probably want to play in the adventure playground. Our latest addition is child-sized tractors, that you can drive around the grounds."],
      [null, "We'll also be going into the farm that's part of the estate, where there's plenty to do. Most of the buildings date from the eighteenth century, so you can really step back into an agricultural past."],
      [null, "Until recently, the dairy was where milk from the cows was turned into cheese. It's now the place to go for lunch, or afternoon tea, or just a cup of coffee and a slice of homemade cake."],
      [null, "The big stone building that dominates the farm is the large barn, and in here is our collection of agricultural tools. These were used in the past to plough the earth, sow seeds, make gates, and much more."],
      [null, "There's a small barn, also made of stone, where you can groom the donkeys and horses, to keep their coats clean. They really seem to enjoy having it done, and children love grooming them."],
      [null, "The horses no longer live in the stables, which instead is the place to go to buy gifts, books, our own jams and pickles, and clothes and blankets made of wool from our sheep."],
      [null, "Outside the shed, which is the only brick building, you can climb into a horse-drawn carriage for a lovely, relaxing tour of the park and farm. The carriages are well over a hundred years old."],
      [null, "And finally, the parkland, which was laid out in the eighteenth century, with a lake and trees that are now well established. You'll see types of cattle and sheep that are hardly ever found on farms these days. We're helping to preserve them, to stop their numbers falling further."],
      [null, "OK, well if you'd like to come with me …"],
    ]),
  },
  {
    testName: 'Cam 17 - Test 2', partNumber: 3,
    transcript: fmt('Review of Romeo and Juliet', [
      ['Ed', "Did you make notes while you were watching the performances of Romeo and Juliet, Gemma?"],
      ['Gemma', 'Yes, I did. I found it quite hard though. I kept getting too involved in the play.'],
      ['Ed', "Me too. I ended up not taking notes. I wrote down my impressions when I got home. Do you mind if I check a few things with you? In case I've missed anything. And I've also got some questions about our assignment."],
      ['Gemma', "No, it's good to talk things through. I may have missed things too."],
      ['Ed', "OK great. So first of all, I'm not sure how much information we should include in our reviews."],
      ['Gemma', "Right. Well, I don't think we need to describe what happens. Especially as Romeo and Juliet is one of Shakespeare's most well-known plays."],
      ['Ed', "Yeah, everyone knows the story. In an essay we'd focus on the poetry and Shakespeare's use of imagery etc., but that isn't really relevant in a review. We're supposed to focus on how effective this particular production is."],
      ['Gemma', 'Mmm. We should say what made it a success or a failure.'],
      ['Ed', "And part of that means talking about the emotional impact the performance had on us. I think that's important."],
      ['Gemma', "Yes. And we should definitely mention how well the director handled important bits of the play – like when Romeo climbs onto Juliet's balcony."],
      ['Ed', 'And the fight between Mercutio and Tybalt.'],
      ['Gemma', "Yes. It would also be interesting to mention the theatre space and how the director used it but I don't think we'll have space in 800 words."],
      ['Ed', 'No. OK. That all sounds quite straightforward.'],
      ['Ed', "So what about The Emporium Theatre's production of the play?"],
      ['Gemma', 'I thought some things worked really well but there were some problems too.'],
      ['Ed', 'Yeah. What about the set, for example?'],
      ['Gemma', "I think it was visually really stunning. I'd say that was probably the most memorable thing about this production."],
      ['Ed', "You're right. The set design was really amazing, but actually I have seen similar ideas used in other productions."],
      ['Gemma', 'What about the lighting? Some of the scenes were so dimly lit it was quite hard to see.'],
      ['Ed', "I didn't dislike it. It helped to change the mood of the quieter scenes."],
      ['Gemma', "That's a good point."],
      ['Ed', 'What did you think of the costumes?'],
      ['Gemma', 'I was a bit surprised by the contemporary dress, I must say.'],
      ['Ed', "Yeah – I think it worked well, but I had assumed it would be more conventional."],
      ['Gemma', "Me too. I liked the music at the beginning and I thought the musicians were brilliant, but I thought they were wasted because the music didn't have much impact in Acts 2 and 3."],
      ['Ed', "Yes – that was a shame."],
      ['Gemma', "One problem with this production was that the actors didn't deliver the lines that well. They were speaking too fast."],
      ['Ed', "It was a problem I agree, but I thought it was because they weren't speaking loudly enough – especially at key points in the play."],
      ['Gemma', "I actually didn't have a problem with that."],
      ['Ed', "It's been an interesting experience watching different versions of Romeo and Juliet, hasn't it?"],
      ['Gemma', "Definitely. It's made me realise how relevant the play still is."],
      ['Ed', "Right. I mean a lot's changed since Shakespeare's time, but in many ways nothing's changed. There are always disagreements and tension between teenagers and their parents."],
      ['Gemma', "Yes, that's something all young people can relate to – more than the violence and the extreme emotions in the play."],
      ['Ed', 'How did you find watching it in translation?'],
      ['Gemma', "Really interesting. I expected to find it more challenging, but I could follow the story pretty well."],
      ['Ed', "I stopped worrying about not being able to understand all the words and focused on the actors' expressions. The ending was pretty powerful."],
      ['Gemma', 'Yes. That somehow intensified the emotion for me.'],
      ['Ed', "Did you know Shakespeare's been translated into more languages than any other writer?"],
      ['Gemma', "What's the reason for his international appeal, do you think?"],
      ['Ed', "I was reading that it's because his plays are about basic themes that people everywhere are familiar with."],
      ['Gemma', 'Yeah, and they can also be understood on different levels. The characters have such depth.'],
      ['Ed', 'Right – which allows directors to experiment and find new angles.'],
      ['Gemma', "That's really important because …"],
    ]),
  },
  {
    testName: 'Cam 17 - Test 2', partNumber: 4,
    transcript: fmt('The impact of digital technology on the Icelandic language', [
      [null, "Right, everyone, let's make a start. Over the past few sessions, we've been considering the reasons why some world languages are in decline, and today I'm going to introduce another factor that affects languages, and the speakers of those languages, and that's technology and, in particular, digital technology. In order to illustrate its effect, I'm going to focus on the Icelandic language, which is spoken by around 321,000 people, most of whom live in Iceland – an island in the North Atlantic Ocean."],
      [null, "The problem for this language is not the number of speakers – even though this number is small. Nor is it about losing words to other languages, such as English. In fact, the vocabulary of Icelandic is continually increasing because when speakers need a new word for something, they tend to create one, rather than borrowing from another language. All this makes Icelandic quite a special language – it's changed very little in the past millennium, yet it can handle twenty-first-century concepts related to the use of computers and digital technology. Take, for example, the word for web browser … this is vafri in Icelandic, which comes from the verb 'to wander'. I can't think of a more appropriate term because that's exactly what you do mentally when you browse the internet. Then there's an Icelandic word for podcast – which is too hard to pronounce! And so on."],
      [null, "Icelandic, then, is alive and growing, but – and it's a big but – young Icelanders spend a great deal of time in the digital world and this world is predominantly English. Think about smartphones. They didn't even exist until comparatively recently, but today young people use them all the time to read books, watch TV or films, play games, listen to music, and so on. Obviously, this is a good thing in many respects because it promotes their bilingual skills, but the extent of the influence of English in the virtual world is staggering and it's all happening really fast."],
      [null, "For their parents and grandparents, the change is less concerning because they already have their native-speaker skills in Icelandic. But for young speakers – well, the outcome is a little troubling. For example, teachers have found that playground conversations in Icelandic secondary schools can be conducted entirely in English, while teachers of much younger children have reported situations where their classes find it easier to say what is in a picture using English, rather than Icelandic. The very real and worrying consequence of all this is that the young generation in Iceland is at risk of losing its mother tongue."],
      [null, "Of course, this is happening to other European languages too, but while internet companies might be willing to offer, say, French options in their systems, it's much harder for them to justify the expense of doing the same for a language that has a population the size of a French town, such as Nice. The other drawback of Icelandic is the grammar, which is significantly more complex than in most languages. At the moment, the tech giants are simply not interested in tackling this."],
      [null, "So, what is the Icelandic government doing about this? Well, large sums of money are being allocated to a language technology fund that it is hoped will lead to the development of Icelandic sourced apps and other social media and digital systems, but clearly this is going to be an uphill struggle."],
      [null, "On the positive side, they know that Icelandic is still the official language of education and government. It has survived for well over a thousand years and the experts predict that its future in this nation state is sound and will continue to be so. However, there's no doubt that it's becoming an inevitable second choice in young people's lives."],
      [null, "This raises important questions. When you consider how much of the past is tied up in a language, will young Icelanders lose their sense of their own identity? Another issue that concerns the government of Iceland is this. If children are learning two languages through different routes, neither of which they are fully fluent in, will they be able to express themselves properly?"],
    ]),
  },

  // ══════════════════════════ Cam 17 - Test 3 ══════════════════════════
  {
    testName: 'Cam 17 - Test 3', partNumber: 1,
    transcript: fmt('Advice on surfing holidays', [
      ['Woman', "Jack, I'm thinking of taking the kids to the seaside on a surfing holiday this summer and I wanted to ask your advice – as I know you're such an expert."],
      ['Jack', "Well, I don't know about that, but yes, I've done a bit of surfing over the years. I'd thoroughly recommend it. I think it's the kind of holiday all the family can enjoy together. The thing about surfing is that it's great for all ages and all abilities. My youngest started when he was only three!"],
      ['Woman', "Wow! But it's quite physically demanding, isn't it? I've heard you need to be pretty fit."],
      ['Jack', "Yes. You'll certainly learn more quickly and won't tire as easily."],
      ['Woman', "Well – that should be OK for us. You've been surfing a few times in Ireland, haven't you?"],
      ['Jack', "Yes. There's some great surfing there, which people don't always realise."],
      ['Woman', "And which locations would you recommend? – there seem to be quite a few."],
      ['Jack', 'Yes, there are loads. Last year we went to County Donegal. There are several great places to surf there.'],
      ['Woman', "What about in County Clare? I read that's also really good for surfing."],
      ['Jack', "Yes, it is. I've been there a few times. Most people go to Lahinch. My kids love it there. The waves aren't too challenging and the town is very lively."],
      ['Woman', 'Are there good hotels there?'],
      ['Jack', "Yes – some very nice ones and there are also a few basic hostels and campsites. It's great if you need lessons as the surf schools are excellent."],
      ['Woman', 'Sounds good.'],
      ['Jack', "Yes and there's lots to see in the area – like those well-known cliffs – … I've forgotten the name of them …"],
      ['Woman', 'Oh don\'t worry – I can look them up.'],
      ['Jack', "I've also been surfing in County Mayo, which is less well-known for surfing, but we had a really good time. That was a few years ago when the kids were younger. There's a good surf school at Carrowniskey beach."],
      ['Woman', 'How do you spell that?'],
      ['Jack', 'C-A-double R-O-W-N-I-S-K-E-Y'],
      ['Woman', 'OK.'],
      ['Jack', 'I put the kids into the surf camp they run during the summer for 10-16 year olds.'],
      ['Woman', 'Oh right. How long was that for?'],
      ['Jack', "Three hours every day for a week. It was perfect – they were so tired out after that."],
      ['Woman', 'I can imagine.'],
      ['Jack', "One thing we did while the kids were surfing was to rent some kayaks to have a look around the bay which is nearby. It's really beautiful."],
      ['Woman', "Oh, I'd love to do that."],
      ['Woman', 'Now the only time I went to Ireland it rained practically every day.'],
      ['Jack', "Mmm yes – that can be a problem – but you can surf in the rain, you know."],
      ['Woman', "It doesn't have the same appeal, somehow."],
      ['Jack', "Well, the weather's been fine the last couple of years when I've been there, but actually, it tends to rain more in August than in the spring or autumn. September's my favourite month because the water is warmer then."],
      ['Woman', 'The only problem is that the kids are back to school then.'],
      ['Jack', "I know. But one good thing about Irish summers is that it doesn't get too hot. The average temperature is about 19 degrees and it usually doesn't go above 25 degrees."],
      ['Woman', 'That sounds alright. Now what about costs?'],
      ['Jack', "Surfing is a pretty cheap holiday really – the only cost is the hire of equipment. You can expect to pay a daily rate of about 30 euros for the hire of a wetsuit and board – but you can save about 40 euros if you hire by the week."],
      ['Woman', "That's not too bad."],
      ['Jack', "No. It's important to make sure you get good quality wetsuits – you'll all get too cold if you don't. And make sure you also get boots. They keep your feet warm and it's easier to surf with them on too."],
      ['Woman', 'OK. Well, thanks very much …'],
    ]),
  },
  {
    testName: 'Cam 17 - Test 3', partNumber: 2,
    transcript: fmt("School's extended hours childcare service", [
      [null, "Good afternoon. My name's Mrs Carter and I run the before and after school extended hours childcare service. I hope you've had a chance to have a good look around the school and talk to staff and pupils. I know that many of you are interested in using our childcare service when your child joins the school, and perhaps you already know something about it, but for those that don't, I'll go through the main details now."],
      [null, "We offer childcare for children from the ages of four to eleven both before and after school. I know that many parents who work find this service invaluable. You can leave your child with us safe in the knowledge that they will be extremely well cared for."],
      [null, "We are insured to provide care for up to 70 children, although we rarely have this many attending at any one session. I think we generally expect around 50-60 children for the afternoon sessions and about half that number for the breakfast sessions. Although we currently do have 70 children registered with us, not all of these attend every day. It's ten years since we began offering an extended hours service and we've come a long way during that time. When we first opened, we only had about 20 children attending regularly."],
      [null, "We try to keep our costs as low as we can and we think we provide very good value for money. For the afternoon sessions, which run from 3.30 until 6 p.m., it's £7.20. But if you prefer, you can pay for one hour only, which costs £3.50, or two hours which costs £5.70."],
      [null, "The cost of the childcare includes food and snacks. They'll be given breakfast in the morning and in the afternoon, a healthy snack as soon as they finish school. At 5 p.m. children are given something more substantial, such as pasta or a casserole. Please inform us of any allergies that your child might have and we'll make sure they're offered a suitable alternative."],
      [null, "As you may know, the childcare service runs through the school holidays from 8 a.m. to 6 p.m. We offer a really varied and exciting programme to keep the children entertained – we don't want them to feel as if they are still at school! It will also feel different because they'll get the chance to make new friends with children from other schools – spaces are available for them because a lot of our term-time children don't always attend during the holiday. In the past, parents have asked if children over the age of 11 are allowed to come with their younger brothers and sisters – but I'm afraid we're unable to do this because of the type of insurance we have."],
      [null, "So now let me tell you about some of the activities that your child can do during the after-school sessions. As well as being able to use the playground equipment, computers and the library, there is usually at least one 'special' activity that children can do each day. For example, Spanish. We have a specialist teacher coming in every Thursday to give a basic introduction to the language through games and songs. She does two sessions: one for the over 8s and one for the younger children. This is the only activity which we have to make an extra charge for – but it's well worth it."],
      [null, "Once a week the children have the opportunity to do some music. We're very lucky that one of our staff is a member of a folk band. On Mondays, she teaches singing and percussion to groups of children. We do rely on parental support for this, so if any of you sing or play an instrument and would be prepared to help out at these sessions, we'd be delighted."],
      [null, "Painting continues to be one of the most popular activities. To begin with we weren't keen on offering this because of the extra mess involved, but children kept asking if they could do some art and so we finally gave in. Art is great for helping the children to relax after working hard at school all day."],
      [null, "Yoga is something that we've been meaning to introduce for some time but haven't been able to find anyone available to teach it – until now that is. So we'll see how this goes. Hopefully, children will benefit in all sorts of ways from this."],
      [null, "Cooking is another popular activity. They make a different sort of cake, or pizza or bread each week. Although the younger children love doing it, we found that the mess was just too much, so we've decided to restrict this to the over 8s, as they are better able to clean up after themselves."],
    ]),
  },
  {
    testName: 'Cam 17 - Test 3', partNumber: 3,
    transcript: fmt("Holly's Work Placement Tutorial", [
      ['Holly', "Hello Dr Green – I'm here to talk to you about my work placement."],
      ['Tutor', "Oh yes, it's Holly, isn't it?"],
      ['Holly', 'Yes.'],
      ['Tutor', 'So, which work placement have you chosen?'],
      ['Holly', "I decided to go for the Orion Stadium placement. The event I'll be managing is one where I'm helping to set up a sports competition for primary school children."],
      ['Tutor', "Yup. That's always a popular placement – even though it can be tougher than you think working with children."],
      ['Holly', "I know, but it's the fresh air that attracts me – organising something indoors doesn't have the same appeal, even though it might be fun."],
      ['Tutor', "OK, so obviously safety's going to be one of your key concerns for this event."],
      ['Holly', "Yes, I've already thought about that. I'll need to make sure none of the equipment's damaged."],
      ['Tutor', "Ah well, you'll be working with schools, so the equipment will be their responsibility. However, the grounds and what goes on there will be yours."],
      ['Holly', "Oh I see – that'll include keeping everyone within the boundary once they're in their kit and on the field?"],
      ['Tutor', "Exactly – you'll need to inspect areas like changing rooms as well for anything someone can trip over, but your main priority will be not to lose anyone!"],
      ['Holly', "Right. I'll need staff to help with that."],
      ['Tutor', "And don't forget about the spectators."],
      ['Holly', "Mmm. I was thinking that many of them will be parents, who could help run the event."],
      ['Tutor', "I wouldn't rely on that. They'll be more interested in filming their children than volunteering."],
      ['Holly', "I'll need to make sure they don't interfere with events doing that!"],
      ['Tutor', "And that's not always easy, especially when a proud parent's trying to get a snap of their child and you want them to move elsewhere."],
      ['Holly', "OK. What about the scheduling?"],
      ['Tutor', "With sporting events there are all sorts of things that can alter the timetable – like rain, for instance – though so far, we've always been lucky with that."],
      ['Holly', "Yeah, and I was thinking about what to do if someone got hurt as well. I know that last year that caused a terrible delay."],
      ['Tutor', 'You have to be prepared for such things.'],
      ['Holly', "Oh. What if a match ends in a draw – do you let the teams keep going until someone wins?"],
      ['Tutor', "That'll be up to you – and again, you need to plan for it."],
      ['Holly', 'Right.'],
      ['Tutor', "Now, the aim of your work placement is to give you the opportunity to develop the skills that an events manager needs. So, let's talk about those a bit."],
      ['Holly', "Well, I think my communication skills are pretty good. I can talk on the phone to people and book venues and that kind of thing."],
      ['Tutor', "Good – just remember it isn't only about what you say. If you meet someone face-to-face and want to persuade them to be a sponsor, for example …"],
      ['Holly', "Oh, I'll dress up for that! Sure."],
      ['Tutor', "Good. Let's go on to think about your organisational skills. You're working in a very people-based industry and that means things won't always go to plan."],
      ['Holly', "I guess it's being prepared to make changes that matters."],
      ['Tutor', "That's right. You may have to make an on-the-spot change to a timetable because of a problem you hadn't anticipated …"],
      ['Holly', '… just do it! OK'],
      ['Tutor', "How's your time management these days?"],
      ['Holly', "I'm working on it – I'm certainly better when I have a deadline, which is why this work suits me."],
      ['Tutor', "Yes, but it's how you respond as that deadline approaches!"],
      ['Holly', "I know I've got to look calm even if I'm in a panic."],
      ['Tutor', "Just think to yourself – no one must know I'm under pressure."],
      ['Holly', "Yeah – even though I'm multi-tasking like crazy!"],
      ['Tutor', "Another skill that events managers need is creativity. Often your client has what we call the 'big picture' idea, but it's up to the events manager to think of all the fine points that go to making it work."],
      ['Holly', "Right, so I need to listen carefully to that idea and then fill in all the gaps."],
      ['Tutor', "That's right. And you'll have a team working under you, so another key skill is leadership. Your team may have lots of ideas too, but you've got to make the ultimate choices. Do we have refreshments inside or out, for example?"],
      ['Holly', "Isn't it better to be democratic?"],
      ['Tutor', "It's a nice idea, but you have the ultimate responsibility. So, believe in what you think best. Be prepared to say 'yes', that's a good idea but it won't work here."],
      ['Holly', "I see what you mean. What about the networking side of things? I know it's an area that a lot of students worry about because we don't have much experience to offer others."],
      ['Tutor', "But even without it – you can still be an interesting person with useful ideas. And the more people you impress, the better."],
      ['Holly', "I guess that will help me when I apply for a real job."],
      ['Tutor', "Exactly – think ahead – remember what your ambitions are and keep them in mind."],
      ['Holly', 'Definitely.'],
    ]),
  },
  {
    testName: 'Cam 17 - Test 3', partNumber: 4,
    transcript: fmt('Bird Migration Theory', [
      [null, "Scientists believe that a majority of the earth's bird population migrate in some fashion or other. Some travel seasonally for relatively short distances, such as birds that move from their winter habitats in lowlands to mountain tops for the summers. Others, like the Arctic Tern, travel more than 25,000 miles seasonally between the northern and southern poles. Bird migration has been studied over many centuries through a variety of observations."],
      [null, "But until relatively recently, where birds went to in the winter was considered something of a mystery. The lack of modern science and technology led to many theories that we now recognize as error-filled and even somewhat amusing. Take hibernation theory for example – two thousand years ago, it was commonly believed that when birds left an area, they went underwater to hibernate in the seas and oceans. Another theory for the regular appearance and disappearance of birds was that they spend winter hidden in mud till the weather changed and food became abundant again. The theory that some birds hibernate persisted until experiments were done on caged birds in the 1940s which demonstrated that birds have no hibernation instinct."],
      [null, "One of the earliest naturalists and philosophers from ancient Greece was Aristotle who was the first writer to discuss the disappearance and reappearance of some bird species at certain times of year. He developed the theory of transmutation, the seasonal change of one species into another, by observing redstarts and robins. He observed that in the autumn, small birds called 'redstarts' began to lose their feathers, which convinced Aristotle that they changed into robins for the winter, and back into redstarts in the summer. These assumptions are understandable given that this pair of species are similar in shape, but are a classic example of an incorrect interpretation based on correct observations."],
      [null, "The most bizarre theory was put forward by an English amateur scientist, Charles Morton, in the seventeenth century. He wrote a surprisingly well-regarded paper claiming that birds migrate to the moon and back every year. He came to this conclusion as the only logical explanation for the total disappearance of some species."],
      [null, "One of the key moments in the development of migration theory came in 1822 when a white stork was shot in Germany. This particular stork made history because of the long spear in its neck which incredibly had not killed it – everyone immediately realised this spear was definitely not European. It turned out to be a spear from a tribe in Central Africa. This was a truly defining moment in the history of ornithology because it was the first evidence that storks spend their winters in sub-Saharan Africa. You can still see the 'arrow stork' in the Zoological Collection of the University of Rostock in Germany."],
      [null, "People gradually became aware that European birds moved south in autumn and north in summer but didn't know much about it until the practice of catching birds and putting rings on their legs became established. Before this, very little information was available about the actual destinations of particular species and how they travelled there. People speculated that larger birds provided a kind of taxi service for smaller birds by carrying them on their backs. This idea came about because it seemed impossible that small birds weighing only a few grams could fly over vast oceans. This idea was supported by observations of bird behaviour such as the harassment of larger birds by smaller birds."],
      [null, "The development of bird ringing, by a Danish schoolteacher, Hans Christian Cornelius Mortensen, made many discoveries possible. This is still common practice today and relies upon what is known as 'recovery' – this is when ringed birds are found dead in the place they have migrated to, and identified. Huge amounts of data were gathered in the early part of the twentieth century and for the first time in history people understood where birds actually went to in winter. In 1931, an atlas was published showing where the most common species of European birds migrated to. More recent theories about bird migration …"],
    ]),
  },

  // ══════════════════════════ Cam 17 - Test 4 ══════════════════════════
  {
    testName: 'Cam 17 - Test 4', partNumber: 1,
    transcript: fmt('Easy Life Cleaning Services', [
      ['Jacinta', 'Hello, Easy Life Cleaning Services, Jacinta speaking.'],
      ['Client', "Oh hello. I'm looking for a cleaning service for my apartment – do you do domestic cleaning?"],
      ['Jacinta', 'Sure.'],
      ['Client', "Well, it's just a one-bedroom flat. Do you have a basic cleaning package?"],
      ['Jacinta', "Yes. For a one-bedroom flat we're probably looking at about two hours for a clean. So we'd do a thorough clean of all surfaces in each room, and polish them where necessary. Does your apartment have carpets?"],
      ['Client', "No, I don't have any, but the floor would need cleaning."],
      ['Jacinta', "Of course – we'd do that in every room. And we'd do a thorough clean of the kitchen and bathroom."],
      ['Client', 'OK.'],
      ['Jacinta', 'Then we have some additional services which you can request if you want – so for example, we can clean your oven for you every week.'],
      ['Client', "Actually, I hardly ever use that, but can you do the fridge?"],
      ['Jacinta', 'Sure. Would you like that done every week?'],
      ['Client', 'Yes, definitely. And would ironing clothes be an additional service you can do?'],
      ['Jacinta', 'Yes, of course.'],
      ['Client', "It wouldn't be much, just my shirts for work that week."],
      ['Jacinta', "That's fine. And we could also clean your microwave if you want."],
      ['Client', "No, I wipe that out pretty regularly so there's no need for that."],
      ['Jacinta', "We also offer additional services that you might want a bit less often, say every month. So for example, if the inside of your windows need cleaning, we could do that."],
      ['Client', "Yes, that'd be good. I'm on the fifteenth floor, so the outside gets done regularly by specialists, but the inside does get a bit grubby."],
      ['Jacinta', 'And we could arrange for your curtains to get cleaned if necessary.'],
      ['Client', "No, they're OK. But would you be able to do something about the balcony? It's quite small and I don't use it much, but it could do with a wash every month or so."],
      ['Jacinta', 'Yes, we can get the pressure washer onto that.'],
      ['Jacinta', "Now if you're interested, we do offer some other possibilities to do with general maintenance. For example, if you have a problem with water and you need a plumber in a hurry, we can put you in touch with a reliable one who can come out straightaway. And the same thing if you need an electrician."],
      ['Client', "Right. That's good to know. I've only just moved here so I don't have any of those sorts of contacts."],
      ['Jacinta', "And I don't know if this is of interest to you, but we also offer a special vacuum cleaning system which can improve the indoor air quality of your home by capturing up to 99% of all the dust in the air. So if you're troubled by allergies, this can make a big difference."],
      ['Client', "Right. In fact, I don't have that sort of problem, but I'll bear it in mind. Now can you tell me a bit about your cleaning staff?"],
      ['Jacinta', "Of course. So all our cleaners are very carefully selected. When they apply to us, they have to undergo a security check with the police to make sure they don't have any sort of criminal background, and, of course, they have to provide references as well. Then if we think they might be suitable for the job, we give them training for it. That lasts for two weeks so it's very thorough, and at the end of it, they have a test. If they pass that, we take them on, but we monitor them very carefully – we ask all our clients to complete a review of their performance after every visit and to email it to us. So we can pick up any problems straightaway and deal with them."],
      ['Client', 'OK, well that all sounds good. And will I always have the same cleaner?'],
      ['Jacinta', "Yes, we do our best to organise it that way, and we usually manage it."],
      ['Client', "Good. That's fine. Right, so I'd like to go ahead and …"],
    ]),
  },
  {
    testName: 'Cam 17 - Test 4', partNumber: 2,
    transcript: fmt('Reducing hotel staff turnover', [
      [null, "As many of you here today have worked in the hotel industry for some time, I'm sure you have experienced the problem of high staff turnover in your hotels. Every hotel relies on having loyal and experienced members of staff who make sure that everything runs smoothly. If staff are constantly changing, it can make life difficult for everyone. But why do staff leave frequently in many hotels? Of course, many hotel jobs, such as cleaning, are low-skilled and are not well-paid. A lot of managers think it's this and the long hours that are the main causes of high staff turnover – but what they don't realise is that it's the lack of training in many hotel jobs which is a huge factor."],
      [null, "So, what kind of problems does a high turnover of staff cause? Well, having to recruit new staff all the time can be very time-consuming, and managers may have to cover some duties while waiting for new staff to arrive. This means they don't have time to think about less immediate problems such as how to improve their service. When staff leave, it can also severely affect the colleagues they leave behind. It has a negative effect on remaining staff, who may start to feel that they too should be thinking about leaving."],
      [null, "So, what can be done to change this situation? Firstly, managers should stop making basic errors which leave their staff feeling upset and resentful. When organising shifts, for example, make sure you never give certain staff preferential treatment. All staff should be given some choice about when they work, and everyone should have to work some evening and weekend shifts. If you treat staff fairly, they'll be more likely to step in and help when extra staff are needed."],
      [null, "Keeping staff happy has other tangible benefits for the business. Take the Dunwich Hotel as an example. It had been experiencing a problem with staff complaints and in order to deal with this, invested in staff training and improved staff conditions. Not only did the level of complaints fall, but they also noticed a significant increase in the amount each customer spent during their stay. They have now introduced a customer loyalty scheme which is going really well."],
      [null, "Now I'd like to look at some ways you can reduce staff turnover in your hotels, and I'll do this by giving some examples of hotels where I've done some training recently."],
      [null, "The Sun Club received feedback which showed that staff thought managers didn't value their opinions. They weren't made to feel they were partners who were contributing to the success of the business as a whole. This situation has changed. Junior staff at all levels are regularly invited to meetings where their ideas are welcomed."],
      [null, "A year ago, The Portland recognised the need to invest in staff retention. Their first step was to introduce a scheme for recognising talent amongst their employees. The hope is that organising training for individuals with management potential will encourage them to stay with the business."],
      [null, "At Bluewater, managers decided to recognise 50 high achievers from across the company's huge hotel chain. As a reward, they're sent on an all-expenses-paid trip abroad every year. Fun is an important element in the trips, but there's also the opportunity to learn something useful. This year's trip included a visit to a brewery, where staff learned about the new beer that would be served in the hotel."],
      [null, "Pentlow Hotels identified that retention of junior reception staff was an issue. In order to encourage them to see that working in a hotel could be worthwhile and rewarding, with good prospects, they introduced a management programme. These staff were given additional responsibilities and the chance to work in various roles in the hotel."],
      [null, "Green Planet wanted to be seen as a caring employer. To make life easier for staff, many of whom had childcare responsibilities, the hotel began issuing vouchers to help cover the cost of childcare."],
      [null, "Louise Marsh at The Amesbury has one of the best staff retention rates in the business. Since she joined the company, she has made a huge effort to achieve this by creating a co-operative and supportive environment. For her, the staff are part of a large family where everyone is valued."],
      [null, 'Ok, now I\'d like to …'],
    ]),
  },
  {
    testName: 'Cam 17 - Test 4', partNumber: 3,
    transcript: fmt('Development of sporting equipment', [
      ['Jeanne', 'Hi Thomas, how are you enjoying the course so far?'],
      ['Thomas', 'Yeah, I think it\'s good.'],
      ['Jeanne', "Remind me – why did you decide to study sports science? Didn't you want to be a professional athlete when you were at school?"],
      ['Thomas', "Yeah – that was my goal, and all my classmates assumed I would achieve it; they thought I was brilliant."],
      ['Jeanne', 'That must have been a nice feeling.'],
      ['Thomas', 'Mm, I thought I could win anything. There was no one who could run faster than me.'],
      ['Jeanne', "Exactly – so what happened? Did your mum and dad want you to be more 'academic'?"],
      ['Thomas', 'Not at all. Perhaps they should have pushed me harder, though.'],
      ['Jeanne', 'What do you mean?'],
      ['Thomas', 'I think I should have practised more.'],
      ['Jeanne', 'What makes you say that?'],
      ['Thomas', 'Well, I went out to Kenya for a couple of weeks to train …'],
      ['Jeanne', "Really! I didn't know that."],
      ['Thomas', "I was chosen to go there out of loads of kids and run with some of the top teenage athletes in the world. And … I was so calm about it. I just kept thinking how fortunate I was. What a great chance this was! Everyone back home was so proud of me. But once we started competing, I very quickly realised I wasn't good enough."],
      ['Jeanne', 'That must have been a huge shock.'],
      ['Thomas', "I thought 'this can't be happening'! I was used to winning."],
      ['Jeanne', "I'm sorry to hear that."],
      ['Thomas', "It's OK. I'm over it now and I think it's much better to do a university course and this one has such a variety of sports-related areas. It's going to be good."],
      ['Jeanne', 'Oh, I agree – I chose it because of that.'],
      ['Thomas', "So Jeanne – have you thought of any ideas for the discussion session next week on technology and sport?"],
      ['Jeanne', "We have to cover more than one sport, don't we?"],
      ['Thomas', 'Yeah.'],
      ['Jeanne', "You know – we always think technology is about the future, but we could gather some ideas about past developments in sport."],
      ['Thomas', "Look at early types of equipment perhaps? Uh, I remember reading something about table tennis bats once – how they ended up being covered with pimpled rubber."],
      ['Jeanne', "Cos they were just wooden at first, I'd imagine."],
      ['Thomas', "Yeah. In about the 1920s, a factory was making rolls of the rubber in bulk for something like horse harnesses."],
      ['Jeanne', 'Really!'],
      ['Thomas', "Yeah – and someone realised that it'd make a perfect covering for the wooden bats."],
      ['Jeanne', "So what about cricket – that's had a few innovative changes. Maybe the pads they were on their legs?"],
      ['Thomas', "I don't think they've changed much but, I'm just looking on the internet … and it says that when the first cricket helmet came in, in 1978, the Australian batsman who first wore it was booed and jeered by people watching because it was so ugly!"],
      ['Jeanne', 'Wow, players have to protect themselves from getting hurt! I mean everyone wears one now.'],
      ['Thomas', 'Mm, unlike the cycle helmet.'],
      ['Jeanne', "Well, unless you're a professional, but you're right, many ordinary bikers don't wear a helmet."],
      ['Thomas', "Hey, look at these pictures of original helmet designs. This one looks like an upside-down bowl!"],
      ['Jeanne', "Yet, the woman's laughing – she's so proud to be wearing it!"],
      ['Thomas', "It says serious cyclists ended up with wet hair from all the hard exercise."],
      ['Jeanne', "I guess that's why they have large air vents in them now so that the skin can breathe more easily."],
      ['Thomas', "OK, so we've done helmets. What about golf balls or better still golf clubs – they've changed a lot."],
      ['Jeanne', "Yeah – I remember my great grandfather telling me that because a club was made entirely of wood, it would easily break and players had to get another."],
      ['Thomas', "There's no wood at all in them now, is there?"],
      ['Jeanne', "No – they're much more powerful."],
      ['Thomas', 'The same must be true of hockey sticks.'],
      ['Jeanne', "I don't think so because players still use wooden sticks today. What it does say here, though, is that when the game started you had to produce a stick yourself."],
      ['Thomas', "I guess they just weren't being manufactured. So, one more perhaps. What about football?"],
      ['Jeanne', 'Well, I know the first balls were made of animal skin.'],
      ['Thomas', "Yeah, they covered them with pieces of leather that were stitched together, but … the balls let in water when it rained."],
      ['Jeanne', 'Oh, that would have made them much heavier.'],
      ['Thomas', "That's right. You can imagine the damage to player's necks when the ball was headed."],
      ['Jeanne', 'How painful that must have been!'],
      ['Thomas', "Yeah, well, I think we can put together some useful ideas …"],
    ]),
  },
  {
    testName: 'Cam 17 - Test 4', partNumber: 4,
    transcript: fmt('Maple syrup', [
      [null, "Hello everyone. Today we're going to look at another natural food product and that's maple syrup. What is this exactly? Well, maple syrup looks rather like clear honey, but it's not made by bees; it's produced from the plant fluid – or sap – inside the maple tree and that makes maple syrup a very natural product. Maple syrup is a thick, golden, sweet-tasting liquid that can be bought in bottles or jars and poured onto food such as waffles and ice cream or used in the baking of cakes and pastries. It contains no preservatives or added ingredients, and it provides a healthy alternative to refined sugar."],
      [null, "Let's just talk a bit about the maple tree itself, which is where maple syrup comes from. So, there are many species of maple tree, and they'll grow without fertilizer in areas where there's plenty of moisture in the soil. However, they'll only do this if another important criterion is fulfilled, which is that they must have full or partial sun exposure during the day and very cool nights – and I'll talk more about that in a minute. There are only certain parts of the world that provide all these conditions: one is Canada, and by that, I mean all parts of Canada, and the other is the north-eastern states of North America. In these areas, the climate suits the trees perfectly. In fact, Canada produces over two-thirds of the world's maple syrup, which is why the five-pointed maple leaf is a Canadian symbol and has features on the flag since 1964."],
      [null, "So how did maple syrup production begin? Well, long before Europeans settled in these parts of the world, the indigenous communities had started producing maple sugar. They bored holes in the trunks of maple trees and used containers made of tree bark to collect the liquid sap as it poured out. As they were unable to keep the liquid for any length of time – they didn't have storage facilities in those days – they boiled the liquid by placing pieces of rock that had become scorching hot from the sun into the sap. They did this until it turned into sugar, and they were then able to use this to sweeten their food and drinks. Since that time, improvements have been made to the process, but it has changed very little overall."],
      [null, "So let's look at the production of maple syrup today. Clearly, the maple forests are a valuable resource in many Canadian and North American communities. The trees have to be well looked after and they cannot be used to make syrup until the trunks reach a diameter of around 25 centimetres. This can take anything up to 40 years. As I've already mentioned, maple trees need the right conditions to grow and also to produce sap. Why is this? Well, what happens is that during a cold night, the tree absorbs water from the soil, and that rises through the tree's vascular system. But then in the warmer daytime, the change in temperature causes the water to be pushed back down to the bottom of the tree. This continual movement – up and down – leads to the formation of the sap needed for maple syrup production."],
      [null, "When the tree is ready, it can be tapped and this involves drilling a small hole into the trunk and inserting a tube into it that ends in a bucket. The trees can often take several taps, though the workers take care not to cause any damage to the healthy growth of the tree itself. The sap that comes out of the trees consists of 98 percent water and 2 percent sugar and other nutrients. It has to be boiled so that much of that water evaporates, and this process has to take place immediately, using what are called evaporators. These are basically extremely large pans – the sap is poured into these, a fire is built and the pans are then heated until the sap boils. As it does this, the water evaporates, and the syrup begins to form. The evaporation process creates large quantities of steam, and the sap becomes thicker and denser, and, at just the right moment, when the sap is thick enough to be called maple syrup, the worker removes it from the heat. After this process, something called 'sugar sand' has to be filtered out as this builds up during the boiling and gives the syrup a cloudy appearance and a slightly gritty taste. Once this has been done, the syrup is ready to be packaged so that it can be used for a whole variety of products. It takes 40 litres of sap to produce one litre of maple syrup so you can get an idea of how much is needed!"],
      [null, "So that's the basic process. In places like Quebec where …"],
    ]),
  },
];

async function runSeed() {
  let updatedTests = 0, updatedSections = 0, sectionNotFound = 0;
  for (const target of TARGETS) {
    const { testName, partNumber, transcript } = target;
    const test = await ListeningTest.findOne({ name: testName });
    if (!test) throw new Error(`ListeningTest not found: "${testName}"`);
    const embedded = test.sections.find(s => s.partNumber === partNumber);
    if (!embedded) throw new Error(`Part ${partNumber} not found on ListeningTest "${testName}"`);
    if (embedded.transcript !== transcript) {
      embedded.transcript = transcript;
      await test.save();
      updatedTests++;
    }

    const title = sectionTitle(testName, embedded);
    const section = await ListeningSection.findOne({ title, partNumber });
    if (!section) {
      console.log(`[SeedListeningTranscriptsCam17] WARNING: standalone ListeningSection not found for "${title}" (Part ${partNumber}) — skipped.`);
      sectionNotFound++;
      continue;
    }
    if (section.transcript !== transcript) {
      section.transcript = transcript;
      await section.save();
      updatedSections++;
    }
  }
  console.log(`\n[SeedListeningTranscriptsCam17] Done. ListeningTest sections updated=${updatedTests}, ListeningSection docs updated=${updatedSections}, standalone-not-found=${sectionNotFound} (out of ${TARGETS.length} targets).`);
}

if (require.main === module) {
  (async () => {
    await mongoose.connect(process.env.MONGO_URI);
    try {
      await runSeed();
    } finally {
      await mongoose.disconnect();
    }
  })().catch(e => { console.error('[SeedListeningTranscriptsCam17] FAILED', e); process.exit(1); });
}

module.exports = { runSeed, TARGETS };
