// Vol 1 – Test 8 (PDF p1–6, key p23; audio test 8/Part 1,3,4.mp3 + "part 2.mp4" (audio track); transcript Tapescript Test 8.docx)
// Source errors fixed: Q1-6 instruction "ONE MORE THAN TWO WORDS AND OR A NUMBER" (→ NO MORE THAN TWO WORDS AND/OR A
// NUMBER, covers Q1-10); key "9/nine moth" (→ months); option A of Q21-26 "it is lacks patience".
const { note, table, mc, multi, map, matching, short } = require('../vol_build');

module.exports = {
  vol: 1, test: 8,
  rawFix: [['look at questions. One, two, four. Now listen carefully and answer questions. One, two, four.', 'look at questions 1 to 4. Now listen carefully and answer questions 1 to 4.']],
  sections: [
    {
      part: 1, title: 'Washing Machine Warranty', audio: 'test 8/Part 1.mp3', cover: 'washing machine | laundry appliance',
      speakers: { 1: 'Judy', 2: 'Roger' },
      fix: [["King's well washing machine", 'Kingswell Washing Machine'], ["It's CWX57684.", "It's CWX576884."], ["It's G0194KE.", "It's G-O-1-9-4-K-E."], ['Judy Smith', 'Judie Smith'],
        ['The washing machine was totally out of control. And the alarm. And it also started to sound.', 'The washing machine was totally out of control and the alarm also started to sound.'],
        ['Oh, sorry. Madame Saturday has been occupied.', 'Oh, sorry, madam. Saturday has been occupied.'], ["It's 386477, five, seven.", "It's 38647757."]],
      groups: [
        note('Complete the notes below.\nWrite NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.', 'Washing Machine Warranty', [
          '<strong>Personal details</strong>',
          '• Name: Judie Smith',
          '• Reference number: __Q1__',
          '• Time of purchase: __Q2__ ago',
          '• Current address: 120 __Q3__, Oxford',
          '• Postcode: __Q4__',
          '<strong>Problems</strong>',
          '• The floor was wet because of the __Q5__.',
          '• The washing machine was out of control and the woman __Q6__ the machine immediately.',
          '• The floor is made of __Q7__.',
          '<strong>Arrangement for the repair work</strong>',
          '• Ask a __Q8__ to repair the washing machine.',
          '• The repairman is available __Q9__.',
          '• The woman’s house is opposite the __Q10__.',
        ], { 1: 'CWX576884', 2: '9 months/nine months', 3: 'Middle Street', 4: 'G0194KE/GO194KE', 5: 'water', 6: 'switched off', 7: 'wood', 8: 'client engineer', 9: 'next Tuesday', 10: 'post office' }, 'Questions 1-10'),
      ],
      expl: {
        1: { v: 'Đầu bài, khi hỏi số tham chiếu trên thẻ bảo hành.', t: "It's CWX576884.", p: 'Số tham chiếu ở góc trên bên phải thẻ bảo hành → CWX576884' },
        2: { v: 'Khi hỏi thời điểm mua máy.', t: 'So it was about nine months ago.', p: 'Mua mùa hè năm ngoái, khoảng 9 tháng trước; “two year warranty” là thời hạn bảo hành (bẫy) → 9 months' },
        3: { v: 'Khi hỏi địa chỉ hiện tại.', t: "It's 120 Middle Street, Oxford.", p: 'Địa chỉ hiện tại là số 120 phố Middle → Middle Street' },
        4: { v: 'Ngay sau đó, mã bưu điện.', t: "It's G-O-1-9-4-K-E.", p: 'Mã bưu điện được đọc từng ký tự → G0194KE' },
        5: { v: 'Khi mô tả sự cố.', t: 'The water had soaked the entire floor.', p: 'Máy bị rò rỉ, nước làm ướt cả sàn → water' },
        6: { v: 'Khi hỏi đã làm gì để máy ngừng rò.', t: 'so I just switched off the machine straight away.', p: '“Straight away” = immediately; cô tắt máy ngay lập tức → switched off' },
        7: { v: 'Khi nói về sàn nhà.', t: 'Oh, then I found my floor was nearly a disaster as it is made of wood rather than marble.', p: 'Sàn làm bằng gỗ chứ không phải đá cẩm thạch (bẫy) → wood' },
        8: { v: 'Phần sắp xếp sửa chữa.', t: "Later, we'll send a client engineer to your house to fix it.", p: 'Công ty sẽ cử một kỹ sư khách hàng tới sửa máy → client engineer' },
        9: { v: 'Khi hẹn ngày sửa.', t: 'The earliest day we can arrange for you is next Tuesday.', p: 'Thứ Bảy đã kín lịch (bẫy); sớm nhất là thứ Ba tuần sau → next Tuesday' },
        10: { v: 'Khi chỉ đường tới nhà.', t: "It's near the central market, just across from the post office.", p: '“Just across from” = opposite; gần chợ trung tâm (bẫy), đối diện bưu điện → post office' },
      },
    },
    {
      part: 2, title: 'Driving Licences and Traffic in the UK', audio: 'test 8/part 2.mp4', cover: 'UK motorway traffic | road signs Britain',
      fix: [["about road conditions in various areas of the UK. I am also going to tell you about driver's licenses in the UK.", "about road conditions in various areas of the UK. I am also going to tell you about driving licences in the UK."],
        ['to get the traffic flowing smoothly', 'to get the traffic flowing smoothly'], ['the forms accordingly. Step by step, I', 'the forms accordingly, step by step. I'], ['to the agency. Location of your choice.', 'to the agency location of your choice.'], ['The other cities in the UK are.', '']],
      groups: [
        mc('Choose the correct letter, A, B or C.', [
          [11, 'What is the basic requirement for applying for a UK driving licence?', ['a medical report', 'a valid licence from another country', 'current residency in the UK'], 'C'],
          [12, 'What is true about the translation of original licences?', ['Applicants need to go to a recognised organisation.', 'It is not always necessary for foreigners when applying for a UK licence.', 'Applicants need to pay an extra fee for translation services.'], 'A'],
          [13, 'When applying for a UK licence, which type of photos will NOT be approved?', ['photos in which the applicant is wearing glasses', 'photos with a cream background', 'photos that are undersized'], 'B'],
          [14, 'What does the speaker think of the licence checking service?', ['The process is too slow.', 'The application form is confusing.', 'Some of the steps are unnecessary.'], 'A'],
          [15, 'What does the speaker recommend about making an application?', ['choosing a quiet location', 'visiting the nearest branch', 'completing the forms online'], 'C'],
        ], 'Questions 11-15'),
        matching('What is the current feature of traffic management in each of the following cities?\nWrite the correct letter, A-H, next to Questions 16-20.',
          ['good signage', 'multiple access roads', 'police control points', 'ring roads', 'one-way streets', 'effective traffic lights', 'additional lanes', 'pedestrianised areas'],
          [[16, 'London', 'A'], [17, 'Edinburgh', 'F'], [18, 'Cardiff', 'G'], [19, 'Manchester', 'D'], [20, 'Oxford', 'B']], { title: 'Features', groupTitle: 'Questions 16-20' }),
      ],
      expl: {
        11: { v: 'Đầu bài, điều kiện xin bằng lái ở Anh.', t: 'you must be a UK resident.', p: 'Điều kiện bắt buộc là phải cư trú ở Anh; báo cáo y tế chỉ cần khi gia hạn (bẫy A) → C' },
        12: { v: 'Khi nói về việc dịch bằng lái gốc.', t: 'you will need to visit an official agency.', p: '“An official agency” = tổ chức được công nhận; việc dịch là bắt buộc (loại B) và đã gồm trong lệ phí (loại C) → A' },
        13: { v: 'Khi nói về ảnh thẻ bị từ chối.', t: 'The majority of rejected photos are the ones that were taken with a cream backdrop instead of a monotone gray background.', p: 'Ảnh nhỏ được phóng to, đeo kính vẫn được; ảnh nền màu kem bị từ chối → B' },
        14: { v: 'Khi nói về dịch vụ kiểm tra bằng lái.', t: 'Ideally, I would like to see the process going faster since it can take hours to finish.', p: 'Quy trình rõ ràng nhưng mất hàng giờ, người nói muốn nó nhanh hơn → quá chậm → A' },
        15: { v: 'Khi khuyên về cách nộp hồ sơ.', t: 'the quickest way to complete an application is to fill out the form on the Internet and then bring a print copy with you', p: 'Chi nhánh nào cũng có lúc đông, giá như nhau; lời khuyên duy nhất là điền đơn trực tuyến → C' },
        16: { v: 'Phần giao thông các thành phố, London.', t: 'But on the whole, I find the traffic signs are very clear.', p: 'London có nhiều đường một chiều (bẫy E), nhưng điểm nổi bật là biển báo rất rõ ràng → A' },
        17: { v: 'Edinburgh.', t: 'It is a city of lights, traffic lights, but they are extremely efficient', p: 'Đèn giao thông được hẹn giờ hoàn hảo, rất hiệu quả; khu đi bộ chỉ là lý do cần điều tiết (bẫy H) → F' },
        18: { v: 'Cardiff.', t: 'It recently completed a road expansion scheme and the extra lanes of the dual carriageway are easing congestion.', p: '“Extra lanes” = làn đường bổ sung → G' },
        19: { v: 'Manchester.', t: 'Instead of going through the town center, most vehicles choose ring roads so as to avoid the downtown congestion.', p: 'Hiện tại xe chạy đường vành đai; trạm cảnh sát chỉ là khả năng trong tương lai (bẫy C) → D' },
        20: { v: 'Oxford.', t: 'I like the many options for getting in and out of the city because drivers can always find alternative routes.', p: 'Nhiều lối ra vào thành phố = nhiều đường tiếp cận → B' },
      },
    },
    {
      part: 3, title: 'Hotel Internship', audio: 'test 8/Part 3.mp3', cover: 'hotel reception lobby | hotel front desk',
      speakers: { 1: 'Mona', 3: 'Tom', 2: 'Tom' },
      fix: [['As a shortage of hands always made, many customers wait long', 'A shortage of hands always made many customers wait long'],
        ['helpful to what I intend to do after graduation but in the end I found it has given me some practical examples which are helpful to what I intend to do after graduation.', 'helpful to what I intend to do after graduation.'],
        ["I'm not so good at giving a presentation thought.", "I'm not so good at giving a presentation, though."]],
      groups: [
        matching('What problem does Mona point out about each part of the hotel where she interned?\nWrite the correct letter, A-F, next to Questions 21-26.',
          ['It lacks patience.', 'It is very strict.', 'It is a daily routine.', 'It lacks sufficient staff.', 'It is noisy.', 'It is very tiring.'],
          [[21, 'reception', 'C'], [22, 'restaurant', 'B'], [23, 'coffee bar', 'D'], [24, 'shop', 'F'], [25, 'personnel office', 'A'], [26, 'cleaning', 'E']], { title: 'Problems', groupTitle: 'Questions 21-26' }),
        mc('Choose the correct letter, A, B or C.', [
          [27, 'How does the experience benefit Mona?', ['It is good for her future job.', 'It is good for her dissertation.', 'It can let her know something about a specific job.'], 'A'],
          [28, 'Why does the tutor want Mona to do the presentation?', ['because she can do it skilfully', 'because she wants to do it herself', 'because she can show other students how to do a presentation'], 'C'],
          [29, 'What does Mona suggest Tom do?', ['talk to the university’s career centre', 'talk to his tutor', 'contact the hotel manager'], 'A'],
          [30, 'What is Tom’s plan for his own essay?', ['to study the rise of five-star hotels', 'to use a video approach', 'to do research into how the hotel industry works'], 'A'],
        ], 'Questions 27-30'),
      ],
      expl: {
        21: { v: 'Khi Mona nói về quầy lễ tân.', t: 'I noticed the staff there kept doing the same thing every day', p: 'Nhân viên lễ tân lặp lại cùng một việc mỗi ngày → công việc thường nhật → C' },
        22: { v: 'Nhà hàng.', t: 'And in the restaurant, the employees told me that they must obey the rules.', p: 'Phải tuân thủ quy định, không mặc đồng phục bị trừ 20% lương ngày → rất nghiêm khắc → B' },
        23: { v: 'Quầy cà phê.', t: 'A shortage of hands always made many customers wait long', p: '“Shortage of hands” = thiếu nhân viên → D' },
        24: { v: 'Cửa hàng nơi Mona làm việc.', t: 'Every night when I got off work, I was nearly exhausted.', p: 'Làm từ 9 giờ sáng đến 6 giờ chiều, tối nào cũng kiệt sức → rất mệt → F' },
        25: { v: 'Phòng nhân sự.', t: 'But the employee of the personnel office seemed a bit annoyed and started complaining', p: 'Nhân viên tỏ ra bực bội và phàn nàn khi Mona hỏi → thiếu kiên nhẫn → A' },
        26: { v: 'Bộ phận dọn dẹp.', t: 'the sound seemed too loud when they were working.', p: 'Máy hút bụi cũ chạy quá ồn → E' },
        27: { v: 'Khi Tom nói Mona được lợi nhiều từ kỳ thực tập.', t: 'it has given me some practical examples which are helpful to what I intend to do after graduation.', p: 'Ban đầu chỉ để làm bài luận (bẫy B), nhưng nó giúp ích cho công việc sau khi tốt nghiệp; cô vẫn chưa rõ về vị trí cụ thể (loại C) → A' },
        28: { v: 'Khi nói về bài thuyết trình.', t: 'and other students can learn from my presentation.', p: 'Mona không giỏi thuyết trình (loại A); gia sư muốn các bạn khác học cách thuyết trình qua bài của cô → C' },
        29: { v: 'Khi Tom hỏi có nên gọi cho quản lý khách sạn.', t: 'There is a career office on campus that has got a list of companies offering internship opportunities to students.', p: 'Mona khuyên không nên gọi quản lý (loại C) mà đến văn phòng hướng nghiệp của trường; thư giới thiệu của gia sư chỉ là giấy tờ kèm theo → A' },
        30: { v: 'Cuối phần 3, kế hoạch bài luận của Tom.', t: 'So I intend to carry out extensive research on this aspect.', p: 'Tom ấn tượng với số khách sạn 5 sao ngày càng tăng và định nghiên cứu điều đó; dùng video thì chưa quyết (loại B) → A' },
      },
    },
    {
      part: 4, title: 'The Early History of Salt', audio: 'test 8/Part 4.mp3', cover: 'sea salt crystals | salt pans',
      fix: [['In my presentation. I\'m going to talk about salt in modern times when we talk about salt.', "In my presentation, I'm going to talk about salt. In modern times, when we talk about salt,"],
        ['was known as salary magenta in Latin', 'was known as salarium argentum in Latin'], ["A soldier salary was cut", "A soldier's salary was cut"],
        ['Salting people tried to keep meat', 'Salting. People tried to keep meat'], ["recorded the Swedish King's Everyday meals", "recorded the Swedish king's everyday meals"],
        ['mentioning that £175 of meat was consumed each year, but over £150 was salty.', 'mentioning that 175 pounds of meat was consumed each year, but over 150 pounds was salted.'],
        ['Making communication between different cultures more frequent and.', 'making communication between different cultures more frequent.']],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'The Early History of Salt', [
          '<strong>Introduction</strong>',
          '• Salt is essential for human __Q31__.',
          '<strong>Ancient Rome</strong>',
          '• The word __Q32__ comes from the Latin words salarium argentum, which were used to describe the payment to Roman soldiers.',
          '<strong>Ancient Sweden</strong>',
          '• Animals were kept in the local __Q33__ at the right time of year.',
          '• Fresh meat was only available in __Q34__.',
          '• Salt has been used widely: we can tell from the diet of the __Q35__ in Sweden.',
          '• __Q36__ consumption increased rapidly because the food was much too salty.',
          '<strong>Salt source</strong>',
          '• People mainly extract salt from oceans and __Q37__ in the basins.',
          '• Salt from spring water is more __Q38__ and purer compared to that from sea water.',
          '<strong>Salt distribution</strong>',
          '• In ancient Sweden: locals needed to protect the __Q39__ by which they imported salt.',
          '• In other ancient countries: people carrying salt around were seen as a natural means of __Q40__.',
        ], { 31: 'health', 32: 'salary', 33: 'forest/forests', 34: 'October', 35: 'king', 36: 'beer', 37: 'deserts/desert', 38: 'concentrated', 39: 'shipping', 40: 'transport' }, 'Questions 31-40'),
      ],
      expl: {
        31: { v: 'Phần mở đầu.', t: 'More importantly, salt plays an indispensable role in the health of human beings.', p: 'Muối đóng vai trò không thể thiếu với sức khỏe con người → health' },
        32: { v: 'Phần La Mã cổ đại.', t: 'from which we derived the English word salary.', p: 'Từ salary trong tiếng Anh bắt nguồn từ salarium argentum (tiền trả cho lính La Mã) → salary' },
        33: { v: 'Phần Thụy Điển cổ.', t: 'Many families in Sweden began to raise animals in the surrounding forests during the summer', p: 'Gia súc được nuôi trong rừng xung quanh vào mùa hè, khi thời tiết thích hợp → forest' },
        34: { v: 'Ngay sau đó.', t: 'And that was the only month when ancient Swedish people had fresh meat on their table.', p: 'Gia súc được mổ vào tháng Mười, tháng duy nhất có thịt tươi → October' },
        35: { v: 'Khi nói về bằng chứng muối được dùng rộng rãi.', t: "recorded the Swedish king's everyday meals", p: 'Tài liệu năm 1573 ghi lại bữa ăn hằng ngày của vua Thụy Điển: phần lớn thịt được ướp muối → king' },
        36: { v: 'Ngay sau đó.', t: 'the documents also noted the annual sales of beer in Sweden soared during that period and this must be related to high levels of salt in their food.', p: 'Doanh số bia tăng vọt vì đồ ăn quá mặn → beer' },
        37: { v: 'Phần nguồn muối.', t: 'On the floor of the latter often lie deserts where traces of salt can be found, such as the Sahara.', p: 'Hai nguồn chính là đại dương và các lòng chảo; dưới đáy lòng chảo thường là sa mạc chứa muối → deserts' },
        38: { v: 'Khi so sánh muối nước suối với muối biển.', t: 'We can hardly find any impurities and the salt level is much more concentrated.', p: 'Muối từ nước suối gần như không tạp chất và đậm đặc hơn → concentrated' },
        39: { v: 'Phần phân phối muối ở Thụy Điển cổ.', t: 'The Swedish had to attach great importance to shipping and keep it undamaged as it was the most crucial way at that time.', p: 'Thụy Điển phải nhập muối và bảo vệ đường vận tải biển, cách quan trọng nhất thời đó → shipping' },
        40: { v: 'Phần các nước cổ đại khác.', t: 'And gradually these people were considered as a mode of transport in early times.', p: 'Những người vác muối trên vai dần được xem như một phương tiện vận chuyển → transport' },
      },
    },
  ],
};
