// Vol 1 – Test 5 (PDF "Test 5 .pdf" p1–5, key p21–22; audio test 5/Part 1–4.mp3; transcript Tapscript Test 5.docx)
// PART 1 ("New Guinea") = Mindset for IELTS Level 3 track 67 — not in the folder; thầy 2026-10-07 gave the source
// (tutorlistening.com/blog/new-guinea-listening → "part 1.mp3"), saved as test 5/Part 1.mp3 with the spoken
// "Track 67." cut off the start. The docx has no "Part one" marker → rawFix adds one so splitParts finds the part.
// Source errors fixed: Q4 "who have had [4] no with neighbouring groups" (stray "no"; key "no contact"); Q6 "to
// resemble [6] order to frighten off other tribes in" (→ "in order to"); Q10 "the replacement [10] of dyes … with
// artificial ones" with key "replacement of natural dyes" (the sentence already has both → gap = "natural");
// "Mount Hagan" (→ Hagen); docx "a tribe of about 14,000" (PDF + recording: 40,000).
// Q21-22 options D and E were the same ("electricity production is affected") → 4 options A–D,
// key B + the electricity option; Q23-26 header said "Questions 21-24"; key "sliver" (→ silver).
const { note, table, mc, multi, map, matching, short } = require('../vol_build');

module.exports = {
  vol: 1, test: 5,
  rawFix: [['Speaker 2 [00:00:02] You will hear a talk about the island of New Guinea', 'Speaker 2 [00:00:02] Part one, you will hear a talk about the island of New Guinea']],
  sections: [
    {
      part: 1, title: 'New Guinea', audio: 'test 5/Part 1.mp3', cover: 'Papua New Guinea Huli wigmen | Mount Hagen show',
      fix: [['the Indonesian administered provinces', 'the Indonesian-administered provinces'],
        ['home to hundreds of traditional tribes. Perhaps better described as distinct social groups, each one', 'home to hundreds of traditional tribes, perhaps better described as distinct social groups, each one'],
        ['the provinces of Papua and West Papua. There are 312 different tribes', 'the provinces of Papua and West Papua, there are 312 different tribes'],
        ['Huli wig men, a tribe of about 14,000 from the Tari highlands', 'Huli Wigmen, a tribe of about 40,000 from the Tari Highlands'],
        ['Highland tribe, the Asaro mud men, have the same intention as the Huli Wickman to ward off outsiders by smearing themselves in clay and mud. They adopt the form of the river spirits',
          'Highland tribe, the Asaro Mudmen, have the same intention as the Huli Wigmen, to ward off outsiders. By smearing themselves in clay and mud, they adopt the form of the river spirits'],
        ['Their elaborate appearances further supplemented with extended fingernails. And they wear', 'Their elaborate appearance is further supplemented with extended fingernails, and they wear'],
        ['The Asaro mud men were discovered', 'The Asaro Mudmen were discovered'],
        ['A third tribe that has become well-known is the timber who live high in the mountains. The chimp boo skeleton dancers', 'A third tribe that has become well-known is the Chimbu, who live high in the mountains. The Chimbu skeleton dancers'],
        ['male, female segregated houses', 'male-female segregated houses'],
        ['This group, to now display', 'This group, too, now display'],
        ['the Mount Hagen Sing Sing takes place every year involving', 'the Mount Hagen Sing Sing, takes place every year, involving'],
        ['So in 1961 it came up with', 'So, in 1961, it came up with'],
        ['showcase its fascinating cultural heritage at this event. Tourists and locals alike', 'showcase its fascinating cultural heritage. At this event, tourists and locals alike'],
        ['six feet high headdresses', 'six-feet-high headdresses']],
      groups: [
        note('Complete the sentences below.\nWrite NO MORE THAN TWO WORDS for each answer.', 'New Guinea', [
          '1. The eastern side of the island of New Guinea, Papua New Guinea, became an __Q1__ in 1975.',
          '2. Only 18% of the inhabitants of Papua New Guinea reside in __Q2__.',
          '3. Papua New Guinea tribes should be seen as separate __Q3__.',
          '4. There are a small number of tribes who have had __Q4__ with neighbouring groups and the world beyond.',
        ], { 1: 'independent country', 2: 'urban areas', 3: 'social groups', 4: 'no contact' }, 'Questions 1-4'),
        note('Complete the notes below.\nWrite NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.', 'Tribes of Papua New Guinea', [
          '<strong>Huli Wigmen</strong>',
          '• 40,000 members',
          '• decorate their faces with __Q5__',
          '• have belts of pigtails, aprons of leaves, wigs made of own hair',
          '• do dances which imitate local birds',
          '<strong>Asaro Mudmen</strong>',
          '• cover their bodies in mud to resemble __Q6__ in order to frighten off other tribes',
          '• have very long fingernails',
          '• put on __Q7__ to make themselves look fiercer',
          '<strong>Chimbu skeleton dancers</strong>',
          '• men and women used to live in separate houses',
          '• now families live together',
          '• now perform dances for the benefit of __Q8__',
          '<strong>Mount Hagen Sing-Sing</strong>',
          '• over 50 tribes take part',
          '• begun by __Q9__ in 1961 to bring together tribes in peace',
          '• tribespeople wear headdresses made of flowers, shells and feathers',
          '• some loss of authenticity, such as the replacement of __Q10__ dyes on their wonderful costumes with artificial ones',
        ], { 5: 'yellow paint', 6: 'river spirits/the river spirits', 7: 'terrifying masks/masks', 8: 'tourists', 9: 'the government/government', 10: 'natural' }, 'Questions 5-10'),
      ],
      expl: {
        1: { v: 'Phần giới thiệu vị trí và lịch sử đảo New Guinea.', t: 'Since 1975, the eastern side has been the independent country of Papua New Guinea', p: 'Từ năm 1975, phía đông đảo là quốc gia độc lập Papua New Guinea → independent country' },
        2: { v: 'Ngay sau đó, khi nói về dân số.', t: 'Papua New Guinea has 7 million inhabitants and is an incredibly rural country with only 18% of the population living in urban areas.', p: '“Reside in” = living in; chỉ 18% dân số sống ở khu đô thị → urban areas' },
        3: { v: 'Khi nói về các bộ tộc truyền thống.', t: 'perhaps better described as distinct social groups, each one numbering hundreds or even thousands of members.', p: '“Distinct” = separate; các bộ tộc nên được xem là những nhóm xã hội riêng biệt → social groups' },
        4: { v: 'Khi nói về các bộ tộc ở phần lãnh thổ Indonesia.', t: "These are tribes who up until now hadn't had any contact with the outside world, even with other neighboring tribes.", p: 'Khoảng 44 bộ tộc “uncontacted” chưa từng tiếp xúc với thế giới bên ngoài, kể cả bộ tộc láng giềng → no contact' },
        5: { v: 'Bộ tộc đầu tiên: Huli Wigmen.', t: 'They have given their faces a very distinctive look by using yellow paint', p: 'Họ trang trí khuôn mặt bằng sơn vàng → yellow paint' },
        6: { v: 'Bộ tộc thứ hai: Asaro Mudmen.', t: 'By smearing themselves in clay and mud, they adopt the form of the river spirits, which are known to terrify their enemies.', p: 'Bôi đất sét và bùn để mang hình dạng “thần sông”, khiến kẻ thù khiếp sợ → river spirits' },
        7: { v: 'Ngay sau đó, vẫn nói về Asaro Mudmen.', t: 'they wear terrifying masks which serve to accentuate their ferocious look.', p: 'Họ đeo mặt nạ đáng sợ để trông dữ tợn hơn (“fiercer” = ferocious) → terrifying masks' },
        8: { v: 'Bộ tộc thứ ba: vũ công bộ xương Chimbu.', t: 'This group, too, now display their traditional dances, not to scare off other tribes, but more to entertain tourists.', p: 'Ngày nay họ múa không phải để dọa bộ tộc khác mà để mua vui cho khách du lịch → tourists' },
        9: { v: 'Phần lễ hội Mount Hagen Sing Sing.', t: 'This came about due to the constant fighting between tribes, which became a serious problem for the Papua New Guinea government.', p: 'Giao tranh là vấn đề của chính phủ, nên năm 1961 chính phủ (“it”) nghĩ ra lễ hội văn hóa này → government' },
        10: { v: 'Cuối bài, khi nói về sự mất tính nguyên bản.', t: 'For example, chemical dyes are now used instead of the natural ones the tribes used earlier.', p: 'Thuốc nhuộm hóa học (= artificial) thay cho thuốc nhuộm tự nhiên trước đây → natural' },
      },
    },
    {
      part: 2, title: 'Photographing Red Squirrels', audio: 'test 5/Part 2.mp3', cover: 'red squirrel | Sciurus vulgaris',
      fix: [['Welcome, Daryn.', 'Welcome, Darren.'], ['Its Latin name, Sirus Vulgaris,', 'Its Latin name, Sciurus vulgaris,'], ['the number of nuts available. The Red Squirrels Primary Food Source.', "the number of nuts available, the red squirrel's primary food source."],
        ['to cite red squirrels on a regular basis', 'to sight red squirrels on a regular basis'], ['Normally an image is center of interest, is placed at one of the intersections that transact the whole picture', "Normally an image's centre of interest is placed at one of the intersections that dissect the whole picture"],
        ['This helps create a 3-D effect in the picture to further improve on your photography skills. It is advised', 'This helps create a 3-D effect in the picture. To further improve on your photography skills, it is advised']],
      speakers: { 2: 'Presenter', 3: 'Darren' },
      groups: [
        mc('Choose the correct letter, A, B or C.', [
          [11, 'What does Darren now think about the Latin name of the red squirrel?', ['It is suitable for this species.', 'It is meaningless.', 'It is an amusing description.'], 'A'],
          [12, 'The number of red squirrels is reduced due to', ['the invasion of an exotic species.', 'a disease brought by the exotic species.', 'the declining food supply.'], 'C'],
          [13, 'Darren differentiates red squirrels from rats by', ['their food category.', 'how the food was eaten.', 'the way they stored food.'], 'B'],
          [14, 'What was the restriction on Darren’s photography?', ['He could only take photos of one species at a time.', 'He could only use one camera.', 'He could only take photographs in a certain location.'], 'C'],
          [15, 'Why is Darren confident about his photographs?', ['He practised a lot.', 'His teacher prepared him well.', 'He had high-quality equipment.'], 'B'],
        ], 'Questions 11-15'),
        note('Complete the notes below.\nWrite NO MORE THAN THREE WORDS for each answer.', '', [
          '• The photos will be exhibited in a __Q16__.',
          '• Darren’s photos once won a competition held by a __Q17__.',
          '<strong>Ways to improve photography skills:</strong>',
          '• Some pictures need a so-called __Q18__ in the scene.',
          '• Darren thinks the lighting is best late in the __Q19__.',
          '• To take better photos, photographers should make __Q20__.',
        ], { 16: 'local museum', 17: 'national newspaper', 18: 'secondary object', 19: 'afternoon', 20: 'detailed notes' }, 'Questions 16-20'),
      ],
      expl: {
        11: { v: 'Khi Darren nói về tên Latin của sóc đỏ.', t: 'At first I thought this description was funny and was kind of an exaggeration, but now I realize that this name suits them very well.', p: 'Lúc đầu thấy buồn cười (bẫy C), giờ anh thấy cái tên rất hợp với loài này → A' },
        12: { v: 'Khi nói về số lượng sóc đỏ giảm.', t: 'The shrinking population actually corresponds to decreases in the number of nuts available', p: 'Số lượng đã giảm trước khi dịch bệnh lan tới (loại B); nguyên nhân là nguồn hạt, thức ăn chính, ít đi → C' },
        13: { v: 'Khi Darren kể chuyện để quên hạt trong vườn.', t: 'Rats bite a hole in the nuts, whereas red squirrels crack the nuts in half and eat the kernels.', p: 'Chuột có loại thức ăn tương tự (loại A); khác biệt ở cách ăn hạt → B' },
        14: { v: 'Khi nói về hạn chế khi chụp ảnh.', t: 'Unfortunately, I had to shoot only in my garden', p: 'Anh chỉ chụp được trong vườn nhà mình → một địa điểm nhất định; chim đôi khi lọt khung hình (loại A) → C' },
        15: { v: 'Khi nói về sự hài lòng với ảnh.', t: 'I got great tutorials from him and was able to shoot better photos.', p: 'Anh chỉ tập vài lần (loại A), dùng máy ảnh cũ của bạn (loại C); người thầy hướng dẫn rất tốt → B' },
        16: { v: 'Khi nói về triển lãm.', t: 'The award winning photos will be on display in a local museum for the coming month.', p: 'Ảnh đoạt giải trưng bày ở bảo tàng địa phương → local museum' },
        17: { v: 'Khi nói về giải thưởng.', t: 'I sent my portfolio for the competition hosted by a national newspaper.', p: 'Cuộc thi do một tờ báo quốc gia tổ chức → national newspaper' },
        18: { v: 'Mẹo thứ nhất: bố cục.', t: 'A secondary object, so to speak, can be added to the scene at the opposing intersection.', p: 'Thêm một “vật thể phụ” ở giao điểm đối diện (quy tắc một phần ba) → secondary object' },
        19: { v: 'Mẹo thứ hai: ánh sáng.', t: 'lighting is most ideal in the late afternoon.', p: 'Ánh sáng lý tưởng nhất vào cuối buổi chiều → afternoon' },
        20: { v: 'Mẹo thứ ba.', t: 'it is advised to take detailed notes of timing, position, weather, etc.', p: 'Nên ghi chép chi tiết thời gian, vị trí, thời tiết → detailed notes' },
      },
    },
    {
      part: 3, title: 'Water Hyacinth Research', audio: 'test 5/Part 3.mp3', cover: 'water hyacinth | Eichhornia crassipes',
      speakers: { 2: 'Tutor', 4: 'John' },
      fix: [['and are brought huge environmental', 'and have brought huge environmental'], ['clogging the dam at the power station West Africa', 'clogging the dams of power stations in West Africa'], ['It is spread mainly to the tropics and subtropics from much of the world since the 1800s.', 'It has spread to much of the tropics and subtropics of the world since the 1800s.'], ['being sold in local markets and African countries', 'being sold in local markets in African countries'],
        ['contribute significantly to the rapid proliferation', 'contributes significantly to the rapid proliferation'], ['which indirectly compound this issue', 'which indirectly compounds this issue'], ['Among them, biological control, is the most', 'Among them, biological control is the most'],
        ["However, water hyacinth won't be removed and immediately the side effects", "However, water hyacinth won't be removed immediately and the side effects"], ['harvesting plants and inside cutting', 'harvesting plants and on-site cutting']],
      groups: [
        multi('Choose TWO letters, A-D.', 21, 'Which TWO problems are caused by water hyacinth?', ['Plants and fish are poisoned.', 'Farmers cannot fish.', 'The dam’s structure is damaged.', 'Electricity production is affected.'], ['B', 'D'], 'Questions 21-22'),
        mc('Choose the correct letter, A, B or C.', [
          [23, 'Where was water hyacinth originally from?', ['Latin America', 'Africa', 'Europe'], 'A'],
          [24, 'What is the primary cause of the decrease in nutrients from the soil?', ['soil erosion', 'a change in rainfall', 'loss of trees'], 'C'],
          [25, 'When will the biological solution bring risks to the environment?', ['immediately', '6 months later', 'many years later'], 'C'],
          [26, 'What does John say about the mechanical solution?', ['It is ineffective.', 'It is dangerous.', 'It is expensive.'], 'C'],
        ], 'Questions 23-26'),
        matching('What is the benefit of the cut-down water hyacinth to each of the following aspects?\nChoose FOUR answers from the box and write the correct letter, A-F, next to Questions 27-30.',
          ['can reduce the effect of global warming', 'can be used as an alternative energy resource', 'can make quick profits', 'can produce materials for plants to grow in', 'can be good for human health', 'can produce fertiliser'],
          [[27, 'dried water hyacinth', 'D'], [28, 'mushroom farmers', 'C'], [29, 'oyster and straw mushrooms', 'E'], [30, 'cows', 'B']], { title: 'Benefits of the cut-down water hyacinth', groupTitle: 'Questions 27-30' }),
      ],
      expl: {
        21: { v: 'Khi John giải thích vì sao ai cũng ghét bèo tây.', t: 'Farmers cannot travel in boats on the water and thus cannot fish in it.', p: 'Nông dân không thể đi thuyền nên không đánh cá được → B' },
        22: { v: 'Như câu 21 (chọn 2 đáp án).', t: 'Dams often cease to function as a result, severely restricting the electricity generation.', p: 'Bèo làm tắc đập, tua-bin phải dừng → sản xuất điện bị ảnh hưởng; cấu trúc đập không bị hư (loại C), cá chết vì thiếu oxy chứ không bị đầu độc (loại A) → D' },
        23: { v: 'Khi hỏi bèo tây có nguồn gốc từ đâu.', t: 'The water hyacinth is native to the Amazon basin in Latin America.', p: 'Bèo tây có nguồn gốc ở lưu vực sông Amazon, Mỹ Latinh; châu Âu và châu Phi là nơi nó được đưa tới sau (bẫy) → A' },
        24: { v: 'Khi hỏi vì sao đất ven sông mất chất dinh dưỡng.', t: 'The main reason for soil nutrient loss is that local residents cut down trees.', p: 'Nguyên nhân chính là chặt cây; xói mòn và mưa chỉ làm vấn đề nặng thêm → C' },
        25: { v: 'Khi nói về biện pháp sinh học.', t: 'the side effects of this method on local ecology will remain unforeseen for years', p: '6 tháng là thời gian Nigeria đã áp dụng (bẫy B); tác hại với hệ sinh thái chỉ lộ ra sau nhiều năm → C' },
        26: { v: 'Khi nói về biện pháp cơ học.', t: 'It is, however, inefficient for workers to process extensive areas and costly to use large cutting and dredging equipment.', p: 'Thiết bị cắt và nạo vét tốn kém, xử lý bèo còn đắt hơn → C' },
        27: { v: 'Phần tận dụng bèo đã cắt.', t: 'The mixture can be used as alternative soil rather than fertilizer.', p: 'Bèo phơi khô trộn tro và phân làm đất trồng thay thế, không phải phân bón (bẫy F) → D' },
        28: { v: 'Nông dân trồng nấm.', t: 'Mushrooms generally grow much faster so that farmers can harvest mushrooms sooner, which enables them to make money faster.', p: 'Nấm lớn nhanh, thu hoạch sớm, kiếm tiền nhanh → C' },
        29: { v: 'Nấm sò và nấm rơm.', t: "These mushrooms provide sufficient nutritional values, including minerals and high quality protein, which are essential to people's level of fitness.", p: 'Nấm giàu khoáng chất và đạm, tốt cho sức khỏe con người → E' },
        30: { v: 'Nuôi bò ở Đông Nam Á.', t: 'Then the waste from the cows is treated to produce methane gas, which can be used as fuel for cooking, lighting or powering an engine.', p: 'Chất thải của bò tạo khí metan làm nhiên liệu → nguồn năng lượng thay thế; nóng lên toàn cầu chỉ là bối cảnh (bẫy A) → B' },
      },
    },
    {
      part: 4, title: 'Nanotechnology and Its Applications', audio: 'test 5/Part 4.mp3', cover: 'nanotubes | nanotechnology microscope',
      fix: [['there is always concern over these are natural products', 'there is always concern over these unnatural products'], ['also known as VHS', 'also known as EHS'], ['on the Nano s research', 'on nanotech research'], ['made of shape, memory alloys', 'made of shape-memory alloys'], ['the effects related sites such as cancer focuses', 'the effect-related sites such as cancer foci'], ['1 to 100 nano meters', '1 to 100 nanometres'], ['A nano meter is one billionth of a meter.', 'A nanometre is one billionth of a metre.']],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'Nanotechnology and Its Applications', [
          '<strong>About nanotechnology</strong>',
          '• It is a study on the scale of nanometres.',
          '• The development in nanotechnology is the result of a new type of __Q31__.',
          '• People are worried that nanotech products are __Q32__.',
          '<strong>Food and household</strong>',
          '• The availability of __Q33__ in our diet (e.g. in potatoes) is greatly improved.',
          '• The packaging cost of __Q34__ is particularly reduced.',
          '• Nanotechnology can increase the __Q35__ of food.',
          '• Nanotechnology can be used to make new types of furniture.',
          '<strong>Agriculture</strong>',
          '• The efficiency of __Q36__ is increased.',
          '<strong>Health and medicine</strong>',
          '• Nanotubes allow more __Q37__ to enter veins.',
          '• As the most popular material, __Q38__ is used to kill bacteria.',
          '• Nanotechnology is also helpful in __Q39__ loss programmes.',
          '<strong>Cosmetics</strong>',
          '• Nanoparticles protect skin from the __Q40__ and help to improve the ability against ageing.',
          '• Nanotechnology helps to deliver effective elements to the skin.',
        ], { 31: 'microscope', 32: 'unnatural', 33: 'iron', 34: 'chocolate', 35: 'flavour/flavor', 36: 'fertilisers/fertilizers/fertiliser/fertilizer', 37: 'drugs', 38: 'silver', 39: 'weight', 40: 'sun' }, 'Questions 31-40'),
      ],
      expl: {
        31: { v: 'Phần lịch sử công nghệ nano.', t: "In fact, it wasn't until 1981, with the invention of a special kind of microscope that modern nanotechnology truly began.", p: 'Công nghệ nano hiện đại chỉ thực sự bắt đầu nhờ phát minh một loại kính hiển vi đặc biệt → microscope' },
        32: { v: 'Khi nói về mối lo ngại.', t: 'there is always concern over these unnatural products.', p: 'Người ta lo ngại về các sản phẩm “không tự nhiên” này → unnatural' },
        33: { v: 'Phần thực phẩm.', t: 'Nanotechnology is leveraged against iron deficiency, which triggers anemia, for example, by reducing the particle size in potatoes.', p: 'Công nghệ nano chống thiếu sắt bằng cách giảm kích thước hạt trong khoai tây → iron' },
        34: { v: 'Khi nói về bao bì.', t: 'Chocolate in particular.', p: 'Vật liệu nano làm bao bì rẻ hơn, đặc biệt với sô-cô-la → chocolate' },
        35: { v: 'Ngay sau đó.', t: 'Nanotechnology can also enhance the flavor of food.', p: '“Enhance” = increase; tăng hương vị thực phẩm → flavour' },
        36: { v: 'Phần nông nghiệp.', t: 'It offers great potential to strengthen the effect of fertilizers', p: 'Tăng hiệu quả của phân bón → fertilisers' },
        37: { v: 'Phần y học, ống nano carbon.', t: 'because of their ability to efficiently deliver drugs into veins.', p: 'Ống nano đưa thuốc vào tĩnh mạch hiệu quả, cho phép liều cao hơn → drugs' },
        38: { v: 'Khi nói về vật liệu phủ bề mặt.', t: 'It is mainly comprised of silver.', p: 'Vật liệu được chấp nhận rộng rãi chủ yếu làm từ bạc, có tính sát khuẩn → silver' },
        39: { v: 'Khi nói về sức khỏe và trao đổi chất.', t: 'Therefore, treatment programs are provided for patients to lose weight', p: 'Chương trình điều trị giúp bệnh nhân giảm cân → weight' },
        40: { v: 'Phần mỹ phẩm.', t: 'nanoparticles are commonly used as UV filters in anti-aging suncare products to avoid skin damage caused by the sun.', p: 'Hạt nano chống tia UV, bảo vệ da khỏi ánh nắng mặt trời → sun' },
      },
    },
  ],
};
