// Vol 1 – Test 6 (PDF "Test 6 .pdf" p1–6, key p22; audio test 6/Part 1–4.mp3; transcript Tapscript Test 6.docx)
const { note, table, mc, multi, map, matching, short } = require('../vol_build');

module.exports = {
  vol: 1, test: 6,
  sections: [
    {
      part: 1, title: 'Tour Booking Enquiry', audio: 'test 6/Part 1.mp3', cover: 'surfing beach | surfer wave',
      speakers: { 1: 'Agent', 2: 'Customer' },
      fix: [['by the hour day or we just book it', 'by the hour, day or week. Just book it'], ["I think I'll pick a trip", "I think I'll book a trip"], ["I'll write you a check then", "I'll write you a cheque then"], ['Does the hotel have any recreational facilities?', 'Does the hotel have any recreational facilities?']],
      groups: [
        table('Complete the table below.\nWrite ONE WORD AND/OR A NUMBER for each answer.', ['Tour Booking Enquiry', ''], [
          ['<strong>Type of holiday</strong>', '__Q1__'],
          ['<strong>Hotel</strong>', '• Meal: including __Q2__<br>• Facilities: a pool, a nightclub and a __Q3__<br>• Prices: reduce from € __Q4__ to €315'],
          ['<strong>Self-catering apartment</strong>', 'Stay in a __Q5__ room'],
          ['<strong>Equipment rental</strong>', 'Rental for one week: € __Q6__'],
          ['<strong>Types of insurance</strong>', '• __Q7__ cover: €30<br>• Premier cover: € __Q8__'],
          ['<strong>Transport</strong>', 'The cheapest way of going to the airport: by __Q9__'],
          ['<strong>Payment method</strong>', 'Pay by __Q10__: no extra fee'],
        ], { 1: 'surfing', 2: 'breakfast', 3: 'gym', 4: '360', 5: 'shared', 6: '75', 7: 'basic', 8: '42.50/42.5', 9: 'taxi', 10: 'cheque/check' }, 'Questions 1-10'),
      ],
      expl: {
        1: { v: 'Đầu bài, khi nhân viên hỏi khách muốn loại chuyến đi nào.', t: 'Well, I enjoy surfing very much and want to get tanned, but all my friends suggest either mountain climbing or biking.', p: 'Bạn bè gợi ý leo núi hoặc đạp xe (bẫy), nhưng khách thích lướt sóng và nhân viên khuyên “follow your heart” → surfing' },
        2: { v: 'Khi hỏi giá khách sạn đã bao gồm gì.', t: 'It covers the beach side, hotel and free breakfast.', p: 'Giá trọn gói gồm khách sạn ven biển và bữa sáng miễn phí → breakfast' },
        3: { v: 'Khi hỏi tiện ích giải trí của khách sạn.', t: 'Oh, rest assured, the hotel is fully equipped with a pool, a nightclub and a gym.', p: 'Hồ bơi, hộp đêm và phòng tập thể dục → gym' },
        4: { v: 'Khi hỏi giá khách sạn.', t: ['Well, it was originally €360 for an adult, but we are now offering a Labour Day promotion.', "so that's €315 for now."], p: 'Giá gốc €360, giảm 12,5% còn €315; đề hỏi giá trước khi giảm → 360' },
        5: { v: 'Khi nói về căn hộ tự nấu ăn.', t: 'But you have to stay in a shared room with other guests.', p: 'Căn hộ rẻ hơn nhưng phải ở phòng chung với khách khác (6 giường tầng) → shared' },
        6: { v: 'Khi hỏi giá thuê ván lướt sóng.', t: "It costs €15 for a day, but for a week's rental, it's just €75.", p: '€15 là giá một ngày (bẫy); thuê cả tuần chỉ €75 → 75' },
        7: { v: 'Phần bảo hiểm, loại thứ nhất.', t: ['The first one is basic coverage.', 'It costs €30.'], p: 'Gói bảo hiểm €30 là gói cơ bản → basic' },
        8: { v: 'Ngay sau đó, loại bảo hiểm thứ hai.', t: 'It is more expensive at €42.50, but we highly recommend this one for regular surfers.', p: 'Premier cover đắt hơn, giá €42.50 → 42.50' },
        9: { v: 'Khi nói về cách ra sân bay.', t: "Actually, I personally suggest you take a taxi. It's much cheaper than other types of transport, including the airport shuttle.", p: 'Khách định đi xe buýt sân bay nhưng nhân viên nói taxi rẻ hơn mọi phương tiện khác → taxi' },
        10: { v: 'Cuối bài, khi hỏi cách thanh toán.', t: "If you pay by cheque, there's no extra fee.", p: 'Thẻ tín dụng bị tính phí thêm (bẫy); trả bằng séc thì không mất phí → cheque' },
      },
    },
    {
      part: 2, title: 'Community Centre Dance Workshops', audio: 'test 6/Part 2.mp3', cover: 'dance class studio | dancers rehearsal',
      fix: [['complimentary show. Back to store your dance shoes.', 'complimentary shoe bag to store your dance shoes.'], ['On behalf of all community centre', 'On behalf of our community centre'], ['dance. For the past few decades, then will warm up', "dance for the past few decades. Then we'll warm up"], ['whenever the studio is available in the first afternoon and evening of your dance class. There will be an introduction', 'whenever the studio is available. In the first afternoon and evening of your dance class, there will be an introduction'], ['You can explore it well later during art or further ahead in the corner. There are the bike racks.', 'You can explore it later during our tour. Further ahead in the corner, there are the bike racks.'], ['If you want a ride, the first hour is free.', 'If you want to ride, the first hour is free.'], ["We are standing here right at the entrance to your left. You can see two rooms in a row after each dance session. You're probably", "We are standing here right at the entrance. To your left, you can see two rooms in a row. After each dance session, you're probably"], ['where you were standing right before', 'where you are standing, right before']],
      groups: [
        multi('Choose TWO letters, A-E.', 11, 'Which TWO items will participants receive when they check in?', ['a class list', 'a face towel', 'a name tag', 'a shoe bag', 'a water bottle'], ['A', 'D'], 'Questions 11-12'),
        multi('Choose TWO letters, A-E.', 13, 'Which TWO activities will be hosted in the first afternoon and evening?', ['costume making', 'a musical show', 'an informal dance', 'a talk on dance history', 'a dance test'], ['C', 'D'], 'Questions 13-14'),
        map('Label the plan below.\nWrite the correct letter, A-J, next to Questions 15-20.', [[15, 'shower room', 'C'], [16, 'bunkroom', 'E'], [17, 'games room', 'I'], [18, 'reception', 'F'], [19, 'medical centre', 'D'], [20, 'store', 'B']], { page: 3, box: [100, 100, 470, 305] }, 'Questions 15-20'),
      ],
      expl: {
        11: { v: 'Khi nói về lúc học viên check-in buổi đầu.', t: ['they will be given a class list printed with available seasonal classes', 'The dance studio will also give you a complimentary shoe bag to store your dance shoes.'], p: 'Học viên được phát danh sách lớp và một túi đựng giày miễn phí; khăn mặt và bình nước phải tự mang, thẻ tên gửi qua bưu điện → A' },
        12: { v: 'Như câu 11 (chọn 2 đáp án).', t: 'The dance studio will also give you a complimentary shoe bag to store your dance shoes.', p: 'Món thứ hai được phát khi check-in là túi đựng giày (shoe bag) → D' },
        13: { v: 'Khi giới thiệu hoạt động buổi chiều và tối đầu tiên.', t: "Then we'll warm up with an informal dance.", p: 'Buổi đầu có màn khởi động bằng một điệu nhảy tự do; làm trang phục để ngày mai, bài kiểm tra để cuối khoá → C' },
        14: { v: 'Như câu 13 (chọn 2 đáp án).', t: 'there will be an introduction to the development of dance for the past few decades.', p: '“Introduction to the development of dance” = bài nói về lịch sử khiêu vũ → D' },
        15: { v: 'Phần sơ đồ, khi nói về phòng tắm.', t: 'Just go straight ahead, turn left and the shower room is on your left hand side.', p: 'Từ lối vào đi thẳng, rẽ trái, phòng tắm nằm bên tay trái → C' },
        16: { v: 'Ngay sau đó, phòng ngủ giường tầng.', t: "It's immediately to the left of where you are standing, right before the shower room.", p: 'Phòng giường tầng ở ngay bên trái chỗ đứng, trước phòng tắm → E' },
        17: { v: 'Khi nói về phòng trò chơi.', t: 'Just take the first right. It is the second area to your right.', p: 'Rẽ phải ở lối đầu tiên, khu thứ hai bên phải → I' },
        18: { v: 'Khi nói về quầy lễ tân.', t: 'The reception is located in the centre to the south of the Music Room.', p: 'Lễ tân ở giữa, phía nam phòng nhạc → F' },
        19: { v: 'Khi nói về trạm y tế.', t: "It's right opposite the reception to the left of the music room.", p: 'Đối diện lễ tân, bên trái phòng nhạc → D' },
        20: { v: 'Khi nói về cửa hàng đồ ăn.', t: "Keep straight on until you get to the third passageway. Turn right and it's the one after the gym", p: 'Đi thẳng tới lối thứ ba, rẽ phải, là phòng ngay sau phòng gym → B' },
      },
    },
    {
      part: 3, reuse: '6a5129c52bf801f4090e8111', // = bank "Assignment Notes & Presentation Guidance" (Actual Test 11 P3)
      title: 'Assignment Feedback', audio: 'test 6/Part 3.mp3', cover: 'university tutor student meeting | student essay',
      speakers: { 1: 'Karen', 2: 'Tutor' },
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'Assignment Feedback', [
          '<strong>Things that need to be done:</strong>',
          '• Hand in book reports with the next assignment',
          '• Check accuracy of the __Q21__ in the last section',
          '• Give more __Q22__',
          '• Expand ideas to improve the grade',
        ], { 21: 'references', 22: 'examples' }, 'Questions 21-22'),
        short('Answer the questions below.\nWrite NO MORE THAN THREE WORDS for each answer.', [
          [23, 'When will Karen give her presentation?', 'next seminar/the next seminar/at the next seminar/at next seminar'],
          [24, 'What must she do during the presentation?', 'explain the experiment/explain experiment'],
          [25, 'By which date does she have to submit an abstract?', '26th November/26 November/November 26/November 26th/26th of November'],
          [26, 'Where will the presentation take place?', 'chemistry lab/the chemistry lab/in the chemistry lab'],
          [27, 'Who will grade her presentation?', 'professor/the professor'],
        ], 'Questions 23-27'),
        multi('Choose THREE letters, A-H.', 28, 'Which THREE modules will Karen study next year?', ['Communication Skills', 'Data Collection', 'Discourse Analysis', 'Language and Society', 'Phonology', 'Psycholinguistics', 'Research Methodology', 'Social Interaction'], ['A', 'C', 'F'], 'Questions 28-30'),
      ],
      expl: {
        21: { v: 'Khi gia sư nói về lỗi trích dẫn.', t: "Don't forget to go through and make sure that your references are accurate.", p: 'Phải kiểm tra độ chính xác của phần tài liệu tham khảo → references' },
        22: { v: 'Ngay sau đó.', t: 'it might be helpful if you could include a few other examples just to drive your point home.', p: 'Gia sư muốn Karen thêm vài ví dụ để làm rõ luận điểm → examples' },
        23: { v: 'Khi Karen hỏi khi nào thuyết trình.', t: 'So you agreed to do it at the next seminar.', p: 'Karen tưởng là học kỳ sau (bẫy), nhưng thực ra cô đã nhận làm ở buổi seminar tới → next seminar' },
        24: { v: 'Khi hỏi phần quan trọng nhất của bài thuyết trình.', t: "So it's absolutely essential for you to explain the experiment.", p: 'Bắt buộc phải giải thích thí nghiệm; phần tóm tắt chỉ là tuỳ chọn → explain the experiment' },
        25: { v: 'Khi nói về bản tóm tắt (abstract).', t: "Now they'll need to be done by the 3rd of December, so I'll need to see it by the 26th of November, if that's okay.", p: 'Ngày 3/12 là hạn in tài liệu (bẫy); hạn nộp abstract cho gia sư là 26/11 → 26th November' },
        26: { v: 'Khi bàn chỗ thuyết trình.', t: "So we'll have to go across the road and do it in the chemistry lab.", p: 'Phòng máy tính không phù hợp (bẫy), nên sẽ làm ở phòng thí nghiệm hoá → chemistry lab' },
        27: { v: 'Khi Karen hỏi ai chấm điểm.', t: 'Your first one was graded by your tutor, but this one will be scored by the professor.', p: 'Bài trước do gia sư chấm, bài này do giáo sư chấm → professor' },
        28: { v: 'Cuối phần 3, khi Karen kể các môn chọn cho năm sau.', t: 'Anyway, I went for communication skills in the end because I know the lecturer.', p: 'Phân vân giữa Language and Society và Communication Skills, cuối cùng chọn Communication Skills → A' },
        29: { v: 'Như câu 28 (chọn 3 đáp án).', t: "So I thought I'd do that rather than the full methodology course.", p: 'Chọn Discourse Analysis vì có cả một phần Research Methodology; Data Collection đã học, Social Interaction trùng nội dung → C' },
        30: { v: 'Như câu 28 (chọn 3 đáp án).', t: 'So I thought psycho linguistics would be interesting.', p: 'Môn thứ ba là Psycholinguistics; Phonology chỉ được nhắc đến như phương án khác và gia sư đồng ý với lựa chọn của cô → F' },
      },
    },
    {
      part: 4, title: 'Research on Birds in Australia', audio: 'test 6/Part 4.mp3', cover: 'peregrine falcon | kestrel bird',
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'Research on birds in Australia', [
          '<strong>The study by Cunningham in 1995</strong>',
          'It aimed to study birds which were __Q31__ in cities',
          '<strong>Methodology</strong>',
          '• Researchers were able to __Q32__ rather than count the number of birds, using methods such as random sampling.',
          '• Researchers studied birds’ companionship habits using a __Q33__ system.',
          '• Researchers attached tags to birds’ legs to identify their __Q34__ over time.',
          '<strong>Findings</strong>',
          '• Birds tended to choose the same nesting site in which they were raised.',
          '• Human activities such as __Q35__ had a negative effect on the reproduction of birds.',
          '<strong>Measures taken by local organisations</strong>',
          '• To increase birds’ rate of __Q36__ in various ways',
          '• To reduce the dangers caused by __Q37__ farms, e.g. colliding with turbines',
          '<strong>The study by Conway in 2006</strong>',
          '• Researchers monitored the __Q38__ of birds’ nocturnal calls during flight.',
          '• __Q39__ were taken to listen to birds’ sounds.',
          '• Data could be collected through noise detection devices placed at a great __Q40__.',
        ], { 31: 'protected', 32: 'estimate', 33: 'mapping', 34: 'trends', 35: 'pollution', 36: 'survival', 37: 'wind', 38: 'frequency', 39: 'recordings', 40: 'distance' }, 'Questions 31-40'),
      ],
      expl: {
        31: { v: 'Phần giới thiệu nghiên cứu của Cunningham (1995).', t: 'especially those protected species in urban regions.', p: '“Urban regions” = cities; nghiên cứu tập trung vào các loài chim được bảo vệ → protected' },
        32: { v: 'Phần phương pháp.', t: 'Instead, they managed to estimate with various standard distance sampling methods, like random sampling.', p: 'Thay vì đếm bằng ống nhòm, họ ước tính bằng phương pháp lấy mẫu → estimate' },
        33: { v: 'Ngay sau đó.', t: 'In addition, a mapping system was used to study their companionship behaviour.', p: 'Hành vi bầu bạn được nghiên cứu bằng một hệ thống lập bản đồ → mapping' },
        34: { v: 'Khi nói về việc gắn thẻ vào chân chim.', t: 'making it possible to assess the trends of birds over 15 months.', p: 'Thẻ phát sóng radio giúp đánh giá xu hướng của chim theo thời gian → trends' },
        35: { v: 'Phần kết quả, tác động của con người.', t: 'found out that pollution had contributed greatly to the declining birth rates of some species', p: 'Ô nhiễm làm giảm tỉ lệ sinh của chim → pollution' },
        36: { v: 'Phần biện pháp của các tổ chức địa phương.', t: 'A number of measures were thus taken by members from local animal conservation organisations to boost their alarming survival rates.', p: '“Boost” = increase; các biện pháp nhằm nâng tỉ lệ sống sót → survival' },
        37: { v: 'Ngay sau đó.', t: 'A further measure was taken to ensure the safety of birds from wind farms.', p: 'Bảo vệ chim khỏi các trang trại điện gió (va vào tuabin) → wind' },
        38: { v: 'Phần nghiên cứu của Conway (2006).', t: 'His team detected the calling frequency of seabirds flying at night.', p: 'Nhóm theo dõi tần suất tiếng kêu của chim biển bay ban đêm → frequency' },
        39: { v: 'Khi nói về cách thu âm thanh.', t: 'Surveyors also took recordings of the sounds of all the individual birds detected.', p: 'Người khảo sát thu âm tiếng kêu của từng con chim → recordings' },
        40: { v: 'Ngay sau đó.', t: 'All the sounds were recorded from a distance, using microphones to detect noise.', p: 'Âm thanh được thu từ xa bằng micro → distance' },
      },
    },
  ],
};
