// Vol 2 – Test 1 (PDF "listening/test 1/Test 1.pdf" p1–6, key p7; audio test 1/part 1–4.mp3)
// Transcripts: P1–P2 Gemini (web/vol2/gemini), P3–P4 Whisper + Otter merge (pN.pdf = Otter.ai).
// Source errors fixed: key Q35 "affordable" / Q36 "flashing" are shifted — the recording gives 35 exhibitions,
// 36 affordable ("flashing" is Part 1 Q6). Q14–17 had no instruction (added, as in the other sentence tasks).
// P2 is another recording of the "Southern Wonders Beach Resort" exam in the bank but its questions and answers
// differ (Q11, Q16, Q18–20) → seeded as its own section.
const { note, table, mc, multi, matching, short } = require('../vol_build');

module.exports = {
  vol: 2, test: 1,
  sections: [
    {
      part: 1, title: 'Eye Problem Consultation', audio: 'listening/test 1/part 1.mp3', cover: 'eye doctor | eye examination',
      fix: [['E-L-2-14-F-B', 'E-L-2-1-4-F-B'], ['E-L-14-2-B-F', 'E-L-1-4-2-B-F'], ["Okay, I'll make a note of that too.\n\nPatient:\nThank you.\n\nDoctor:\nI think", "Okay, I'll make a note of that too.\nThank you.\nI think"]],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD AND/OR A NUMBER for each answer.', 'Consultation', [
          '<strong>Patient Information</strong>',
          'Name: Anu __Q1__',
          'Post code: __Q2__',
          'Current address: __Q3__ Avenue',
          'Birthday: October 1st __Q4__',
          'Phone number: 875934',
          '<strong>Health Condition</strong>',
          'Background: Illness has lasted for __Q5__ days',
          'Symptom: see __Q6__ lights',
          'Possible cause: the room was too __Q7__',
          'Previous hospital: __Q8__ Hospital',
          '<strong>Suggestions</strong>',
          'Have a good rest after staring at a __Q9__ for a long time',
          'Use some medicine to ease eye __Q10__',
        ], { 1: 'Atkinson', 2: 'EL14 2BF/EL142BF', 3: 'Queens/Queen\'s', 4: '1986', 5: '5/five', 6: 'flashing', 7: 'bright', 8: 'Central', 9: 'screen', 10: 'strain' }, 'Questions 1-10'),
      ],
      expl: {
        1: { v: 'Đầu bài, khi bác sĩ hỏi tên và yêu cầu đánh vần họ.', t: ['Could you spell your family name?', 'A-T-K-I-N-S-O-N, Atkinson.'], p: 'Họ (family name) được đánh vần từng chữ → Atkinson' },
        2: { v: 'Khi bác sĩ hỏi mã bưu điện.', t: ["Yes, I think it's E-L-2-1-4-F-B.", "Oh, sorry, it's actually E-L-1-4-2-B-F."], p: 'Mã đọc lần đầu (EL2 14FB) là bẫy; bệnh nhân kiểm tra lại và sửa → EL14 2BF' },
        3: { v: 'Khi hỏi địa chỉ hiện tại.', t: "At the moment, I'm living with my parents on Queen's Avenue.", p: 'Hiện đang sống với bố mẹ ở đại lộ Queen\'s → Queens' },
        4: { v: 'Khi hỏi ngày sinh.', t: ['October 1st, 1986.', 'It\'s my birthday too, but I was born in 1984.'], p: '1984 là năm sinh của bác sĩ (bẫy); bệnh nhân sinh năm 1986 → 1986' },
        5: { v: 'Khi hỏi triệu chứng xuất hiện bao lâu rồi.', t: ['No, it started just three days ago.', 'Oh no, I think it was five days ago in the gym after I played badminton.'], p: '“Ba ngày” bị chính bệnh nhân sửa lại thành năm ngày → 5' },
        6: { v: 'Khi bác sĩ hỏi triệu chứng cụ thể.', t: 'I see these flashing lights.', p: 'Bệnh nhân nhìn thấy những ánh sáng nhấp nháy → flashing' },
        7: { v: 'Khi hỏi tình trạng căn phòng chơi cầu lông.', t: ['Was it very dark?', 'Oh, it was very bright.'], p: 'Bác sĩ đoán phòng tối (bẫy) nhưng thực ra phòng quá sáng → bright' },
        8: { v: 'Khi hỏi từng điều trị ở đâu trước đây.', t: 'Well, I went into Central Hospital last month because of severe headache, and they kept me in for observation for a couple of days, but they couldn\'t find anything wrong.', p: 'Tháng trước bệnh nhân vào bệnh viện Central → Central' },
        9: { v: 'Lời khuyên thứ nhất của bác sĩ.', t: 'If you find yourself looking at a screen for too long, you should look away, focus on a point in the distance for approximately 10 to 20 seconds, and then focus on something closer to you.', p: '“Looking at a screen for too long” = staring at a screen for a long time → screen' },
        10: { v: 'Lời khuyên thứ hai: thuốc nhỏ mắt.', t: ["I'll give you some eye drops.", 'That should reduce levels of eye strain.'], p: '“Reduce” = ease; thuốc nhỏ mắt giúp giảm mỏi mắt (eye strain) → strain' },
      },
    },
    {
      part: 2, title: 'Oceanic Island Travelling', audio: 'listening/test 1/part 2.mp3', cover: 'kangaroo wildlife park | island beach cottages',
      fix: [['Man:\n', '']],
      groups: [
        mc('Choose the correct letter, A, B or C.', [
          [11, 'Where is the information board?', ['At the reception', 'Inside the cottage', 'On the beach'], 'A'],
          [12, 'Which sport do customers have to book in advance?', ['Beach soccer', 'Water-skiing', 'Scuba diving'], 'B'],
          [13, 'What does the cave tour ticket price include?', ['shoes', 'a map of cave', 'safety helmet'], 'C'],
        ], 'Questions 11-13'),
        short('Complete the sentences below.\nWrite NO MORE THAN THREE WORDS AND/OR A NUMBER for each answer.', [
          [14, 'Davison Wildlife Park is a great place for ______', 'families/family'],
          [15, 'Children are allowed to ______', 'feed the animals'],
          [16, 'Red kangaroos are larger than ______', 'adults'],
          [17, 'Crocodiles can live for at least ______', '50 years/fifty years'],
        ], 'Questions 14-17'),
        multi('Choose THREE letters, A-H.', 18, 'Which THREE activities are popular now for tourists in the inland region?', ['hill hiking', 'barbecue and bonfire', 'buying souvenirs', 'visiting emu farm', 'visiting cheese factory', 'following nature trails', 'fruit picking', 'staff'], ['C', 'E', 'G'], 'Questions 18-20'),
      ],
      expl: {
        11: { v: 'Đầu bài, khi nói về bảng thông tin.', t: 'So please remember to check it at the reception area in the front of the visitor centre of the resort.', p: 'Bãi biển và nhà nghỉ chỉ là nơi bạn hoạt động trong ngày (bẫy); bảng thông tin đặt ở khu lễ tân → A' },
        12: { v: 'Khi nói về việc đặt chỗ cho các hoạt động.', t: ['Reservations are not necessary for most activities, such as sand soccer, beach volleyball, and even scuba diving.', 'However, if you are planning to participate in our water skiing activity, we encourage you to book that activity at least 48 hours beforehand'], p: 'Bóng đá bãi biển và lặn không cần đặt trước; riêng lướt ván nước phải đặt trước 48 giờ → B' },
        13: { v: 'Khi nói về giá vé tour hang động.', t: 'All participants are required to wear a safety helmet inside the caves and the ticket has covered that for you.', p: 'Giày phải tự chuẩn bị, bản đồ tốn thêm phí; mũ bảo hiểm đã bao gồm trong giá vé → C' },
        14: { v: 'Khi giới thiệu công viên động vật Davison.', t: 'For those of you interested in visiting the Davison Wildlife Park, you should know that the park is an excellent site for families, though it does attract a lot of zoologists to do some research.', p: '“An excellent site for families” = a great place for families; nhà động vật học chỉ là thông tin phụ → families' },
        15: { v: 'Khi nói về hoạt động dành cho trẻ em.', t: ['In the wildlife park, children can often watch elephant shows, which are really an attraction, but now some elephants are ill and they need some time to recover.', 'They are allowed to feed the animals.'], p: 'Xem voi biểu diễn tạm dừng vì voi ốm (bẫy); trẻ em được phép cho thú ăn → feed the animals' },
        16: { v: 'Khi nói về chuột túi đỏ.', t: 'The size of these kangaroos is similar to that of black bears, but generally, they are bigger than adults', p: 'Kích thước tương đương gấu đen, và nhìn chung to hơn người lớn → adults' },
        17: { v: 'Khi nói về cá sấu.', t: ['These prehistoric animals have a lifespan of over 50 years.', 'A male crocodile can even be expected to live to the age of 80.'], p: '80 tuổi là tuổi thọ của riêng cá sấu đực (bẫy); cá sấu nói chung sống hơn 50 năm → 50 years' },
        18: { v: 'Cuối bài, khi nói về các hoạt động đã thay đổi.', t: 'Instead of going hiking on the hills, most of our tourists prefer to visit many of the gift shops in the area to buy souvenirs for themselves or for family and friends who are not on the tour.', p: 'Leo đồi không còn được ưa chuộng; du khách thích ghé cửa hàng mua quà lưu niệm → C' },
        19: { v: 'Như câu 18 (chọn 3 đáp án).', t: ['The Emu Farm, which has previously been a popular place to visit, is now temporarily closed for business.', 'But, newly available to you is a popular trip offered to the Nelson Cheese Factory'], p: 'Nướng thịt/lửa trại bị cấm, trại đà điểu tạm đóng cửa; chuyến tham quan xưởng phô mai mới mở và được ưa chuộng → E' },
        20: { v: 'Như câu 18 (chọn 3 đáp án).', t: ["At the farm, you will be able to pick strawberries and apples in the farm's orchards and fields.", 'Many tourists enjoy this activity a lot.'], p: 'Đường mòn thiên nhiên chỉ có “in the future” (bẫy); hái dâu, táo ở trang trại St. John\'s rất được yêu thích → G' },
      },
    },
    {
      part: 3, title: 'Food Additives Research Project', audio: 'listening/test 1/part 3.mp3', cover: 'food label ingredients | supermarket shopping',
      speakers: { 1: 'Tutor', 2: 'Tutor', 3: 'Jack' },
      fix: [
        ['Perhaps supermarket managers would be a good starting point.\nYeah,\nJack:\nIt\'s true', 'Perhaps supermarket managers would be a good starting point.\nJack:\nYeah, it\'s true'],
        ['think of 2', 'think of.'],
        ['would have to be stated on the packaging.\nWhat did you find instead?\nIt seems', 'would have to be stated on the packaging.\nTutor:\nWhat did you find instead?\nJack:\nIt seems'],
        ['every day.\nAs the\nTutor:\nCost of food goes up we see', 'every day.\nTutor:\nAs the cost of food goes up, we see'],
        ['It\'s difficult to find the time\n', 'It\'s difficult to find the time.\n'],
        ['first steer students', 'first-year students'],
        ['weigh up, its worth against the time it would take, it wouldn\'t be worth it.', 'weigh up its worth against the time it would take.\nIt wouldn\'t be worth it.'],
        ['Great.\nThanks for your help.', 'Great.\nJack:\nThanks for your help.'],
      ],
      groups: [
        mc('Choose the correct letter, A, B or C.', [
          [21, 'Why did they do it as a team?', ['They needed to do a lot of research.', 'They had worked together before.', 'The research was very complicated.'], 'A'],
          [22, 'Who will be the interviewees at the first stage?', ['manufacturers', 'shoppers', 'managers'], 'B'],
          [23, "What is the manufacturers' top priority on the labels?", ['the weight', 'the ingredients', 'the price'], 'C'],
          [24, 'What result surprised them?', ['There are a lot of additives in food.', 'The cost of food is much higher than before.', 'Fast food is popular among customers.'], 'A'],
          [25, 'What does Jack worry about most regarding the project?', ["They don't have enough respondents.", 'There is not enough time.', 'Some important data is not available.'], 'B'],
        ], 'Questions 21-25'),
        matching("What does the tutor suggest doing with Jack's research regarding each of the following tasks?\nChoose FIVE answers from the box and write the correct letter, A-E, next to Questions 26-30.",
          ['do it with a partner', 'not worthy of doing', 'leave it to others', 'do it later', 'need special training beforehand'], [
            [26, 'sort out recorded content', 'A'],
            [27, 'collect and analyse some specific data', 'C'],
            [28, 'do research on ingredients of well-done beef', 'B'],
            [29, 'interview customers when they shop', 'E'],
            [30, 'decide on the format of the presentation', 'D'],
          ], { title: 'Suggestions', groupTitle: 'Questions 26-30' }),
      ],
      expl: {
        21: { v: 'Khi Jack giải thích vì sao làm cùng bạn.', t: ['Originally, I thought the research material would be complicated, so I should ask a friend to help interpret the results.', 'But it turned out having a partner was beneficial because there was a lot of research that needed doing'], p: 'Tài liệu không phức tạp như tưởng (bẫy C), cũng không nói từng làm chung (bẫy B); lý do thật là khối lượng nghiên cứu lớn → A' },
        22: { v: 'Khi bàn ai sẽ được phỏng vấn trước.', t: 'But I have decided to start with consumers and take down their opinions on what they\'re eating.', p: 'Gia sư gợi ý quản lý siêu thị, nhà sản xuất là bước sau; Jack bắt đầu với người tiêu dùng (consumers = shoppers) → B' },
        23: { v: 'Khi Jack nói về nhãn sản phẩm.', t: ['I thought the weight of the product and ingredients would have to be stated on the packaging.', 'It seems the price of the food item is the most important consideration of the manufacturers'], p: 'Jack tưởng là trọng lượng và thành phần (bẫy); thực tế giá là điều nhà sản xuất quan tâm nhất → C' },
        24: { v: 'Khi gia sư hỏi điều gì gây bất ngờ.', t: ['What really surprised me was the amount of artificial ingredients these foods contain.', "We're taking in vast amounts of additives every day."], p: 'Đồ ăn nhanh chỉ là phỏng đoán (bẫy C); điều bất ngờ là lượng phụ gia nhân tạo → A' },
        25: { v: 'Khi gia sư hỏi Jack lo lắng điều gì.', t: "My partner on the project worries that we have much more essential data to collect, but I'm more concerned with the fact that we're running out of time to complete the project.", p: 'Tìm người trả lời là “the easy part”, thiếu dữ liệu là nỗi lo của bạn cùng nhóm; Jack lo nhất là sắp hết thời gian → B' },
        26: { v: 'Khi gia sư góp ý về phần nội dung ghi âm.', t: ['You must have a great deal of recorded content to interpret.', 'It may be difficult to compile, so continuing to work with your partner is a good option.'], p: 'Nội dung ghi âm nhiều, khó tổng hợp → tiếp tục làm cùng bạn → A' },
        27: { v: 'Khi Jack nói cần thu thập dữ liệu về sở thích người tiêu dùng.', t: "There's no harm in asking someone else to collect it and even analyze it.", p: 'Nhờ người khác thu thập và phân tích, chỉ cần lấy kết quả → C' },
        28: { v: 'Khi nói về nghiên cứu thành phần thịt bò chín kỹ.', t: ['I think you need to weigh up its worth against the time it would take.', "It wouldn't be worth it."], p: 'Gia sư cho rằng việc này không đáng thời gian bỏ ra → B' },
        29: { v: 'Khi nói về phỏng vấn ở trung tâm mua sắm.', t: 'I suggest before you begin that you do some training.', p: 'Phỏng vấn khách trong trung tâm mua sắm cần được tập huấn trước → E' },
        30: { v: 'Cuối bài, khi nói về định dạng bài thuyết trình.', t: "You can work on that once you've gathered all your data.", p: 'Để việc trình bày lại sau khi thu thập xong dữ liệu → D' },
      },
    },
    {
      part: 4, title: 'Green Mountain Fossil Park', audio: 'listening/test 1/part 4.mp3', cover: 'fossil rock | ammonite fossil',
      fix: [['trace fossils you may wonder','trace fossils.\nYou may wonder'], ['And Allen animal dies', 'An animal dies']],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD AND/OR A NUMBER for each answer.', 'Study of Fossil Park', [
          '<strong>Types of fossils:</strong>',
          '• transitional fossils: rare, show evidence of evolutionary change',
          '• __Q31__ fossils: more common, actual fossilised remains',
          '• __Q32__ fossils: indirect evidence of animals, such as footprints or tunnels',
          '<strong>Fossilisation processes:</strong>',
          'Organism trapped in volcanic ash',
          'Petrifaction',
          '• An animal is __Q33__ in the mud after death.',
          '• Mud dries and hardens.',
          '• __Q34__ replace the bones leaving a stone shape.',
          '<strong>Purchasing fossils:</strong>',
          '• Site: Shop outside the park or from the park’s __Q35__',
          '• Prices: generally __Q36__',
        ], { 31: 'preserved', 32: 'trace', 33: 'buried', 34: 'minerals/mineral', 35: 'exhibitions/exhibition', 36: 'affordable' }, 'Questions 31-36'),
        table('Complete the table below.\nWrite NO MORE THAN TWO WORDS for each answer.', ['Tools', 'Function or purpose'], [
          ['A tape measure', 'Record the __Q37__ of each fossil'],
          ['A notebook', 'Record the types of __Q38__'],
          ['A camera', 'Record the __Q39__ of each fossil'],
          ['A compass', 'Detect __Q40__ the fossils to locate'],
        ], { 37: 'dimensions/dimension', 38: 'rocks', 39: 'images', 40: 'sediments' }, 'Questions 37-40'),
      ],
      expl: {
        31: { v: 'Phần các loại hoá thạch, loại thứ hai.', t: 'Next, we have preserved fossils, which are more common fossilised remains.', p: '“More common fossilised remains” khớp với ghi chú → preserved' },
        32: { v: 'Ngay sau đó, loại thứ ba.', t: ['Thirdly, we have fossils which indirectly show the activities of animals, such as their tracks and burrows.', 'And we refer to these as trace fossils.'], p: '“Tracks and burrows” = footprints or tunnels; loại này gọi là hoá thạch dấu vết → trace' },
        33: { v: 'Phần quá trình hoá đá (petrifaction).', t: 'An animal dies and becomes buried under mud or silt.', p: 'Con vật chết rồi bị vùi trong bùn → buried' },
        34: { v: 'Bước cuối của quá trình hoá đá.', t: 'Eventually, the bones also decay and are replaced by minerals, which form the shape of the fossil in stone.', p: 'Xương phân huỷ và được khoáng chất thay thế → minerals' },
        35: { v: 'Phần mua hoá thạch, nơi mua.', t: 'There is a shop outside the park but you can also make purchases from our exhibitions.', p: 'Ngoài cửa hàng bên ngoài công viên, có thể mua ở các khu triển lãm của công viên (key gốc ghi lệch câu, băng nói “exhibitions”) → exhibitions' },
        36: { v: 'Ngay sau đó, về giá.', t: ["Please don't think that all fossils are expensive to buy.", 'The majority are small and affordable samples that are as wonderful as the last one.'], p: 'Phần lớn là mẫu nhỏ, giá phải chăng → affordable' },
        37: { v: 'Phần dụng cụ: thước dây.', t: 'For example, there are tape measures available beside each fossil, so that you can note the dimensions of each fossil.', p: '“Note” = record; thước dây để ghi kích thước mỗi hoá thạch → dimensions' },
        38: { v: 'Dụng cụ thứ hai: sổ ghi chép.', t: 'We also encourage you to use your specially designed notebook to record as many different types of rocks as you can.', p: 'Sổ dùng để ghi các loại đá → rocks' },
        39: { v: 'Dụng cụ thứ ba: máy ảnh.', t: "If you brought a camera along with you today, don't hesitate to use it as the images of the fossils will be worth reviewing later.", p: 'Máy ảnh để lưu hình ảnh hoá thạch → images' },
        40: { v: 'Dụng cụ cuối: la bàn.', t: 'Even though you cannot locate the fossils themselves using the compass it will help you find the sediments which are the key to the location of the fossils.', p: 'La bàn không tìm trực tiếp hoá thạch mà giúp tìm lớp trầm tích – chìa khoá để định vị hoá thạch → sediments' },
      },
    },
  ],
};
