// Vol 3 – Test 6 (PDF "listening/test 6/test 6- up.pdf" p2–7; key xlsx sheet Test 6; audio test 6/section1–4.m4a;
// Otter per part: transcript/test 6/section N.pdf). P4's file ends with the 10-minute answer-transfer silence → clipped
// at 6:16 (the talk itself stops mid-sentence in the original recording: "Now one thing I haven't spoken about is...").
// Transcript: Whisper + Otter; turns by hand. P1: the example run (played first) is dropped, the full run kept.
// Source errors fixed: key Q17 "C" → B (the fire officer who showed staff how to help a colleague "is coming back to
// lead another session" = an external specialist); key Q39 "roads" → ropes ("local people produce ropes from them").
const { note, mc, matching } = require('../vol_build');

module.exports = {
  vol: 3, test: 6,
  sections: [
    {
      part: 1, title: 'Accommodation Request', audio: 'listening/test 6/section1.m4a', clip: [45.3, 500], cover: 'house for rent | letting agent house keys',
      fix: [
        ["I IELTS Listening, version 18144.\nGood morning.\nHow can I help you?\nI'm interested in renting somewhere to live in town and was wondering what you had available?\nExcellent.\nI'll just need to find out a bit more about what you're looking for and then we can see what we've got.\nSo your name is Anna Black.\nGood, got that.\nThe woman's name is Anna Black, so Anna Black has been written in the space.\n", ''],
        ["so let's say 15th of.\nMay.", "so let's say 15th of May."],
        ['£650 pounds', '£650'], ['£675 pounds', '£675'],
        ['my employer I will do that', 'my employer will do that'],
        ["33 Ainsworth's Street.\nThat's.\nA-I-N-S-W-O-R-T-H Street.", "33 Ainsworth Street.\nThat's A-I-N-S-W-O-R-T-H Street."],
      ],
      turns: [
        ['Agent', 'Good morning.'], ['Anna', "I'm interested in renting"], ['Agent', 'Excellent.'], ['Anna', 'Anna Black.'],
        ['Agent', 'Good, got that.'], ['Anna', "Well, I don't know if"], ['Agent', 'Oh, dear,'], ['Anna', 'Oh, yes, that would'],
        ['Agent', "And there's more chance"], ['Anna', "Yes.\nAnd I know it's not"], ['Agent', "I'll see what I can do."], ['Anna', 'One year?'],
        ['Agent', 'And when would you like to move in?'], ['Anna', "I've got to be out"], ['Agent', "And what's your current address?"],
        ['Anna', '56 Stone Street.'], ['Agent', 'And is there a phone number'], ['Anna', 'Yes.\nThe best one'],
        ['Agent', "Now, of course, we'll need a reference"], ['Anna', "I'm pretty sure"], ['Agent', "Good.\nNow, let's see"],
        ['Anna', "I'm paying £650"], ['Agent', "That shouldn't be any problem."], ['Anna', 'Since I came here,'], ['Agent', 'OK, good.'],
        ['Anna', 'No problem.'], ['Agent', "Good.\nNow, we've got a small house"], ['Anna', 'This looks great.'], ['Agent', 'Well, I could arrange'],
        ['Anna', 'Sounds good.'], ['Agent', 'Hmm.'], ['Anna', "And, sorry, there's another thing."], ['Agent', "Again, if I can't find out"],
        ['Anna', "OK.\nSo I'll drop by"], ['Agent', 'Excellent.'],
      ],
      groups: [
        note('Complete the notes below.\nWrite NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.', 'Accommodation request', [
          'Example: Name: <em>Anna Black</em>',
          'Type of accommodation: a house',
          'Preferred location: the __Q1__ of the town',
          'Facilities required: furnished property - with a __Q2__',
          'Period of time required: one year',
          'Start date of rental period: __Q3__',
          'Present address: 56, Stone Street',
          'Phone number: (mobile) 07942 326584',
          'Reference from: her __Q4__',
          'Maximum rent: £__Q5__ per month',
          "Applicant's job: __Q6__",
          '<strong>Documents to be supplied</strong>',
          "ID check: applicant's passport",
          'Credit check: a __Q7__',
          '<strong>Viewing arrangements</strong>',
          'Address of property: 33, __Q8__ Street',
          'Viewing day and time: Saturday 4 p.m.',
          'To check: Is there a __Q9__ in the house?',
          'Is there a __Q10__ nearby?',
        ], { 1: 'southeast/south-east/south east', 2: 'washing machine', 3: '15th May/15 May/15th of May/May 15th/May 15', 4: 'employer', 5: '675', 6: 'translator', 7: 'bank statement', 8: 'Ainsworth', 9: 'telephone/phone', 10: 'bus stop' }, 'Questions 1-10'),
      ],
      expl: {
        1: { v: 'Khi nhân viên gợi ý khu vực khác ngoài trung tâm.', t: ['There are a lot of nice properties in the south-east.', 'Oh, yes, that would be really convenient for me.'], p: 'Trung tâm thành phố chủ yếu là căn hộ (bẫy); Anna đồng ý khu đông nam vì gần bạn bè và chỗ làm → southeast' },
        2: { v: 'Khi nói về đồ đạc trong nhà.', t: "And I know it's not always included, but I'd like to have a washing machine.", p: 'Anna muốn nhà có máy giặt vì ghét đi tiệm giặt → washing machine' },
        3: { v: 'Khi hỏi ngày dọn vào.', t: ["I've got to be out of my present place by the 30th of April.", "Then I'm going to visit my parents for a couple of weeks so let's say 15th of May."], p: '30/4 là ngày phải rời chỗ cũ (bẫy); sau 2 tuần thăm bố mẹ, ngày bắt đầu thuê là 15/5 → 15th May' },
        4: { v: 'Khi hỏi ai có thể viết thư giới thiệu.', t: ["I'm pretty sure my employer will do that for me.", "I don't really know my doctor or anyone like that here."], p: 'Bác sĩ thì Anna không quen (bẫy); người giới thiệu là chủ lao động → employer' },
        5: { v: 'Khi hỏi mức giá thuê.', t: "I'm paying £650 a month at the moment, and the most I can go to is £675.", p: '£650 là mức đang trả (bẫy); tối đa có thể trả £675/tháng → 675' },
        6: { v: 'Khi hỏi nghề nghiệp.', t: "Since I came here, I've been working for various bodies within the city as a translator, you know, for the police and the hospital.", p: 'Cảnh sát, bệnh viện chỉ là nơi Anna làm việc; nghề của cô là phiên dịch → translator' },
        7: { v: 'Khi nói về giấy tờ cần nộp.', t: ['So we\'ll need to see your passport and, of course, to do the credit check.', "We'll need to see a bank statement in order to complete all the paperwork."], p: 'Hộ chiếu dùng để kiểm tra danh tính; để kiểm tra tín dụng cần sao kê ngân hàng → bank statement' },
        8: { v: 'Khi giới thiệu căn nhà.', t: ['33 Ainsworth Street.', "That's A-I-N-S-W-O-R-T-H Street."], p: 'Tên đường được đánh vần → Ainsworth' },
        9: { v: 'Khi Anna xem thông tin căn nhà.', t: ["I can't see any mention of a telephone in the details, though.", "I'd need that."], p: 'Chi tiết căn nhà không nhắc đến điện thoại, cần kiểm tra → telephone' },
        10: { v: 'Cuối bài, điều cần kiểm tra thứ hai.', t: "Do you happen to know if there's a bus stop reasonably close to the house, so that I can get around easily?", p: '“Reasonably close to the house” = nearby → bus stop' },
      },
    },
    {
      part: 2, title: 'Information for Fire Wardens', audio: 'listening/test 6/section 2.m4a', cover: 'fire extinguisher office | fire exit sign',
      turns: [],
      fix: [
        ['the standard ones on the wall the report says', 'the standard ones on the wall, the report says'],
        ['in that mine of fire', 'in that minor fire'],
      ],
      groups: [
        mc('Choose the correct letter, A, B or C.\nInformation for fire wardens', [
          [11, 'The company is having this meeting about fire procedures because', ['employees did badly in the last annual fire drill.', 'there have been changes in the building layout.', 'new staff have joined the company.'], 'B'],
          [12, 'There has been a recent upgrade to', ['the sprinkler system.', 'the fire extinguishers.', 'the alarm system.'], 'C'],
          [13, 'During the minor fire in January, some staff working in the factory', ['were unable to read fire notices.', 'left fire doors open.', 'were unwilling to start the fire alarm.'], 'C'],
          [14, 'In the fire in January, the problem with office staff was that they', ['refused to leave personal items behind.', 'moved too slowly during the evacuation.', 'did not move far away enough from the building.'], 'C'],
        ], 'Questions 11-14'),
        matching('What comment does the speaker make about each of the following aspects of fire safety?\nWrite the correct letter, A, B or C, next to Questions 15-20.',
          ['It should be a priority for fire wardens', 'It will be dealt with by an external specialist', 'It does not require attention'], [
            [15, 'ensuring there are no obstacles in fire escape routes', 'A'],
            [16, 'checking that fire doors are easily opened', 'A'],
            [17, 'showing staff how to look after each other', 'B'],
            [18, 'training staff to use fire extinguishers correctly', 'B'],
            [19, 'checking that staff are aware of evacuation points', 'A'],
            [20, 'checking that flammable liquids are properly stored', 'C'],
          ], { title: 'Comments', reuse: true, groupTitle: 'Questions 15-20' }),
      ],
      expl: {
        11: { v: 'Đầu bài, khi nêu lý do của cuộc họp.', t: ['But now the construction work is finished and we have a couple of new corridors and stairways.', 'We need the meeting to update everyone.'], p: 'Có người mới làm fire warden lần đầu nhưng đó không phải lý do (bẫy C); công trình xây xong, có thêm hành lang và cầu thang mới → thay đổi bố cục toà nhà → B' },
        12: { v: 'Khi nói về việc nâng cấp tuần trước.', t: ["The handheld fire extinguishers, the standard ones on the wall, the report says they're all working well as is the overhead sprinkler system.", 'But the old alarm system has been replaced and should be a lot more reliable.'], p: 'Bình chữa cháy và hệ thống phun nước chỉ được kiểm tra là vẫn tốt; hệ thống báo cháy cũ đã được thay → C' },
        13: { v: 'Khi nói về vụ cháy nhỏ ở nhà máy tháng 1.', t: 'From what I understand, staff felt somewhat reluctant to activate it themselves and were looking for someone senior.', p: 'Cửa chống cháy đã chặn được khói (loại B); nhân viên ngại tự bật chuông báo cháy → C' },
        14: { v: 'Khi nói về nhân viên văn phòng.', t: ['When the fire alarm went off in January in that minor fire, people got out of the office building pretty quickly.', "That was fine, but once they were out, they stood right in front of the doors, so if the fire crews had needed to access the offices, they would have been prevented."], p: 'Họ ra ngoài nhanh và để lại đồ đạc (loại A, B); vấn đề là đứng ngay trước cửa, không di chuyển đủ xa → C' },
        15: { v: 'Khi nói về lối thoát hiểm.', t: ["Firstly, we want to make sure that when we have the next fire drill, there's nothing blocking the way in the escape routes.", 'So, please have a look at that as soon as possible.'], p: 'Fire warden cần kiểm tra ngay → việc ưu tiên → A' },
        16: { v: 'Khi nói về cửa chống cháy.', t: "One thing that should definitely be on your to-do list is making sure no one's locked the fire doors and that it's easy enough to get through them.", p: '“Definitely be on your to-do list” → việc ưu tiên của fire warden → A' },
        17: { v: 'Khi nói về cách giúp đồng nghiệp bị ngạt khói.', t: ['Now, you might remember that last year we had a fire officer come and visit and show us what to do if we see a colleague starting to suffer from the effects of smoke inhalation.', "Well, the same officer's coming back to lead another session."], p: 'Cán bộ cứu hoả (người bên ngoài) sẽ quay lại hướng dẫn — key gốc ghi C là sai → B' },
        18: { v: 'Khi nói về bình chữa cháy.', t: 'Someone from the local fire department has booked in to teach people how to do that.', p: 'Người của sở cứu hoả địa phương sẽ dạy cách dùng bình chữa cháy → chuyên gia bên ngoài → B' },
        19: { v: 'Khi nói về điểm tập trung sơ tán.', t: 'Fire wardens need to make sure all staff are familiar with these locations for evacuation, so please send out emails directly after the meeting.', p: 'Fire warden phải gửi email ngay sau cuộc họp → việc ưu tiên → A' },
        20: { v: 'Cuối bài, về chất lỏng dễ cháy.', t: "I believe there have been a few concerns about where they were being stored in the warehouse, but that's been resolved now.", p: 'Vấn đề đã được giải quyết → không cần chú ý nữa → C' },
      },
    },
    {
      part: 3, title: 'Research on Pigeons', audio: 'listening/test 6/section 3.m4a', cover: 'pigeons city square | crested pigeon',
      fix: [
        ['on pavements and roads.\nIt stays way up', 'on pavements and roads, it stays way up'],
        ['in the computer lab to...\nYou.', 'in the computer lab to...'],
      ],
      turns: [
        ['Adam', 'Hi, Jennifer.'], ['Jennifer', 'Hey, Adam.'], ['Adam', 'Yes, I think so.'], ['Jennifer', 'Me too.'],
        ['Adam', 'But a lot of birds'], ['Jennifer', 'Well, it uses its wings.'], ['Adam', 'Really?'], ['Jennifer', 'Yes, if the pigeon is startled'],
        ['Adam', 'Interesting.'], ['Jennifer', 'Of all the pigeon species'], ['Adam', 'In contrast to the rock pigeon'], ['Jennifer', "That's unusual."],
        ['Adam', "Really?\nSo is there anything"], ['Jennifer', 'Yes, actually.'], ['Adam', 'Oh, right.'], ['Jennifer', 'Now, in the second part'],
        ['Adam', 'A lot of people in the city'], ['Jennifer', "Yes.\nSome people think"], ['Adam', "I suppose human food"],
        ['Jennifer', "Actually, because the pigeons"], ['Adam', 'I see.'], ['Jennifer', 'Now, I read that here in Melbourne'],
        ['Adam', "Yes.\nThey've built"], ['Jennifer', "But isn't that just changing"], ['Adam', "Well, that's just the first step."],
        ['Jennifer', "It's like a form of birth control."], ['Adam', 'Well, yes.'], ['Jennifer', 'Yes, I imagine it would be.'],
        ['Adam', 'And what did they do?'], ['Jennifer', 'Well, the city council found'], ['Adam', 'Really?\nWe\'ll have to include'],
        ['Jennifer', 'Well, I was thinking'], ['Adam', "Yes, we haven't really done that yet."], ['Jennifer', "Right.\nI've got some information"],
        ['Adam', "And I've got something related"], ['Jennifer', "But I haven't found anything yet"], ['Adam', 'Neither have I.'],
        ['Jennifer', 'OK.\nCan we meet again'],
      ],
      groups: [
        matching('What comments do the speakers make about each of the following types of pigeon?\nChoose FIVE answers from the box and write the correct letter, A-H, next to Questions 21-25.',
          ['eats meat', 'communicates with its wings', 'is found in a variety of locations', 'feeds on a particular type of plant', 'sings to attract a mate', 'is endangered', 'is brightly coloured', 'avoids the ground'], [
            [21, 'Australian crested pigeon', 'B'],
            [22, 'Rock pigeon', 'C'],
            [23, 'Black-banded pigeon', 'H'],
            [24, 'Galapagos pigeon', 'D'],
            [25, 'Nicobar pigeon', 'G'],
          ], { title: 'Comments', groupTitle: 'Questions 21-25' }),
        mc('Choose the correct letter, A, B or C.\nPigeons', [
          [26, 'When people feed city pigeons, it causes them to', ['breed more successfully.', 'become overweight.', 'get sick.'], 'A'],
          [27, 'The Melbourne city council are tackling their pigeon problem by', ['removing the pigeons from the city.', 'scaring away pigeons.', 'providing homes for the pigeons.'], 'C'],
          [28, 'Jennifer and Adam agree that the second stage of the council scheme is', ['expensive.', 'cruel.', 'ineffective.'], 'A'],
          [29, 'What method of pigeon control was most successful in the city of Basel?', ['trapping the pigeons', 'educating the public', 'building nesting sites'], 'B'],
          [30, 'Adam and Jennifer decide to do some more research on how pigeons can', ['affect our health.', 'damage buildings.', 'cause local flooding.'], 'A'],
        ], 'Questions 26-30'),
      ],
      expl: {
        21: { v: 'Khi nói về loài bồ câu mào Úc.', t: ['Well, it uses its wings.', 'Yes, if the pigeon is startled, it makes a whistling sound when it flies off.', "This sound warns other pigeons in the flock that there's danger."], p: 'Nhiều loài chim dùng tiếng hót để tìm bạn tình (bẫy E); loài này dùng cánh tạo tiếng rít để cảnh báo đàn → B' },
        22: { v: 'Khi nói về bồ câu đá.', t: ["They're the ones with the widest distribution.", "Of all the pigeon species, they've been the most successful at adapting to different environments, haven't they?"], p: 'Phân bố rộng nhất, thích nghi nhiều môi trường → có mặt ở nhiều nơi → C' },
        23: { v: 'Khi nói về bồ câu khoang đen.', t: 'Another interesting thing about it is that unlike the typical pigeons we see on pavements and roads, it stays way up in the trees in the rainforest.', p: 'Chỉ sống ở một khu rừng nhỏ nhưng không nói là sắp tuyệt chủng (bẫy F); nó ở trên cao, tránh mặt đất → H' },
        24: { v: 'Khi nói về thức ăn của bồ câu Galapagos.', t: 'The Galapagos pigeon, for example, gets all its nutrients from this one kind of cactus that grows on the island where it lives.', p: 'Lấy toàn bộ dinh dưỡng từ một loại xương rồng → ăn một loại cây nhất định → D' },
        25: { v: 'Khi nói về bộ lông bồ câu Nicobar.', t: ['The Nicobar pigeon from Indonesia is very attractive.', 'It has beautiful metallic green feathers.'], p: '“Not hunted” không có nghĩa là bị đe doạ (bẫy F); lông xanh ánh kim rất đẹp → màu sắc sặc sỡ → G' },
        26: { v: 'Khi bàn về việc cho bồ câu ăn.', t: ['Actually, because the pigeons don\'t have to spend time looking for food, they have more time to mate and reproduce.', 'And so it results in population explosion.'], p: 'Đồ ăn nhanh không tốt chỉ là phỏng đoán (bẫy B, C); bồ câu có thêm thời gian giao phối, sinh sản → A' },
        27: { v: 'Khi nói về hội đồng thành phố Melbourne.', t: ["They've built some special nesting places in one of the parks in the city centre.", "They're designed to house the pigeons so they stop creating nests on buildings."], p: 'Xây chỗ làm tổ đặc biệt để bồ câu ở → cung cấp nhà cho bồ câu → C' },
        28: { v: 'Khi nói về giai đoạn hai của chương trình.', t: ['The program does work as a means of controlling the population, but the financial burden on the taxpayer is quite high.', 'Yes, I imagine it would be.'], p: 'Chương trình có hiệu quả (loại C); gánh nặng tài chính cao và người kia đồng ý → A' },
        29: { v: 'Khi nói về thành phố Basel.', t: 'Well, the city council found that teaching the public about the negative effects of feeding pigeons was more effective than trapping the pigeons, or providing alternative nesting sites for them.', p: 'Bẫy bồ câu và xây chỗ làm tổ là cách đã thử trước đó; dạy công chúng hiệu quả hơn → B' },
        30: { v: 'Cuối bài, khi bàn cần tìm thêm thông tin.', t: ["But I haven't found anything yet on the health risks to humans that urban pigeons pose.", "Let's look for some information about that and add it."], p: 'Hư hại toà nhà và tắc máng nước đã có thông tin; còn thiếu rủi ro sức khoẻ → A' },
      },
    },
    {
      part: 4, title: 'The Lontar Palm', audio: 'listening/test 6/section 4.m4a', clip: [0, 376], cover: 'palm tree indonesia island | palm sap tapping',
      turns: [],
      fix: [
        ['Thank you.\nAs part of', 'As part of'],
        ['a tall palm tree called the lontar.\nThank you in the south of the Indonesian archipelago.', 'a tall palm tree called the lontar, which mainly grows on the island of Roti in the south of the Indonesian archipelago.'],
        ['Male and female long tar trees are different.\nMahlon tars can be', 'Male and female lontar trees are different.\nMale lontars can be'],
        ['as animal feed men and older boys', 'as animal feed.\nMen and older boys'],
        ['within their family Ownership', 'within their family.\nOwnership'],
        ['from September to October.\nAs villagers work', 'from September to October, as villagers work'],
        ['biscuits of brown sugar but the lawn tar palm supplies much more than sustenance for the road to Nice.', 'biscuits of brown sugar.\nBut the lontar palm supplies much more than sustenance for the Rotinese.'],
        ['The broad lawn tar leaves', 'The broad lontar leaves'],
        ['The Rotonese also make', 'The Rotinese also make'],
        ['The lantar leaf even provides the Rotonese people', 'The lontar leaf even provides the Rotinese people'],
        ['The stalks of the lantar leaves', 'The stalks of the lontar leaves'],
        ["Now one thing I haven't spoken about is.\nYou now have 10 Minutes to Transfer your answers to the listening answer sheet.\nYou have two minutes left.\nYou have one minute left?\nPlease stop writing and wait for your question booklet to be collected", "Now one thing I haven't spoken about is..."],
      ],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'The Lontar Palm', [
          '<strong>The tree</strong>',
          '• grows on Roti, an Indonesian island',
          "• is known as the 'tree of life'",
          '• produces delicious juice',
          '• has a fruit resembling a __Q31__ (female trees only)',
          '<strong>People climbing the trees</strong>',
          '• fix __Q32__ to the tree trunks to help them climb',
          '• keep their tools attached to a __Q33__',
          '• often own particular trees',
          '• contribute to the upkeep of the communal fence',
          '<strong>Using the juice</strong>',
          '• It quickly becomes __Q34__ if left unprocessed.',
          '• A concentrated form of it is drunk in the rainy season.',
          '• It can be made into sugary __Q35__',
          '<strong>Using other parts of the tree</strong>',
          'The leaf is used:',
          '• to make containers, bags and roofing',
          '• as garden __Q36__',
          '• for brightly decorated hats worn at a __Q37__',
          '• for a musical instrument which sounds like a __Q38__',
          'The stalk is used to make __Q39__',
          'The trunk is used in the construction of __Q40__',
        ], { 31: 'coconut', 32: 'stones', 33: 'belt', 34: 'sour', 35: 'biscuits', 36: 'fertiliser/fertilizer', 37: 'celebration', 38: 'harp', 39: 'ropes/rope', 40: 'houses' }, 'Questions 31-40'),
      ],
      expl: {
        31: { v: 'Khi nói về cây cái.', t: 'If the female tree is left untapped, a large fruit develops like a coconut in appearance.', p: 'Quả lớn trông giống quả dừa (chỉ cây cái) → coconut' },
        32: { v: 'Khi nói về người trèo cây.', t: "They don't use safety equipment, but make things easier for themselves by tying stones to the trunk.", p: 'Họ không dùng đồ bảo hộ mà buộc đá vào thân cây → stones' },
        33: { v: 'Ngay sau đó, về dụng cụ.', t: 'The men attach all the tools they need to a belt that they wear when climbing the tree.', p: 'Dụng cụ được gắn vào thắt lưng đeo khi trèo → belt' },
        34: { v: 'Khi nói về nước ép.', t: "Whatever juice isn't drunk immediately has to be processed as quickly as possible, as it turns sour very rapidly.", p: '“Turns sour very rapidly” = quickly becomes sour → sour' },
        35: { v: 'Khi nói về cách dùng nước ép mùa mưa.', t: 'For example, it can be used to make biscuits of brown sugar.', p: 'Nước ép cô đặc dùng làm bánh quy đường nâu → biscuits' },
        36: { v: 'Khi nói về lá cây.', t: 'When the leaves are replaced every five years or so the old ones are burned on the garden as a fertilizer.', p: 'Lá cũ được đốt trong vườn làm phân bón → fertiliser' },
        37: { v: 'Khi nói về chiếc mũ làm từ lá.', t: 'There are many for different occasions, ranging from simple ones for everyday use to larger and more elaborate hats used for a celebration, which are painted in bright colors.', p: 'Mũ to, cầu kỳ, sơn màu sáng dùng cho dịp lễ hội → celebration' },
        38: { v: 'Khi nói về nhạc cụ sasando.', t: 'The leaf is made into a sounding board and has strings attached, which are plucked in the manner of a harp, and the sound produced is also similar.', p: 'Gảy như đàn hạc và âm thanh cũng giống → harp' },
        39: { v: 'Khi nói về cuống lá.', t: 'They are really strong and grow up to 1.5 metres long, and local people produce ropes from them.', p: 'Cuống lá chắc, người dân làm dây thừng (key gốc ghi “roads” là sai) → ropes' },
        40: { v: 'Cuối bài, về thân cây.', t: 'Even when a lontar tree becomes old and unproductive and no longer can be used for tapping, the whole tree is cut down and the thick trunk is utilised for building houses.', p: 'Thân cây dày dùng để xây nhà → houses' },
      },
    },
  ],
};
