// Vol 3 – Test 10 (PDF "listening/test 10/test 10.pdf" p2–7; key xlsx sheet Test 10; audio test 10/Track 1–4.mp3 —
// Track 4 ends with the 10-minute answer-transfer silence → clipped at 5:12.5).
// Transcript: Whisper + the whole-test Otter PDF (transcript/test 10.pdf); turns by hand.
// Source errors fixed: key Q21 "A" → B (Lorna: "evaluating how useful it was is simple. The challenge is not to go over
// length" — published sources are Charles's tip, not her problem).
const { note, mc, matching } = require('../vol_build');

module.exports = {
  vol: 3, test: 10,
  sections: [
    {
      part: 1, title: 'Joining a Film Club', audio: 'listening/test 10/Track 1.mp3', clip: [39.9, 430.5], cover: 'cinema film club | movie theatre audience',
      fix: [
        ['IELTS Listening, version 56658.\nIn the listening question booklet.\n', ''],
        ["setting up the web page Sorry about that.", "setting up the web page.\nSorry about that."],
        ['How often does the club meet Every two weeks', 'How often does the club meet?\nEvery two weeks'],
        ['£24 pounds', '£24'],
        ['complementary parking', 'complimentary parking'],
        ['an American film called.\nThe Soldier.', 'an American film called The Soldier.'],
        ['1926 or 27?\n£17?\n', '1926 or 27?\n'],
        ["Then the next film after that so that'll be, let's see, the 11th of November is a film", "Then the next film after that, so that'll be, let's see, the 11th of November, is a film"],
        ['application form...\nSure.\nThank you.\nThank you.', 'application form...\nSure.'],
      ],
      turns: [
        ['Assistant', 'Hi.'], ['Teenager', 'Yeah.'], ['Assistant', "Yes, we're still setting up"], ['Teenager', 'How often does the club meet?'],
        ['Assistant', 'Every two weeks'], ['Teenager', "OK.\nAnd I'm 16"], ['Assistant', 'Sure.'], ['Teenager', 'Right.\nSo how much'],
        ['Assistant', 'Well, it depends.'], ['Teenager', "I'm a student."], ['Assistant', "You'd get the concession rate"], ['Teenager', "That's good."],
        ['Assistant', 'That entitles you'], ['Teenager', 'Great.'], ['Assistant', "OK.\nNow, I don't know"], ['Teenager', "I don't drive"],
        ['Assistant', "I'm afraid we've run out"], ['Teenager', 'Ah, I read the reviews'], ['Assistant', "That's right.\nIt just came out"],
        ['Teenager', 'And the kid somehow'], ['Assistant', 'A singing competition, yeah.'], ['Teenager', 'Yes, it sounds really good.'],
        ['Assistant', 'On October the 28th'], ['Teenager', 'Must be a pretty old film'], ['Assistant', 'Yes, this was made in 1922'],
        ['Teenager', 'So what sort of film is it?'], ['Assistant', "Well, it's billed as a comedy"], ['Teenager', "Yeah, I'll do that."],
        ['Assistant', 'Then the next film after that'], ['Teenager', "What's it about?"], ['Assistant', "It's got no humans"],
        ['Teenager', 'Right.\nWell, thanks for all that.'], ['Assistant', 'Sure.'],
      ],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD AND/OR A NUMBER for each answer.', 'Film Club', [
          '<strong>Membership information</strong>',
          'Club meets every 2 weeks',
          'No __Q1__ limit',
          'Student membership costs £__Q2__ per season',
          'Members get:',
          '• free entry to club films',
          '• £__Q3__ reduction on other films at cinema',
          "Members are entitled to 3 hours' free __Q4__",
          '<strong>Films to be shown:</strong>',
          'Oct 14: <em>Pablo</em>',
          '• about a child in __Q5__ who runs away from home and wins a __Q6__ competition on TV',
          'Oct 28: <em>The Soldier</em>',
          '• with live __Q7__ accompaniment',
          '• made in the year __Q8__',
          '• type of film: a __Q9__',
          'Nov 11: <em>Tiger</em>',
          '• cartoon aimed at adults',
          '• followed by a __Q10__ by the director',
        ], { 1: 'age', 2: '21.50', 3: '2/two', 4: 'parking', 5: 'Argentina', 6: 'singing', 7: 'piano', 8: '1922', 9: 'comedy', 10: 'talk' }, 'Questions 1-10'),
      ],
      expl: {
        1: { v: 'Khi bạn trẻ hỏi 16 tuổi có tham gia được không.', t: ["And I'm 16, so could I join?", 'People of any age can join.'], p: 'Người ở mọi lứa tuổi đều tham gia được → không giới hạn tuổi → age' },
        2: { v: 'Khi hỏi phí thành viên.', t: ["The basic charge is £24 a season, but for people eligible for concessions, it's £21.50.", "I'm a student.", "You'd get the concession rate, then."], p: '£24 là giá thường (bẫy); sinh viên được giá ưu đãi £21.50 → 21.50' },
        3: { v: 'Khi nói về quyền lợi thành viên.', t: ['That entitles you to free entry to the club films, and also to £2 off tickets for all other films on at the cinema.', "So you'd pay £4.50 instead of £6.50."], p: '£4.50 và £6.50 là giá vé (bẫy); mức giảm là £2 → 2' },
        4: { v: 'Ngay sau đó.', t: "Now, I don't know if this applies to you, but club members are also eligible for three hours complimentary parking when there's a film on.", p: '“Complimentary” = free; 3 giờ đỗ xe miễn phí → parking' },
        5: { v: 'Khi nói về phim Pablo.', t: ["It's set in Argentina, isn't it?", "About a child who's run away from home?", "That's right."], p: 'Phim lấy bối cảnh ở Argentina → Argentina' },
        6: { v: 'Ngay sau đó.', t: ['And the kid somehow gets on TV and he wins a dance competition or something?', 'A singing competition, yeah.'], p: '“Dance” là đoán sai của bạn trẻ (bẫy); cuộc thi hát → singing' },
        7: { v: 'Khi nói về phim The Soldier.', t: "But in this showing, we have someone who'll accompany it on the piano, just like they used to in the old cinemas, though it was sometimes an organ accompaniment in those days.", p: 'Đàn organ là cách đệm ngày xưa (bẫy); buổi chiếu này đệm piano → piano' },
        8: { v: 'Khi hỏi phim được làm năm nào.', t: 'Yes, this was made in 1922, so well before, though, I think they had short feature films with sound by 1923, actually.', p: '1926–27 là năm có phim nói, 1923 là phim ngắn có tiếng (bẫy); phim làm năm 1922 → 1922' },
        9: { v: 'Khi hỏi thể loại phim.', t: "Well, it's billed as a comedy, though you'd think it was a war film from the title.", p: 'Nghe tên tưởng phim chiến tranh (bẫy) nhưng thực ra là phim hài → comedy' },
        10: { v: 'Cuối bài, về phim Tiger.', t: "There's a talk afterwards given by the directors, so that should be very popular.", p: 'Sau phim có buổi nói chuyện của đạo diễn → talk' },
      },
    },
    {
      part: 2, title: 'ExtraHands.com Volunteer Placements', audio: 'listening/test 10/Track 2.mp3', cover: 'volunteer farm work | working holiday volunteer',
      fix: [
        ['Com.\nStephen Jennings has been involved', 'Stephen Jennings has been involved'],
        ['how long they want to work for are Not many people', 'how long they want to work for.\nNot many people'],
        ['What about problems?\nWell.\nThere are too many members', 'What about problems?\nWell, there are too many members'],
        ["They've had Things like", "They've had things like"],
        ['And this works very well. com placements, Stephen.', "And this works very well.\nI know you've personally had lots of ExtraHands.com placements, Stephen."],
        ['And if you want more information... about that is.\nThe end of Part 2.\nThank you.', 'And if you want more information about...'],
      ],
      turns: [
        ['Presenter', 'Stephen Jennings has been involved'], ['Stephen', 'Thanks.'], ['Presenter', 'So how does it work?'],
        ['Stephen', 'Well, if a host'], ['Presenter', 'What about problems?'], ['Stephen', 'Well, there are too many members'],
        ['Presenter', "I know you've personally"], ['Stephen', 'Well, my first placement'], ['Presenter', 'Thanks, Stephen.'],
      ],
      groups: [
        mc('Choose the correct letter, A, B or C.\nextrahands.com', [
          [11, 'Stephen says the founders of extrahands.com originally needed help in', ['preparing their fields for planting.', 'harvesting their organic crops.', 'constructing their farm buildings.'], 'A'],
          [12, 'To remain an active member of extrahands.com, you must', ['update your form on the website every year.', 'pay a subscription of $25 every year.', 'use the scheme as a host or volunteer every year.'], 'A'],
          [13, 'Most extrahands.com volunteers search for jobs on the website according to', ['the type of work available.', 'the geographical location.', 'the length of time required.'], 'B'],
          [14, 'Stephen recommends that the host and volunteer should', ['confirm details of the arrangement in writing.', 'draw up a formal written contract.', 'meet each other before setting out terms.'], 'A'],
          [15, "To deal with members' problems, extrahands.com have a system", ['for checking each new member online.', 'for allowing online feedback.', 'for inspecting work and accommodation.'], 'B'],
        ], 'Questions 11-15'),
        matching('Which job did Stephen do on his placement in each of the following countries?\nChoose FIVE answers from the box and write the correct letter, A-G, next to Questions 16-20.',
          ['cook', 'gardener', 'construction worker', 'tour guide', 'farm labourer', 'editor', 'swimming pool cleaner'], [
            [16, 'Portugal', 'F'],
            [17, 'Australia', 'A'],
            [18, 'South Korea', 'D'],
            [19, 'USA', 'B'],
            [20, 'Italy', 'C'],
          ], { title: 'Jobs', groupTitle: 'Questions 16-20' }),
      ],
      expl: {
        11: { v: 'Khi Stephen kể về lúc thành lập ExtraHands.com.', t: "They wanted to go organic, but they realized they'd need help clearing the fields for cultivation, and they just didn't have the money to pay for it.", p: '“Clearing the fields for cultivation” = chuẩn bị ruộng để trồng trọt → A' },
        12: { v: 'Khi nói về cách duy trì tư cách thành viên.', t: 'But for your membership to stay active, every 12 months, you have to go back to the website and check the details on your form there, adding information about any help you requested or work you did over that period.', p: 'Phí chỉ trả một lần (loại B); mỗi 12 tháng phải cập nhật biểu mẫu trên website → A' },
        13: { v: 'Khi nói về cách tình nguyện viên tìm việc.', t: "So the way most volunteers access these details on the website is by specifying the country or region they're interested in working in, but a few search according to how long they want to work for.", p: 'Chỉ một số ít tìm theo thời gian (bẫy C), loại việc thì ít ai quan tâm; đa số tìm theo quốc gia, khu vực → B' },
        14: { v: 'Khi nói về việc thoả thuận.', t: ['There are no legal documents or anything like that.', "But you do both need to have some sort of written record of what's been agreed before you actually arrive."], p: 'Không có hợp đồng pháp lý (loại B); cần có ghi chép bằng văn bản điều đã thoả thuận → A' },
        15: { v: 'Khi nói về cách xử lý vấn đề.', t: ['There are too many members for the organization to be able to investigate them all.', 'But there is an online message board where members can post details of any difficulties.'], p: 'Không thể kiểm tra từng thành viên (loại A, C); có bảng tin trực tuyến để phản hồi → B' },
        16: { v: 'Công việc ở Bồ Đào Nha.', t: ['Well, my first placement was in Portugal, where I helped a local guy with a guidebook he\'d written in English.', 'I read what he\'d written and corrected the English and made some suggestions for improving it.'], p: 'Đọc, sửa tiếng Anh và góp ý cho cuốn sách hướng dẫn → biên tập viên → F' },
        17: { v: 'Công việc ở Úc.', t: "I was on a farm in the middle of nowhere and since I'm pretty good in the kitchen, they had me fixing meals for 30 sheep shearers.", p: 'Ở trang trại nhưng không làm việc đồng áng (bẫy E); nấu ăn cho 30 thợ xén lông cừu → A' },
        18: { v: 'Công việc ở Hàn Quốc.', t: 'Okay, then, after a well deserved rest, I did a job in South Korea for a small company that wanted an English speaker to show visiting Americans around.', p: 'Dẫn khách Mỹ đi tham quan → hướng dẫn viên → D' },
        19: { v: 'Công việc ở Mỹ.', t: 'So I worked for her, digging and planting flowers and stuff around her swimming pool.', p: 'Bể bơi chỉ là địa điểm (bẫy G); đào đất, trồng hoa → làm vườn → B' },
        20: { v: 'Công việc ở Ý.', t: 'I helped a family add a room onto their house.', p: 'Giúp xây thêm một phòng cho ngôi nhà → công nhân xây dựng → C' },
      },
    },
    {
      part: 3, title: 'Song-writing Course for Drama Students', audio: 'listening/test 10/Track 3.mp3', cover: 'songwriting guitar notebook | drama students workshop',
      fix: [
        ['Now I\'ll listen carefully and answer questions 21 to 25?\n', ''],
        ['Hmm evaluating', 'Hmm, evaluating'],
        ['The challenge is not to go over length, Referring', 'The challenge is not to go over length.\nReferring'],
        ['OK I go with that.', "OK, I'll go with that."],
        ['That was the best bit for me, Having', 'That was the best bit for me, having'],
        ["It was tough and Peggy, my partner was hard work, which wasn't funny and writing", "It was tough, and Peggy, my partner, was hard work, which wasn't funny, and writing"],
        ['like Ted Winter workshop', "like Ted Winter's workshop"],
        ["What's about Dorothy Thomas?", 'What about Dorothy Thomas?'],
        ["put my name down for...\nThank you.", 'put my name down for...'],
      ],
      turns: [
        ['Lorna', 'Hi, Charles'], ['Charles', 'Yes, it was great.'], ['Lorna', 'Hmm, evaluating'], ['Charles', 'Referring to published'],
        ['Lorna', "OK, I'll go with that."], ['Charles', 'And saying why you did'], ['Lorna', 'I thought it was the location'],
        ['Charles', 'I enjoyed the workshop most.'], ['Lorna', 'Well, we were divided'], ['Charles', 'And what did you think'],
        ['Lorna', "I hadn't realised"], ['Charles', "Yes, we learned it's no use"], ['Lorna', 'I knew about that stuff'],
        ['Charles', 'Yeah, I suppose so.'], ['Lorna', 'You could always look them up'], ['Charles', 'Anyway, how did you get on'],
        ['Lorna', 'It was tough'], ['Charles', 'Writing music from the heart'], ['Lorna', "Well, that's got the report sorted"],
        ['Charles', "I want to do Bob Lacey's."], ['Lorna', "I'm thinking of going"], ['Charles', 'Oh, Evelyn.'], ['Lorna', 'Yes, fencing,'],
        ['Charles', 'Lots of people like'], ['Lorna', "I'm definitely going to sign up"], ['Charles', 'If you want to understand'],
        ['Lorna', 'What about Dorothy Thomas?'], ['Charles', "She's good at activities"], ['Lorna', "Well, I think I'll put my name down"],
      ],
      groups: [
        mc('Choose the correct letter, A, B or C.\nSong-writing course for drama students', [
          [21, 'What problem is Lorna having with her report?', ['listing the references', 'keeping to the word limit', 'writing the evaluation'], 'B'],
          [22, 'Why did Charles take the song-writing course?', ['to improve his job prospects', 'to increase his self-confidence', 'to develop his self-expression'], 'C'],
          [23, 'Which type of work did Lorna most enjoy?', ['individual work', 'pair work', 'group work'], 'C'],
          [24, 'Which aspect of the course content did both students find interesting?', ['song structure', 'writing a chorus', 'lyrical styles and forms'], 'A'],
          [25, 'Lorna found writing a song', ['impossible.', 'tiring.', 'amusing.'], 'B'],
        ], 'Questions 21-25'),
        matching('What is the focus of the drama workshop run by each of the following teachers?\nChoose FIVE answers from the box and write the correct letter, A-H, next to Questions 26-30.',
          ['use of own memories', 'full use of the stage', 'relaxation techniques', 'physical expression of character', 'play readings', 'acting without preparation', 'using a range of accents', 'following instructions'], [
            [26, 'Bob Lacey', 'G'],
            [27, 'Evelyn Chance', 'B'],
            [28, 'Ted Winter', 'D'],
            [29, 'Kevin Gray', 'H'],
            [30, 'Dorothy Thomas', 'C'],
          ], { title: 'Focus of drama workshop', groupTitle: 'Questions 26-30' }),
      ],
      expl: {
        21: { v: 'Khi Lorna nói khó khăn với bài báo cáo.', t: ['Hmm, evaluating how useful it was is simple.', 'The challenge is not to go over length.', 'Referring to published sources might help.'], p: 'Phần đánh giá thì đơn giản (loại C), nguồn tham khảo là gợi ý của Charles (key gốc ghi A là sai); khó khăn là không viết quá độ dài cho phép → B' },
        22: { v: 'Khi Charles nói vì sao học khoá này.', t: ['Some people just do it as another string to their bow to help with auditions for work and things.', 'I thought it was a good opportunity to try out new techniques for communicating feelings and emotions.', 'I was already confident about singing before I did it.'], p: 'Việc làm là lý do của người khác (loại A), anh đã tự tin sẵn (loại B); anh muốn thử kỹ thuật truyền đạt cảm xúc → C' },
        23: { v: 'Khi Lorna kể phần thích nhất.', t: ['Well, we were divided into six small groups for the afternoon, each with their own advisor.', 'That was the best bit for me, having that discussion with an expert.'], p: 'Làm theo cặp không suôn sẻ vì bạn thích làm một mình; phần hay nhất là thảo luận theo nhóm nhỏ → C' },
        24: { v: 'Khi bàn về nội dung khoá học.', t: ["I hadn't realised before how important the structure of a song is to its success.", "Yes, we learned it's no use writing the most beautiful words and melodies if there's no shape."], p: 'Điệp khúc thì Lorna đã biết (loại B), phong cách lời Charles thấy chán (loại C); cả hai đều thấy cấu trúc bài hát hay → A' },
        25: { v: 'Khi Charles hỏi Lorna viết bài hát thế nào.', t: ["It was tough, and Peggy, my partner, was hard work, which wasn't funny, and writing was a slow process as a result of our lack of communication.", 'By the time we finished, I was exhausted.'], p: 'Khó nhưng vẫn viết xong (loại A), “wasn\'t funny” (loại C); kết thúc thì kiệt sức → B' },
        26: { v: 'Workshop của Bob Lacey.', t: ["He's got a brilliant reputation for voice coaching.", 'You know, getting us to use dialects and different pronunciation and stuff.'], p: 'Dùng phương ngữ và nhiều cách phát âm → nhiều giọng khác nhau; đọc bài báo chỉ là ví dụ (bẫy E) → G' },
        27: { v: 'Workshop của Evelyn Chance.', t: 'She really knows how to help actors use the whole of the space available.', p: 'Giúp diễn viên dùng toàn bộ không gian sân khấu → B' },
        28: { v: 'Workshop của Ted Winter.', t: "He's keen on actors conveying emotion through their bodies and faces alone.", p: 'Truyền tải cảm xúc chỉ bằng cơ thể và nét mặt → thể hiện nhân vật qua hình thể → D' },
        29: { v: 'Workshop của Kevin Gray.', t: ["He likes telling people what to do, and he's always saying you can't have a company of actors reading a play any way they want, because they'd end up fighting amongst themselves.", 'They must listen to the director.'], p: 'Đọc kịch được nhắc đến nhưng trọng tâm là phải nghe theo đạo diễn → làm theo chỉ dẫn → H' },
        30: { v: 'Workshop của Dorothy Thomas.', t: "She's good at activities for getting rid of stress and, you know, emptying your mind of all thoughts about the past, and that can really help when acting.", p: 'Giảm căng thẳng, làm trống đầu óc → kỹ thuật thư giãn; “the past” là bẫy cho A → C' },
      },
    },
    {
      part: 4, title: 'Office Design', audio: 'listening/test 10/Track 4.mp3', clip: [0, 312.5], cover: 'open plan office | office cubicles',
      turns: [],
      fix: [
        ['End of Part three.\n', ''],
        ['in large call centers.\nA phenomenon known as hot desking', 'in large call centers, a phenomenon known as hot desking'],
        ['can learn from observe other workers', 'can learn from observing other workers'],
      ],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'Office Design', [
          '<strong>Early 20th century</strong>',
          '• workers employed to do __Q31__ were arranged in rows',
          '<strong>1960s to present</strong>',
          'Variations in design of open-plan offices:',
          '• first, workers had individual __Q32__',
          '• later, they had cubicles with high or low __Q33__',
          '• nowadays, workers may have to __Q34__ a work area',
          '<strong>Survey results</strong>',
          'Attitudes of employees to open-plan designs:',
          '• there is a lack of __Q35__ and __Q36__',
          '• they pose a risk to our __Q37__ (staff records support this)',
          'Attitudes of employers to open-plan designs:',
          '• they significantly reduce rent and __Q38__ costs',
          '• they improve teamwork and communication',
          '• they can make __Q39__ staff easier',
          'In reality, employees are unhappy and they are often distracted by the __Q40__ in the office.',
        ], { 31: 'typing', 32: 'desks', 33: 'screens', 34: 'share', 35: 'privacy', 36: 'security', 37: 'health', 38: 'energy', 39: 'training', 40: 'noise' }, 'Questions 31-40'),
      ],
      expl: {
        31: { v: 'Phần đầu thế kỷ 20.', t: 'You might think open plan designs are a recent phenomenon, but they actually came about in the early 20th century, when businesses needed large numbers of people to do typing.', p: 'Doanh nghiệp cần nhiều người đánh máy, ngồi thành hàng → typing' },
        32: { v: 'Biến thể thiết kế đầu tiên.', t: 'The early designs featured separate desks.', p: '“Separate desks” = individual desks → desks' },
        33: { v: 'Biến thể tiếp theo.', t: "These can have either high screens that workers can't see over, or a screen just low enough to keep a lookout for the manager.", p: 'Buồng làm việc có vách ngăn cao hoặc thấp → screens' },
        34: { v: 'Thiết kế hiện nay.', t: 'In this system, employees working on different shifts are asked to share the same workstation.', p: 'Hot desking: nhân viên khác ca dùng chung một chỗ làm việc → share' },
        35: { v: 'Phần khảo sát nhân viên.', t: 'Firstly, they felt that the open plan took away their privacy, but many also felt the need to carry their valuables with them at all times.', p: 'Văn phòng mở lấy mất sự riêng tư → privacy' },
        36: { v: 'Ngay sau đó.', t: 'So, to some extent, they also felt there was less security with these designs.', p: 'Phải mang theo đồ có giá trị vì kém an ninh → security' },
        37: { v: 'Lời phàn nàn thứ ba.', t: ['and this was that these types of office space are bad for the health.', "I was intrigued by this possibility, but looking at staff records, it does seem to be borne out."], p: 'Có hại cho sức khoẻ, hồ sơ nhân viên xác nhận → health' },
        38: { v: 'Phần quan điểm của chủ doanh nghiệp.', t: 'Of course, there is the obvious benefit that this design significantly reduces costs, both in terms of rent, and even in terms of energy use.', p: 'Giảm chi phí thuê mặt bằng và năng lượng → energy' },
        39: { v: 'Lợi ích thứ ba.', t: 'They also feel that new staff can learn from observing other workers, so this design can actually help in training staff.', p: 'Nhân viên mới học bằng cách quan sát → giúp đào tạo nhân viên dễ hơn → training' },
        40: { v: 'Cuối bài, thực tế.', t: 'And there is plenty of evidence to suggest workers are frequently distracted from their work by the noise that is all around them.', p: 'Nhân viên thường bị xao nhãng bởi tiếng ồn xung quanh → noise' },
      },
    },
  ],
};
