// Vol 3 – Test 1 (PDF "listening/test 1/test 1- up.pdf" p2–8; key = "Key Lis VOL 3-full.xlsx" sheet Test 1; audio = ONE
// whole-test file "test 1.mp3" → each part is a clip of it, from "Now turn to section N" to the end of its check pause).
// Transcript: Whisper + the whole-test Otter PDF (transcript/test 1.pdf, sliced per part); Otter names no speakers →
// turns by hand. P1: the example is played first and then again — the first (cleaner) run is kept.
// Source errors fixed: Q4–10 instruction "NO MORE THAN WORDS AND/OR A NUMBER" (→ TWO WORDS); key Q19–20 "B, C" → B, E
// (the water bottle is for everyone present, the two gifts for new members are the heart monitor and the massage
// voucher); key Q26 "D" → C (Coleman: the survey looked at a single year only — "money well spent" is the distractor);
// key Q34 "reponsible" → responsible.
const { note, mc, multi, map, matching } = require('../vol_build');

module.exports = {
  vol: 3, test: 1,
  sections: [
    {
      part: 1, title: 'Manor Farm Fruit Picking', audio: 'listening/test 1/test 1.mp3', clip: [42.3, 413], cover: 'apple orchard | strawberries harvest',
      fix: [
        ['On this occasion only, the conversation relating to this will be played first.\n', ''],
        ["The man's name is Ben Miller.\nSo Ben Miller has been written in the space.\nManor farm Hello.\nHi there.\nI'd like to apply to do fruit picking this summer.\nOh, hello.\nI'm Mrs. Chandler.\nMy husband and I own Manor farm.\nLet me take some details.\nI'll just get a form to fill in.\nHold on.\nSure.\nSorry.\nIt's Ben Miller.\n", ''],
        ['Manor Farm, hello.\nHello.\nHi there.', 'Manor Farm, hello.\nHi there.'],
        ["That's fine, then we'll need fruit Baker's", "That's fine, then.\nWe'll need fruit pickers"],
        ['\nUh.\n', '\nUh-huh.\n'],
        ["your passport because without one won't be allowed to work.", "your passport.\nPickers without one won't be allowed to work."],
        ["Well, I'll post a contract to you at the... end.", "Well, I'll post a contract to you..."],
      ],
      turns: [
        ['Mrs Chandler', 'Manor Farm, hello.'], ['Ben', 'Hi there.'], ['Mrs Chandler', 'Oh, hello.'], ['Ben', 'Sure.'],
        ['Mrs Chandler', 'Sorry.'], ['Ben', "It's Ben Miller."], ['Mrs Chandler', 'And where are you from?'], ['Ben', "I'm from the USA."],
        ['Mrs Chandler', 'Fine.'], ['Ben', "I'm 20."], ['Mrs Chandler', "Yes, that's right."], ['Ben', 'Sorry?'],
        ['Mrs Chandler', 'I mean, do you have a visa?'], ['Ben', 'Oh, yeah.'], ['Mrs Chandler', "That's fine, then."], ['Ben', 'When can I work?'],
        ['Mrs Chandler', 'OK.'], ['Ben', "That's right."], ['Mrs Chandler', "Well, yes, but it's a question"], ['Ben', 'I see.'],
        ['Mrs Chandler', 'Well, that depends on age.'], ['Ben', 'Uh-huh.'], ['Mrs Chandler', 'Yes, there is no accommodation'],
        ['Ben', 'Is that walking distance?'], ['Mrs Chandler', 'What do you think?'], ['Ben', 'No, maybe I should bring'],
        ['Mrs Chandler', 'Yes, we always recommend that.'], ['Ben', 'I know that fruit picking'], ['Mrs Chandler', 'Well, firstly,'],
        ['Ben', 'Oh, even if'], ['Mrs Chandler', 'Sorry, a driving'], ['Ben', 'Fair enough.'], ['Mrs Chandler', "I'm afraid not."],
        ['Ben', 'Right, like back home.'], ['Mrs Chandler', "Well, I'll post a contract"],
      ],
      groups: [
        note('Complete the form below.\nWrite NO MORE THAN TWO WORDS for each answer.', 'Manor Farm – Application Form: Summer fruit picking', [
          'Example: Name: <em>Ben Miller</em>',
          'Country of origin: the USA',
          'Age: 20',
          'Visa type: a __Q1__',
          'Visa valid until: November',
          'Availability for work: from __Q2__ to October',
          'Heard about job: from the __Q3__',
        ], { 1: 'blue card', 2: 'July', 3: 'website' }, 'Questions 1-3'),
        note('Complete the notes below.\nWrite NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.', 'Manor Farm – Important information for fruit pickers', [
          '<strong>Picking season:</strong>',
          'Busiest month is __Q4__',
          'Exact picking dates depend on the __Q5__',
          '<strong>Payment:</strong>',
          'Pickers over 18 will earn £__Q6__ an hour',
          '<strong>Accommodation:</strong>',
          'None on the farm but there is a __Q7__ nearby',
          '<strong>Transport:</strong>',
          'Pickers are advised to travel around by __Q8__',
          '<strong>Documentation:</strong>',
          'Only pickers with a __Q9__ will be allowed to work',
          '<strong>Meals:</strong>',
          "Pickers must bring lunch and a day's supply of __Q10__",
        ], { 4: 'September', 5: 'weather', 6: '5.60', 7: 'campsite', 8: 'bike/bicycle', 9: 'passport', 10: 'water' }, 'Questions 4-10'),
      ],
      expl: {
        1: { v: 'Khi bà Chandler hỏi Ben có visa làm việc ở Anh không.', t: ['I mean, do you have a visa?', 'I have a thing called a blue card.'], p: 'Loại visa của Ben là “blue card” → blue card' },
        2: { v: 'Khi hỏi Ben có thể làm việc từ khi nào.', t: "Um, I'd like to do July, August and September, and could do October, if there's any work then.", p: 'Tháng 6 là lúc trang trại bắt đầu cần người (bẫy); Ben làm được từ tháng 7 đến tháng 10 → July' },
        3: { v: 'Khi hỏi Ben biết đến công việc qua đâu.', t: ['Did you find out about us through our website?', "That's right."], p: 'Ben biết qua website, không qua công ty môi giới (agency là bẫy) → website' },
        4: { v: 'Khi Ben nói về mùa hái quả.', t: 'I see you need most pickers in September for apples and pears, but the whole picking season can last about 16 weeks.', p: '“Need most pickers in September” = tháng bận nhất → September' },
        5: { v: 'Ngay sau đó, bà Chandler giải thích vì sao chưa có ngày cụ thể.', t: ["Well, yes, but it's a question of the weather.", "That's why I can't give you exact picking dates now."], p: 'Ngày hái chính xác phụ thuộc vào thời tiết → weather' },
        6: { v: 'Khi Ben hỏi tiền công.', t: "The rate is £4.50 an hour for the under-18s, but as you're over 18, it would rise to £5.60 an hour.", p: '£4.50 là mức cho người dưới 18 tuổi (bẫy); trên 18 tuổi được £5.60/giờ → 5.60' },
        7: { v: 'Khi nói về chỗ ở.', t: 'Yes, there is no accommodation on the farm but there is a campsite about 15 minutes away.', p: 'Trang trại không có chỗ ở nhưng gần đó có khu cắm trại → campsite' },
        8: { v: 'Khi nói về việc đi lại.', t: ['No, maybe I should bring my bike to get around.', 'Yes, we always recommend that.'], p: 'Ô tô (đường hẹp) và xe buýt (ít chuyến) đều là bẫy; trang trại khuyên đi xe đạp → bike' },
        9: { v: 'Khi nói về giấy tờ cần mang.', t: ["We will need proof of age, so we'll expect to see your passport.", "Pickers without one won't be allowed to work."], p: 'Bằng lái xe không được chấp nhận (bẫy); không có hộ chiếu thì không được làm → passport' },
        10: { v: 'Cuối bài, khi nói về bữa ăn.', t: "You'll need to bring your own food for lunch and, more importantly, enough water to last a full day.", p: '“Enough water to last a full day” = a day\'s supply of water → water' },
      },
    },
    {
      part: 2, title: 'Karrara Sports and Leisure Centre', audio: 'listening/test 1/test 1.mp3', clip: [441, 806], cover: 'sports leisure centre swimming pool | gym fitness centre',
      turns: [],
      fix: [
        ["Carrara's brand new", "Karrara's brand new"], ['Good evening and Welcome', 'Good evening and welcome'],
        ['is the shop.\nThank you.\nWe have a look in there later as we\'ve got', "is the shop.\nBe sure to have a look in there later as we've got"],
        ['So as well as the spa to help aching bodies.\nWe also have', 'So as well as the spa to help aching bodies, we also have'],
        ['and we offer physiotherapy', "and we'll offer physiotherapy"],
        ["all the classes and sports it's usually", "all the classes and sports.\nIt's usually"],
        ['If you prefer just the gym classes.\nYou may want', 'If you prefer just the gym classes, you may want'],
      ],
      groups: [
        map('Label the plan below.\nWrite the correct letter, A-I, next to Questions 11-16.', [[11, 'Shop', 'H'], [12, 'Playground', 'G'], [13, 'Spa', 'I'], [14, 'Weights room', 'D'], [15, 'Gym', 'B'], [16, 'Massage room', 'E']], { page: 4, box: [95, 192, 495, 492] }, 'Questions 11-16'),
        multi('Choose TWO letters, A-E.', 17, 'Which TWO memberships have a special introductory price?', ['Off-peak', 'Gym and Weights', 'Swim Plus', 'All-in', 'Family Pack'], ['A', 'D'], 'Questions 17-18'),
        multi('Choose TWO letters, A-E.', 19, 'Which TWO free gifts will new members get?', ['sports towel', 'heart monitor', 'water bottle', 'sports socks', 'free massage'], ['B', 'E'], 'Questions 19-20'),
      ],
      expl: {
        11: { v: 'Đầu bài, khi giới thiệu khu vực gần lối vào.', t: 'To one side of us, and right in front of you as you enter the complex, is the shop.', p: 'Cửa hàng nằm cạnh quán cà phê, ngay trước mặt khi bước vào từ lối vào → H' },
        12: { v: 'Khi nói về khu vui chơi.', t: 'On the other side of the cafe, and ideally situated between the cafe and the childminding facilities, we have the playground.', p: 'Khu vui chơi nằm giữa quán cà phê và khu trông trẻ (Child care) → G' },
        13: { v: 'Khi nói về bể bơi và bồn spa.', t: 'It has a 5-metre water slide, which will be very popular with kids of all ages, and in the corner nearest the changing rooms, we have a high-tech hot spa.', p: 'Spa ở góc bể bơi gần phòng thay đồ nhất → I' },
        14: { v: 'Khi nói về phòng tạ.', t: 'Well, we have a large weights room located at the cafe end of the administration block.', p: 'Phòng tạ ở đầu khu hành chính phía quán cà phê → D' },
        15: { v: 'Khi nói về phòng gym.', t: 'Another place to get a good workout is in the gym, which is shown on the map to the right of the changing rooms.', p: 'Phòng gym nằm bên phải phòng thay đồ → B' },
        16: { v: 'Khi nói về khu massage.', t: ["It's in the funny shaped room close to the administration area.", 'Its distinctive shape has already led to the nickname of the bullet room.'], p: 'Phòng có hình dạng lạ (hình viên đạn) gần khu hành chính → E' },
        17: { v: 'Khi giới thiệu các gói thành viên (chọn 2 đáp án).', t: "The other package we've reduced for this month only is the Off Peak.", p: 'Gói Gym and Weights chỉ được khen “good value”, gói Family rẻ hơn mua lẻ — không phải giá khuyến mãi; gói Off Peak được giảm giá trong tháng này → A' },
        18: { v: 'Như câu 17 (chọn 2 đáp án).', t: ['If you are a fitness freak, then choose our all-in membership.', "But for a short time, we're offering 12 months for the price of nine, which is a huge saving."], p: 'Gói All-in đang được ưu đãi 12 tháng với giá 9 tháng → D' },
        19: { v: 'Khi nói về quà tặng cho thành viên mới.', t: 'So not only are we going to give you a voucher for a session in our massage centre, a great way to unwind after your workout, but you\'ll also get this great device that measures your heart rate.', p: '“A device that measures your heart rate” = máy đo nhịp tim → B' },
        20: { v: 'Như câu 19 (chọn 2 đáp án).', t: ['So not only are we going to give you a voucher for a session in our massage centre', "And finally, just for turning up tonight, we'd like to give everyone here a drink bottle to take away with them."], p: 'Khăn và quần áo chỉ là “could have chosen” (bẫy); bình nước tặng mọi người có mặt chứ không riêng thành viên mới (key gốc ghi C là sai); quà thứ hai là phiếu massage miễn phí → E' },
      },
    },
    {
      part: 3, title: 'The Value Survey on House Prices', audio: 'listening/test 1/test 1.mp3', clip: [833.5, 1207.5], cover: 'house prices real estate | suburban houses new zealand',
      fix: [
        ["Thank you.\nOK, for this week's", "OK, for this week's"],
        ['So um first,', 'So, um, first,'],
        ['ways of calculating it?', 'ways of calculating it.'],
        ['But the problem is, there are.\nThere are too many', 'But the problem is, there are too many'],
        ['new rail networks.', 'new rail networks?'],
        ['think about how.\nHow house prices', 'think about how house prices'],
        ['by Professor Massey.\nBecause', 'by Professor Massey?\nBecause'],
        ['were interpreted, was open', 'were interpreted was open'],
      ],
      turns: [
        ['Tutor', "OK, for this week's"], ['James', 'All right.'], ['Anna', 'Sure, James.'], ['James', 'So, um, first,'],
        ['Anna', 'Well, it looked at all houses'], ['James', 'So it\'s about affordability'], ['Anna', "There's no information about the size"],
        ['James', "No, that's a limitation."], ['Anna', "Yeah, there's lots of these surveys"], ['James', 'OK, good point.'],
        ['Anna', 'Yeah, it is.'], ['James', 'So if more building sites'], ['Anna', "That's it, isn't it?"], ['James', 'Exactly.'],
        ['Anna', 'Well, what about transport?'], ['James', "Yeah, but the survey didn't mention it."], ['Anna', 'True.'],
        ['James', 'Exactly the same.'], ['Anna', 'The government may have to'], ['James', 'So we should look at some of the criticism'],
        ['Anna', "OK, so there's the economist"], ['James', 'Did you get that article'], ['Anna', 'Yeah, interesting.'],
        ['James', 'All right.\nThen, Richard Bernard'], ['Anna', 'OK.\nThen Professor Lowndes.'], ['James', "That's right.\nAfter all the work"],
        ['Anna', 'And the last one, Maria Darling.'], ['James', "There weren't enough of them"], ['Anna', "No, it wasn't that."],
        ['James', 'Right.\nSo a lot of criticism.'], ['Anna', 'Yeah, but this sort of research'],
      ],
      groups: [
        mc('Choose the correct letter, A, B or C.\nThe Value Survey on House Prices', [
          [21, 'According to James and Anna, the Value Survey measured the cost of houses by calculating', ['the total price of building a new house.', 'the size of house a typical family can afford.', 'the price of houses compared to average income.'], 'C'],
          [22, 'Anna says the Value Survey is unusual because', ['it compares prices in different cities.', 'it is the oldest survey of its kind.', 'it publishes its results annually.'], 'A'],
          [23, 'The students decide that New Zealand house prices are high because of', ['the cost of construction materials.', 'the shortage of builders.', 'the rules concerning land use.'], 'C'],
          [24, 'When the students talk about transport, they are', ['concerned there is no plan.', 'worried about rising costs.', 'alarmed by increasing congestion.'], 'A'],
          [25, 'The students agree that the next Value Survey will', ['compare a wider number of locations.', 'indicate a future trend in house prices.', 'advise against regulation of house prices.'], 'B'],
        ], 'Questions 21-25'),
        matching('What aspect of the Value Survey did each of the following people criticise?\nChoose FIVE answers from the box and write the correct letter, A-G, next to Questions 26-30.',
          ['organisation of final text', "researchers' qualifications", 'period covered', 'level of funding', 'lack of public access to full information', 'old-fashioned systems of data analysis', "way of defining home-buyers' wealth"], [
            [26, 'Andrew Coleman', 'C'],
            [27, 'Professor Massey', 'G'],
            [28, 'Richard Bernard', 'F'],
            [29, 'Professor Lowndes', 'A'],
            [30, 'Maria Darling', 'E'],
          ], { title: 'Aspects of the survey criticised', groupTitle: 'Questions 26-30' }),
      ],
      expl: {
        21: { v: 'Khi James hỏi khảo sát đo giá nhà bằng cách nào.', t: ['So it started with average incomes across the whole workforce, and then worked out house prices in relation to that.', "There's no information about the size of a house a typical family can buy."], p: 'Khảo sát tính giá nhà so với thu nhập trung bình; không có thông tin về diện tích nhà (bẫy B) → C' },
        22: { v: 'Khi Anna nói điểm khác biệt của Value Survey.', t: 'Value is actually one of the newer ones, but it stands out because it gives figures for a range of the largest urban centres, which none of the others do.', p: 'Đây là khảo sát mới (không phải lâu đời nhất); nó nổi bật vì có số liệu của nhiều đô thị lớn → so sánh giá ở các thành phố → A' },
        23: { v: 'Khi bàn vì sao nhà ở New Zealand đắt.', t: ['Because most of them are built of wood, and that\'s quite cheap.', 'But the problem is, there are too many regulations and restrictions about where you can build.', 'Because there are plenty of contractors ready to do the work.'], p: 'Vật liệu (gỗ) rẻ, thợ xây thì nhiều; nguyên nhân là quy định hạn chế nơi được xây → C' },
        24: { v: 'Khi nói về giao thông.', t: ['It should be a coordinated approach.', "Yeah, but the survey didn't mention it."], p: 'Cần một kế hoạch phối hợp nhưng khảo sát không đề cập → lo ngại không có kế hoạch → A' },
        25: { v: 'Khi bàn về khảo sát lần tới.', t: ['It\'ll look at all the same places, right?', 'Exactly the same.', 'But the next one will give an idea of the way prices are moving.'], p: 'Vẫn khảo sát đúng các nơi cũ (loại A); lần sau sẽ cho thấy xu hướng giá → B' },
        26: { v: 'Nhà kinh tế học Andrew Coleman.', t: ['He actually questioned whether the survey was money well spent.', 'Because it only looked at a single year in isolation.', 'So he thought the survey should consider a longer time frame.'], p: '“Money well spent” là bẫy (D); điều ông chê là khảo sát chỉ xét một năm, nên xét khoảng thời gian dài hơn (key gốc ghi D là sai) → C' },
        27: { v: 'Giáo sư Massey.', t: 'He realised the method used to calculate how much money people had didn\'t take savings into account.', p: 'Cách tính tiền của người mua nhà không tính khoản tiết kiệm → cách xác định mức giàu có của người mua → G' },
        28: { v: 'Richard Bernard.', t: 'He found out they were using quite outdated software to process all the information they gathered, which was crazy, because they actually had the money available for an upgrade.', p: 'Phần mềm xử lý dữ liệu lạc hậu; đội ngũ được đánh giá cao (loại B), có tiền nâng cấp (loại D) → F' },
        29: { v: 'Giáo sư Lowndes.', t: ['He thought the report was just badly written.', 'After all the work that went into gathering valid information, the finished report was just too long and weakly structured.'], p: 'Báo cáo cuối viết dở, quá dài, bố cục yếu → cách tổ chức văn bản cuối → A' },
        30: { v: 'Maria Darling.', t: ['But they were never identified for privacy reasons.', 'The process should have been transparent if the people are going to have full confidence in the survey.'], p: 'Không phải số lượng nhà ít; các căn nhà không được công bố → công chúng không tiếp cận được đầy đủ thông tin → E' },
      },
    },
    {
      part: 4, title: 'Drama Activities in the Classroom', audio: 'listening/test 1/test 1.mp3', clip: [1235, 1594], cover: 'children drama class role play | school play children acting',
      turns: [],
      fix: [
        ['Thank you.\nThank you I going to look at', "So, now we're going to look at"],
        ['which relies on everyone working together.\nAnd playing their part also helps', 'which relies on everyone working together and playing their part, also helps'],
        ['for voicing certain views getting children', 'for voicing certain views.\nGetting children'],
        ['a stronger more awareness of morality', 'a stronger awareness of morality'],
        ['\nYou now have 10 Minutes to Transfer your answers to the listening answer sheet', ''],
      ],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'Benefits of using drama activities in the classroom', [
          "<strong>Child's personal development</strong>",
          '• Group participation develops __Q31__ in own ideas',
          '• Unscripted, imaginative activities allow children to take __Q32__',
          "<strong>Child's educational development</strong>",
          '• Working as a group teaches the importance of __Q33__ to others',
          '• Performing makes children __Q34__ for their learning and behaviour',
          '<strong>Role-play can be used:</strong>',
          '• as a form of __Q35__ for children experiencing problems',
          '• to help children be objective about their behaviour problems',
          '• to explore controversial issues with a class in a __Q36__ environment',
          "• to explore children's self-knowledge and understanding of __Q37__",
          '<strong>Advantages of using role-play in the study of history</strong>',
          "• Drama activities increase children's __Q38__ in class",
          '• Makes it easier for children to __Q39__ and understand historical events',
          '• Can find answers to __Q40__ in history to see why certain decisions were made',
        ], { 31: 'confidence', 32: 'risks', 33: 'listening', 34: 'responsible', 35: 'therapy', 36: 'safe', 37: 'morality', 38: 'participation', 39: 'remember', 40: 'problems' }, 'Questions 31-40'),
      ],
      expl: {
        31: { v: 'Phần phát triển cá nhân, lợi ích thứ nhất.', t: 'Firstly, creating the space for children to express themselves freely in a group situation helps to give them confidence in their own opinions and ideas', p: '“Confidence in their own opinions and ideas” = confidence in own ideas → confidence' },
        32: { v: 'Lợi ích thứ hai.', t: 'Secondly, unscripted improvisation activities, where children work from their imagination, if done in a supportive way, give children the opportunity to gain experience in taking risks', p: 'Hoạt động ứng biến cho trẻ trải nghiệm việc chấp nhận rủi ro → risks' },
        33: { v: 'Phần phát triển học tập.', t: 'For example, the emphasis placed on cooperative activities in drama means that group members must learn the value of listening to one another.', p: '“The value of listening to one another” = the importance of listening to others → listening' },
        34: { v: 'Ngay sau đó, về việc biểu diễn.', t: 'And playing their part, also helps children to be responsible not only for their learning, but for their general behavior.', p: 'Biểu diễn giúp trẻ có trách nhiệm với việc học và hành vi → responsible' },
        35: { v: 'Phần giá trị của đóng vai.', t: 'The value of role play for children who are having difficulties as a means of therapy is now widely accepted.', p: '“As a means of therapy” = a form of therapy cho trẻ gặp khó khăn → therapy' },
        36: { v: 'Khi nói về chủ đề gây tranh cãi.', t: 'More generally, role play also allows the teacher to explore potentially controversial or taboo subjects in a safe setting in which children feel at ease.', p: '“A safe setting” = a safe environment → safe' },
        37: { v: 'Ngay sau đó.', t: 'Getting children to examine their thoughts and opinions carefully, can lead to a deeper self knowledge and a stronger awareness of morality.', p: 'Hiểu biết sâu hơn về bản thân và nhận thức về đạo đức → morality' },
        38: { v: 'Phần môn lịch sử.', t: "Bringing characters from the past to life in the classroom by doing classroom drama activities is an easy way to improve the level of the children's participation in the lesson.", p: '“Improve the level of participation” = increase participation → participation' },
        39: { v: 'Ngay sau đó, khi nói về tái hiện cảnh lịch sử.', t: 'but getting children to reenact scenes from history can also be extremely useful, as it helps them to remember what happened and why it was important', p: 'Tái hiện giúp trẻ nhớ điều đã xảy ra và vì sao nó quan trọng → remember' },
        40: { v: 'Cách thứ hai trong môn lịch sử.', t: ['Another way of doing this is to ask children to find solutions to historical problems using role play.', 'This can help to focus attention on why certain decisions were taken.'], p: '“Find solutions to historical problems” = find answers to problems in history → problems' },
      },
    },
  ],
};
