// Vol 3 – Test 9 (PDF "listening/test 9/Test 9.pdf" p2–7; key xlsx sheet Test 9; audio test 9/09 section 01–04.mp3).
// Transcript: Whisper + the whole-test Otter PDF (transcript/test 9.pdf — no "Section two, you will hear" in it, so P2
// starts at "end of section one"); turns by hand. P1: the example run (played first) is dropped.
// Source errors fixed: key Q2 "3 courses" → celebration (the blank is the menu's name: standard / celebration / gold);
// key Q11 "A" → B (he loved vacuum cleaners at 4 but got his first one, "the beginning of his collections", at 8);
// key Q31 "smell" → bear, Q33 "viewers" → bread (recording: "of all, the bear"; "a smell of newly baked bread … to
// encourage viewers"); Q16–20 instruction said "questions 26-30".
const { note, mc, matching } = require('../vol_build');

module.exports = {
  vol: 3, test: 9,
  sections: [
    {
      part: 1, title: 'Party Reservation at Shaw\'s Restaurant', audio: 'listening/test 9/09 section 01.mp3', cover: 'restaurant function room party | birthday party dinner',
      fix: [
        ["On this occasion only, the conversation relating to this will be played first.\nGood morning, Shaw's Restaurant.\nHi, I'd like to book one of your function rooms for a party, please.\nOkay, fine.\nHow many people are you expecting for the party?\nWell, I'm not quite sure yet, but about 60.\nThere are about 60 people expected, so 60 has been written in the space.\nGood morning Shaw's Restaurant.", "Good morning, Shaw's Restaurant."],
        ["That's £25 pounds per person.", "That's £25 per person."], ["That's £35 pounds.", "That's £35."], ['menu at 50 pounds.', 'menu at £50.'],
        ['anything like to have a meal please I need to check but I do know', "anything like shellfish, for example?\nI'll need to check, but I do know"],
        ["We aren't offering that service anymore.\nI'm afraid.", "We aren't offering that service anymore, I'm afraid."],
        ["I think she'd I prefer flowers", "I think she'd prefer flowers"],
        ["I'm Maria Nelson and my number's.\n07749132760.", "I'm Maria Nelson and my number's 07749 132760."],
      ],
      turns: [
        ['Receptionist', "Good morning, Shaw's"], ['Maria', "Hi, I'd like to book"], ['Receptionist', 'Okay, fine.'], ['Maria', "Well, I'm not quite sure yet"],
        ['Receptionist', 'Fine.\nSo you will need'], ['Maria', "The party's for my daughter's"], ['Receptionist', 'And what time would you like'],
        ['Maria', "Oh, I'm not sure."], ['Receptionist', 'Okay.'], ['Maria', 'And people will probably'], ['Receptionist', "Fine.\nWe're open until"],
        ['Maria', 'Excellent.'], ['Receptionist', 'And what about the menu?'], ['Maria', 'Yes, not a buffet.'], ['Receptionist', 'Right.\nWell, there are several'],
        ['Maria', 'OK.'], ['Receptionist', 'Or the celebration menu'], ['Maria', "Okay, I think I'd rather"], ['Receptionist', "And there's also our gold menu."],
        ['Maria', "No, that's definitely too expensive."], ['Receptionist', "Of course, we'll make sure"], ['Maria', 'Great.'],
        ['Receptionist', 'And do you know if any'], ['Maria', "I'll need to check"], ['Receptionist', "Okay, I'll make a note"], ['Maria', "Well, I'd like a choice"],
        ['Receptionist', 'Of course, no problem.'], ['Maria', 'Actually, I think a disco'], ['Receptionist', 'No problem.'], ['Maria', 'And I heard you might'],
        ['Receptionist', "We aren't offering"], ['Maria', 'Oh, I see.'], ['Receptionist', 'Now, the menu package'], ['Maria', 'Oh, like what?'],
        ['Receptionist', "We'll decorate the room"], ['Maria', 'She loves pink.'], ['Receptionist', 'No problem.\nNow, you mentioned'], ['Maria', 'Okay, yes.'],
        ['Receptionist', 'And we can put a special message'], ['Maria', 'Um, congratulations'], ['Receptionist', 'Fine.'], ['Maria', 'Now, one or two'],
        ['Receptionist', 'Absolutely.'], ['Maria', "I think that's all for now."], ['Receptionist', 'OK.\nWell, just get in touch'], ['Maria', "I'm Maria Nelson"],
        ['Receptionist', 'Excellent.\nWe look forward'],
      ],
      groups: [
        note('Complete the form below.\nWrite ONE WORD AND/OR A NUMBER for each answer.', 'Party Reservation', [
          'Example: Number of guests for the party: <em>60</em> people',
          'Starting time of the party: __Q1__ pm',
          '<strong>Menu options:</strong>',
          '- the standard ($25)',
          '- the __Q2__ ($35)',
          '- the gold ($50)',
          'each course has some __Q3__ option',
          'one guest is allergic to __Q4__',
          'other requests: desserts and __Q5__',
          'entertainment: book a __Q6__ after dinner',
          'room decoration: pink __Q7__',
          "Special request: write '__Q8__ Susie' on the birthday cake",
          'Book a __Q9__ to take guests to the Forest Hotel',
          'Phone number: __Q10__',
        ], { 1: '7.45/7:45', 2: 'celebration', 3: 'vegetarian', 4: 'strawberries', 5: 'cheese', 6: 'disco', 7: 'flowers', 8: 'congratulations', 9: 'taxi', 10: '07749 132760/07749132760' }, 'Questions 1-10'),
      ],
      expl: {
        1: { v: 'Khi nhân viên hỏi giờ thuê phòng.', t: ["Oh, I'm not sure.", 'Uh, 7.45?', 'Not too late.'], p: '11 giờ là lúc khách về, 11.30 là giờ nhà hàng đóng cửa (bẫy); tiệc bắt đầu lúc 7.45 → 7.45' },
        2: { v: 'Khi giới thiệu các thực đơn.', t: ['Or the celebration menu, which is three courses.', "That's £35."], p: 'Thực đơn £35 tên là “celebration” (ba món chỉ là mô tả — key gốc ghi “3 courses” là sai) → celebration' },
        3: { v: 'Khi Maria hỏi món cho khách không ăn thịt.', t: "Of course, we'll make sure there's a vegetarian option for each course.", p: 'Mỗi món đều có lựa chọn chay → vegetarian' },
        4: { v: 'Khi hỏi về dị ứng thức ăn.', t: "I'll need to check, but I do know that one of my daughter's friends is very allergic to strawberries.", p: 'Hải sản có vỏ chỉ là ví dụ của nhân viên (bẫy); bạn của con gái dị ứng dâu tây → strawberries' },
        5: { v: 'Khi nói về yêu cầu khác cho món tráng miệng.', t: ["Well, I'd like a choice, if possible.", 'And could we have cheese as well?'], p: 'Ngoài món tráng miệng, Maria muốn thêm phô mai → cheese' },
        6: { v: 'Khi nói về giải trí sau bữa tối.', t: ["You can book a band if you'd like live music.", 'Actually, I think a disco would be best if you can arrange that.'], p: 'Ban nhạc là gợi ý của nhân viên, pháo hoa không còn phục vụ (bẫy); Maria chọn disco → disco' },
        7: { v: 'Khi nói về trang trí phòng.', t: ['She loves pink.', "But actually, I think she'd prefer flowers to balloons, so let's go for them instead, in the same color."], p: 'Bóng bay bị thay bằng hoa, cùng màu hồng → flowers' },
        8: { v: 'Khi nói về bánh sinh nhật.', t: ['Um, congratulations and then her name.', "That's Susie."], p: 'Dòng chữ trên bánh là “Congratulations” rồi tên Susie → congratulations' },
        9: { v: 'Khi nói về khách đi tàu.', t: "Now, one or two of the guests are coming by train, but they stop running quite early, so they'll need a taxi to take them to the Forest Hotel after the party.", p: 'Tàu dừng chạy sớm nên cần taxi đưa khách về khách sạn Forest → taxi' },
        10: { v: 'Cuối bài, khi hỏi số điện thoại.', t: "I'm Maria Nelson and my number's 07749 132760.", p: 'Số điện thoại được đọc ở cuối cuộc gọi → 07749 132760' },
      },
    },
    {
      part: 2, title: 'The Vacuum Cleaner Museum', audio: 'listening/test 9/09 section 02.mp3', cover: 'vintage vacuum cleaner | old vacuum cleaner museum',
      turns: [],
      fix: [
        ['End of Section one.\n', ''],
        ["Yes, that's right Vacuum cleaners, the machines", "Yes, that's right, vacuum cleaners, the machines"],
        ["The museums opened", "The museum's opened"],
        ['thrown away on the streets he took it home', 'thrown away on the streets, he took it home'],
        ['the final count of 30 of 126,', 'the final count of 126,'],
        ["Loading on now a common household appliance, it wasn't until 1950s", "Although now a common household appliance, it wasn't until the 1950s"],
        ["Vacuumland that dedicated", "Vacuumland that's dedicated"],
        ['from 9.30 a.m to 5.30 p.m from Tuesdays', 'from 9.30 a.m. to 5.30 p.m. from Tuesdays'], ['until 7 p.m and Mondays', 'until 7 p.m., and Mondays'],
        ['adapted to be right back by electricity', 'adapted to be powered by electricity'],
        ['The Electrolytes Model 5', 'The Electrolux Model V'],
        ['which were not easily bought from', 'which were not easily moved'],
        ['the Electrolytes 30, or XXX,', 'the Electrolux 30, or Triple X,'],
        ['Kirby made pieces trophy, but they also manufacture vacuum cleaners for everyday use, as sold only', 'Kirby made this piece as a trophy, but they also manufacture vacuum cleaners for everyday use, which are sold only'],
      ],
      groups: [
        mc('Choose the correct letter, A, B or C.', [
          [11, 'When did James Brown start collecting vacuum cleaners?', ['at 4 years old', 'at 8 years old', 'at 30 years old'], 'B'],
          [12, 'James can listen to a vacuum cleaner and identify', ['which company made it', 'what problem it might have', 'the age of the battery life'], 'A'],
          [13, 'Before the 1950s, vacuum cleaners cost', ['the same price as an average car', "almost a whole year's salary", "about three months' wages"], 'C'],
          [14, 'Why did James make a trip to the USA a few years ago?', ['to win an award in Texas', 'to visit the Kirby Factory', 'to meet some vacuum collectors'], 'B'],
          [15, 'On what day is the vacuum cleaner museum open late?', ['Tuesday to Saturday', 'Monday', 'Thursday'], 'C'],
        ], 'Questions 11-15'),
        matching('Which characteristic does each of the following vacuum cleaners have?\nChoose FIVE answers from the box and write the correct letter, A-G, next to Questions 16-20.',
          ['not available in shops', 'specially designed to be easy to move', 'as large as a horse', 'used two different sources of power', 'designed by a businessman', 'named after a person other than the inventor', 'associated with a style of building'], [
            [16, 'Puffing Billy', 'D'],
            [17, 'Hoover', 'F'],
            [18, 'Electrolux Model V', 'B'],
            [19, 'Electrolux Triple X', 'G'],
            [20, 'Kirby', 'A'],
          ], { title: 'Characteristics', groupTitle: 'Questions 16-20' }),
      ],
      expl: {
        11: { v: 'Khi kể James bắt đầu sưu tầm.', t: ['James first fell in love with vacuum cleaners when he was only four years old.', "However, it wasn't until James was eight years old that he first acquired his own vacuum cleaner.", 'And that was the beginning of his collections.'], p: '4 tuổi chỉ là lúc bắt đầu thích (bẫy A), 30 là số máy khi ở tuổi teen (bẫy C); 8 tuổi có chiếc đầu tiên, khởi đầu bộ sưu tập (key gốc ghi A là sai) → B' },
        12: { v: 'Khi kể trò bịt mắt đoán máy.', t: 'When I tested him out on five different machines, switching them on and pushing them across the floor, he had no problem telling me the manufacturer of each one, and he could even tell its age.', p: '“The manufacturer” = công ty sản xuất ra nó → A' },
        13: { v: 'Khi nói về giá máy hút bụi trước những năm 1950.', t: "In today's money, you would have had to pay around a third of the price for an average car, which is around three months' wages for most people.", p: 'Bằng một phần ba giá ô tô (không phải bằng giá ô tô) = khoảng ba tháng lương → C' },
        14: { v: 'Khi nói về chuyến đi Mỹ.', t: 'and a few years ago, he made a special trip to the USA to the factory of his favorite, the Kirby Vacuum Cleaner.', p: 'Hội nghị ở Texas là sự kiện năm nay, gặp người sưu tầm là việc “might want” làm (bẫy); chuyến đi trước đây là thăm nhà máy Kirby → B' },
        15: { v: 'Khi nói về giờ mở cửa.', t: "Well, they're open all year round from 9.30 a.m. to 5.30 p.m. from Tuesdays to Saturdays, except Thursdays when they're open until 7 p.m., and Mondays when the museum is closed.", p: 'Thứ Năm mở cửa đến 7 giờ tối, thứ Hai đóng cửa → C' },
        16: { v: 'Khi nói về Puffing Billy.', t: ['It was so large it had to be pulled by horses, and parked outside the house where the cleaning was being done.', 'It was initially driven by an oil engine, although it was later adapted to be powered by electricity'], p: 'Ngựa chỉ kéo máy chứ không nói to bằng con ngựa (bẫy C); chạy bằng động cơ dầu rồi bằng điện → hai nguồn năng lượng → D' },
        17: { v: 'Khi nói về máy Hoover.', t: ["It's often thought that it was created by a Mr. Hoover, but in fact, it was created by a James Spangler, who worked as a cleaner in a department store.", 'Mr. Hoover was a businessman who bought the idea and then developed and marketed it in the USA and other countries.'], p: 'Người phát minh là Spangler, máy mang tên ông Hoover (doanh nhân chỉ mua ý tưởng — bẫy E) → F' },
        18: { v: 'Khi nói về Electrolux Model V.', t: ['Up until that time, vacuum cleaners had been heavy devices, which were not easily moved.', 'This was a lighter model, which laid on the floor and can be pulled along on two strips of metal'], p: 'Mẫu nhẹ hơn, kéo đi được trên hai thanh kim loại → được thiết kế để dễ di chuyển → B' },
        19: { v: 'Khi nói về Electrolux Triple X.', t: 'and is perhaps the most visually elegant vacuum cleaner of all, with its sleek lines inspired by the Art Deco architecture, popular in the 1930s.', p: 'Đường nét lấy cảm hứng từ kiến trúc Art Deco → gắn với một phong cách kiến trúc → G' },
        20: { v: 'Cuối bài, khi nói về Kirby.', t: "but they also manufacture vacuum cleaners for everyday use, which are sold only by salesmen who demonstrated them only in the customer's home.", p: 'Chỉ bán qua nhân viên đến tận nhà khách → không có ở cửa hàng → A' },
      },
    },
    {
      part: 3, title: 'The Role of Health Visitors', audio: 'listening/test 9/09 section 03.mp3', cover: 'nurse mother baby | midwife baby',
      fix: [
        ["Harris and a student called Lisa discussing Lisa's postgraduate research project on the role of health visitors.\n", ''],
        ['Okay but there are other', 'Okay, but there are other'],
        ['effect of a newborn baby.\nRight?', 'effect of a newborn baby.\nRight.'],
      ],
      turns: [
        ['Dr Harris', 'Hi, Lisa.'], ['Lisa', 'Well, I enjoyed my first degree'], ['Dr Harris', 'Excellent.'], ['Lisa', 'From what I read'],
        ['Dr Harris', 'Yes, some health visitors'], ['Lisa', 'Yes.\nWhat I really want'], ['Dr Harris', 'Right.'], ['Lisa', 'Another area, which I am thinking'],
        ['Dr Harris', "That's an area I'd stay clear of"], ['Lisa', 'Okay, will do.'], ['Dr Harris', 'A good idea, but'], ['Lisa', 'And peer relationships'],
        ['Dr Harris', 'Okay, but there are other'], ['Lisa', 'Right.'],['Dr Harris', 'You need to consider the impact'],
        ['Lisa', 'Of course, the additional expense'], ['Dr Harris', 'Certainly all those matters'], ['Lisa', 'This is the area where'],
        ['Dr Harris', 'Very much so.'], ['Lisa', 'Yes, I appreciate that.'], ['Dr Harris', 'Now, your book list.'], ['Lisa', "Well, I wasn't sure"],
        ['Dr Harris', 'Yes, some of it may not'], ['Lisa', 'I understand.'], ['Dr Harris', "It's an excellent buy"], ['Lisa', "I've already ordered"],
        ['Dr Harris', "Well, it's very expensive"], ['Lisa', 'And what about the future'], ['Dr Harris', 'Useful in a utilitarian sense?'],
        ['Lisa', 'And resources for health visitors?'], ['Dr Harris', 'Strangely enough,'], ['Lisa', 'Okay.'],
      ],
      groups: [
        mc('Choose the correct letter, A, B or C.\nThe Role of Health Visitors', [
          [21, "In the context of Lisa's research project, Dr Harris suggests she should", ['re-think the focus of her research', 'be prepared to be flexible', 'narrow the scope'], 'B'],
          [22, 'Which topic area does Dr Harris advise Lisa to avoid investigating?', ['pre-schools', 'nurseries', 'child-minders'], 'C'],
          [23, 'The main reason why Lisa wants to film very young children is', ['to watch how they play', 'to look at their relationships', 'to study their language'], 'C'],
          [24, 'According to Dr Harris, how might the arrival of a new baby affect a family?', ['other children may feel jealous', 'parents may be put under pressure', 'sufficient support may not be available'], 'B'],
          [25, 'Dr Harris agrees with Lisa that she needs to find out about', ['legal constraints', 'family considerations', 'medical circumstances'], 'A'],
        ], 'Questions 21-25'),
        matching('What feature does Dr Harris identify for each of the following textbooks?\nChoose FIVE answers from the box and write the correct letter, A-G, next to Questions 26-30.',
          ['global coverage but sometimes inaccurate', 'interesting but rather unrealistic', 'practical and full of thoughtful tips', 'up-to-date with an international approach', 'wide ranging but poorly organised', 'good value despite some omissions', 'extremely costly but comprehensive'], [
            [26, 'Worldwide Healthcare Policies', 'D'],
            [27, 'Supporting Vulnerable Families', 'F'],
            [28, 'Health Visitors and Child Protection', 'G'],
            [29, 'The Future of Health Visiting', 'B'],
            [30, 'Resources for Health Visitors', 'E'],
          ], { title: 'Features', groupTitle: 'Questions 26-30' }),
      ],
      expl: {
        21: { v: 'Khi Dr Harris nhận xét hướng nghiên cứu của Lisa.', t: ['And your focus, the role of a health visitor in the community, is spot on.', 'But at this stage, you need to keep an open mind so you can respond to initial findings once you get underway.'], p: 'Trọng tâm đã đúng (loại A); cần giữ tư duy mở để thích ứng với kết quả ban đầu → sẵn sàng linh hoạt → B' },
        22: { v: 'Khi Lisa liệt kê các mảng muốn tìm hiểu.', t: ["I thought I'd also include childminders, the individuals in the area of Haines that might not be qualified, but look after young children.", "That's an area I'd stay clear of, as it's very complex."], p: '“Stay clear of” = tránh; người trông trẻ quá phức tạp → C' },
        23: { v: 'Khi bàn về việc quay phim trẻ nhỏ.', t: 'And peer relationships between children, as well as the ways in which they relate and play with each other, especially when they are around 2 to 3 years old, although early use of language is my main interest.', p: 'Quan hệ và cách chơi chỉ là phụ; mối quan tâm chính là ngôn ngữ ban đầu → C' },
        24: { v: 'Khi nói về ảnh hưởng của em bé mới sinh.', t: ['You need to consider the impact of this on the parents, particularly if the family lives in poor economic circumstances.', 'There\'s plenty of help available.'], p: 'Hỗ trợ thì có nhiều (loại C), không nhắc ghen tị (loại A); Dr Harris nói tác động lên bố mẹ, nhất là khi khó khăn kinh tế → áp lực → B' },
        25: { v: 'Khi Lisa hỏi về luật gia đình.', t: ["This is the area where I will need to be familiar with family law, isn't it?", 'Very much so.', 'But you\'ll find that in most circumstances, you will have to refer to the law to understand how far a health visitor can intervene.'], p: 'Hai người đồng ý cần hiểu luật để biết health visitor được can thiệp đến đâu → giới hạn pháp lý → A' },
        26: { v: 'Cuốn Worldwide Health Care Policies.', t: ["Well, I wasn't sure how relevant it would be, but it's a new edition, so the information is current.", "Yes, some of it may not be relevant but it's important to keep abreast of developments in other countries"], p: 'Bản mới nên thông tin cập nhật, nói về các nước khác → cập nhật, cách tiếp cận quốc tế → D' },
        27: { v: 'Cuốn Supporting Vulnerable Families.', t: "It's an excellent buy considering the price, even though it does leave a few things out.", p: '“Excellent buy considering the price” = good value, “leave a few things out” = some omissions → F' },
        28: { v: 'Cuốn Health Visitors and Child Protection.', t: "Well, it's very expensive, but it's a sound investment, and there aren't many textbooks which cover as much detail as this.", p: 'Rất đắt nhưng chi tiết hiếm sách nào bằng → đắt nhưng toàn diện → G' },
        29: { v: 'Cuốn The Future of Health Visiting.', t: ["But it's stimulating in the way the writer considers what health visiting could be like in a perfect world.", "I'd suggest dipping into it to discover the improvements which could be made if money were no object."], p: '“Stimulating” = interesting; “in a perfect world”, “if money were no object” = không thực tế → B' },
        30: { v: 'Cuốn Resources for Health Visitors.', t: "It offers a huge variety of activities and strategies which are great when working with young children, but they're presented in a rather haphazard way and the index isn't much use either.", p: 'Rất nhiều hoạt động nhưng trình bày lộn xộn → phong phú nhưng tổ chức kém → E' },
      },
    },
    {
      part: 4, title: 'The Sense of Smell', audio: 'listening/test 9/09 section 04.mp3', cover: 'sense of smell nose | smelling coffee aroma',
      turns: [],
      fix: [
        ['on human perception that is our sense of smell', 'on human perception, that is, our sense of smell'],
        ['sense of smell of all the bear.', 'sense of smell of all, the bear.'],
        ['They danced more rated', 'They danced more, rated'],
        ['let people relying on their emotions', 'led people to rely on their emotions'],
        ['observed the subject brain activity', "observed the subjects' brain activity"],
        ['affected people responses', "affected people's responses"],
      ],
      groups: [
        note('Complete the notes below.\nWrite ONE WORD ONLY for each answer.', 'Course on the Sense of Smell', [
          '<strong>Background</strong>',
          "- People's sense of smell is not as developed as that of some animals",
          '- Animal with the most accurate sense of smell is the __Q31__',
          "- There is a misconception that people's sense of smell is weak",
          "- In fact subtle smells have great impacts on people's mood",
          "- People's noses cannot detect the __Q32__ of the odour",
          '<strong>Practical examples of how smell affects us</strong>',
          '- Estate agents arranged the smell of newly made __Q33__ to encourage clients to buy the property quickly',
          '- Dutch researchers found out that the odour of __Q34__ makes people like to go to clubs',
          '- The smell of detergent makes students __Q35__ the kitchen after using it',
          '- A recent study showed that people make decisions depending on __Q36__',
          "<strong>Experiments on how smells tell us people's feelings</strong>",
          '- A group of scientists chose some sweat samples from sky divers',
          '- Then they picked up the same subjects who worked out in a __Q37__',
          '- The result showed people reacted more strongly to the sky dive sweat',
          '- Some scientists also found out that angry faces pose a __Q38__',
          '- Some psychologists try to test some students whether they can smell __Q39__',
          '- A chef lost her sense of smell, but regained the ability by smelling __Q40__ on a daily basis',
        ], { 31: 'bear', 32: 'source', 33: 'bread', 34: 'oranges/orange', 35: 'clean', 36: 'emotions', 37: 'gym', 38: 'threat', 39: 'chocolate', 40: 'spices' }, 'Questions 31-40'),
      ],
      expl: {
        31: { v: 'Đầu bài, khi so sánh khứu giác người và động vật.', t: "It's often said that our ability to sense smells is much less developed than that of animals such as the dog or a fish such as the shark, or of course, the creature, which is believed to have the most acute sense of smell of all, the bear.", p: 'Chó và cá mập chỉ là ví dụ; loài có khứu giác nhạy nhất là gấu (key gốc ghi “smell” là sai) → bear' },
        32: { v: 'Khi giải thích vì sao ta không nhận ra tác động của mùi.', t: "One possible reason is that our noses aren't well equipped to detect the source of an odor, and so we dismiss it.", p: 'Mũi không giỏi xác định nguồn gốc mùi → source' },
        33: { v: 'Ví dụ về môi giới nhà đất.', t: 'They often suggest that people who want to sell a house arrange things so that there is a smell of newly baked bread on the property to encourage viewers to want to buy it.', p: '“Viewers” là người xem nhà = clients; mùi được tạo ra là bánh mì mới nướng (key gốc ghi “viewers” là sai) → bread' },
        34: { v: 'Nghiên cứu ở hộp đêm của Hà Lan.', t: 'They discovered, rather to their surprise, that when the aroma of oranges was pumped into the venue, the guests partied harder.', p: 'Mùi cam làm khách vui chơi nhiệt tình hơn → oranges' },
        35: { v: 'Nghiên cứu về chất tẩy rửa.', t: 'Another study found that the hint of a smell wafting out of a hidden bucket of lemon scented detergent was enough to persuade students to clean the communal kitchen after using it', p: 'Mùi chất tẩy khiến sinh viên dọn bếp chung sau khi dùng → clean' },
        36: { v: 'Nghiên cứu về khả năng ra quyết định.', t: 'It found that subjecting people to a new smell, either good or bad, led people to rely on their emotions to make a decision, rather than relying on logic.', p: 'Mùi lạ khiến người ta quyết định dựa vào cảm xúc thay vì logic → emotions' },
        37: { v: 'Thí nghiệm mồ hôi người nhảy dù.', t: 'They also took sweat samples from the same people after they had worked up their sweat in a gym, a situation where no fear is involved.', p: 'Mẫu mồ hôi thứ hai lấy khi chính những người đó tập ở phòng gym → gym' },
        38: { v: 'Khi nói về phản ứng với nét mặt.', t: 'Normally, people pay more attention to angry faces because they pose a threat.', p: 'Gương mặt giận dữ là mối đe doạ → threat' },
        39: { v: 'Thí nghiệm luyện mũi.', t: 'They persuaded 32 students to wear blindfolds and ear defenders and see whether they could sniff out a trail of chocolate.', p: 'Sinh viên bịt mắt lần theo vệt mùi sô-cô-la → chocolate' },
        40: { v: 'Cuối bài, ví dụ về đầu bếp.', t: 'Knowing that her job depended on her having a good nose, she trained herself gradually by sniffing spices for ten minutes a day.', p: 'Ngửi gia vị 10 phút mỗi ngày → spices' },
      },
    },
  ],
};
